##############################################################################
# CML QSP Model — mrgsolve ODE Implementation (PK/PD-refactored sibling)
# Chronic Myeloid Leukemia: BCR-ABL Kinetics, TKI PK/PD, Resistance, TFR
#
# This file is a PK/PD-interface refactor of `cml_mrgsolve_model.R`, per
# `FORK_WORKFLOW_GUIDE.md` Part 2 and `chronic-myeloid-leukemia/cml_refactor_notes.md`.
# Scope: ONLY the four TKI compounds' PK compartments and their Hill effect
# terms were renamed/reorganized to the guide's `<ROLE>_<STEM>` convention
# (Asciminib=ASC, Dasatinib=DAS, Imatinib=IMT, Nilotinib=NIL) plus two
# mechanical, non-numeric build-compatibility fixes (see notes). Every other
# equation — normal hematopoiesis, leukemic hierarchy, sensitive/resistant
# clone dynamics, immune kill terms, BCR-ABL IS% scoring — is byte-identical
# to the original.
#
# Framework: Michor et al. (2005) Nature 435:1267-1270 (leukemic hierarchy)
#            + TKI PK/PD (IRIS, ENESTnd, DASISION, ASCEMBL calibration)
#            + Sensitive/Resistant clone dynamics (T315I)
#
# Author: Generated by Claude Code (CCR) — 2026-06-20; PK/PD-refactored 2026-08-30
# References: Michor 2005; Roeder 2006; IRIS 2003; ENESTnd 2010;
#             DASISION 2010; ASCEMBL 2021; OPTIC 2022
##############################################################################

library(mrgsolve)
library(dplyr)
library(ggplot2)
library(tidyr)

# ============================================================
# MODEL CODE
# ============================================================
cml_code <- '
$PROB
CML QSP Model — BCR-ABL Hierarchy + TKI PK/PD + Resistance
Calibrated to IRIS, ENESTnd, DASISION, ASCEMBL clinical trials.
PK/PD-refactored: each TKI now exposes exactly one named C_<STEM> concentration
and one named EFFECT_<STEM> Hill term (two for asciminib — sensitive + T315I).

$PARAM @annotated
// --- Normal Hematopoiesis Parameters ---
ay0   : 0.008 : HSC self-renewal rate (Michor 2005 calibrated)
by0   : 0.004 : HSC differentiation rate
dy0   : 0.003 : HSC death rate
ay1   : 0.0   : CMP self-renewal (transit amplifying)
by1   : 0.05  : CMP differentiation rate
dy1   : 0.02  : CMP death rate
by2   : 0.2   : GMP differentiation rate
dy2   : 0.05  : GMP death rate
dy3   : 0.10  : Mature cell (neutrophil) death rate
// Amplification factors (normal)
c1    : 10.0  : HSC->CMP amplification
c2    : 8.0   : CMP->GMP amplification
c3    : 16.0  : GMP->Neutrophil amplification

// --- CML Leukemic Hierarchy Parameters ---
// LSC (x0q = quiescent, x0p = cycling)
a0    : 0.04  : LSC self-renewal rate (BCR-ABL driven, > normal)
b0    : 0.01  : LSC differentiation rate
d0    : 0.003 : LSC death rate (baseline, low due to BCR-ABL)
q_act : 0.005 : Quiescent LSC activation rate (G0->cycling)
q_dorm: 0.02  : LSC quiescence induction rate
// LPC proliferation
a1    : 0.03  : LPC1 self-renewal
b1    : 0.08  : LPC1 differentiation
d1    : 0.015 : LPC1 death rate
b2    : 0.15  : LPC2 differentiation
d2    : 0.04  : LPC2 death rate
d3    : 0.12  : Leukemic blast death rate
// Amplification (leukemic, higher than normal)
lc1   : 15.0  : LSC->LPC1 amplification
lc2   : 10.0  : LPC1->LPC2 amplification
lc3   : 20.0  : LPC2->WBC amplification

// --- Sensitive Clone Parameters ---
as0   : 0.035 : Sensitive LSC self-renewal
bs0   : 0.012 : Sensitive LSC differentiation
ds0   : 0.004 : Sensitive LSC death
asp   : 0.04  : Sensitive progenitor proliferation
dsp   : 0.02  : Sensitive progenitor death

// --- Resistant Clone (T315I) Parameters ---
ar0   : 0.032 : Resistant LSC self-renewal (slight fitness cost)
br0   : 0.010 : Resistant LSC differentiation
dr0   : 0.005 : Resistant LSC death
arp   : 0.038 : Resistant progenitor proliferation
drp   : 0.022 : Resistant progenitor death
mu    : 1e-8  : Mutation rate per cell division (WT->T315I)

// --- Imatinib (IMT) PK Parameters (IRIS trial) -- [was ka_imt/F_imt/Vd_imt/CL_imt/Kin_imt/Kout_imt/IC50_imt/Emax_imt/Hill_imt]
// 400 mg/day standard; 800 mg/day high-dose
KA_IMT    : 0.8    : Absorption rate constant (h^-1), Tmax~2h
F_IMT     : 0.98   : Oral bioavailability
V1_IMT    : 435.0  : Volume of distribution (L), Cp,ss ~1-2 uM
CL_IMT    : 14.0   : Total clearance (L/h), t1/2~18h
KIN_IMT   : 0.5    : OCT1-mediated influx into intracellular compartment (h^-1)
KOUT_IMT  : 0.3    : Intracellular efflux (ABCB1) rate constant (h^-1)
EC50_IMT  : 0.25   : IC50 imatinib (uM, intracellular BCR-ABL inhibition; PD reads intracellular, not plasma)
EMAX_IMT  : 0.90   : Maximum effect (90% kill of sensitive cells)
GAMMA_IMT : 1.2    : Hill coefficient

// --- Dasatinib (DAS) PK Parameters (DASISION trial) -- [was ka_das/F_das/Vd_das/CL_das/Kic_das/Kout_das/IC50_das/Emax_das/Hill_das]
KA_DAS    : 3.5    : Absorption rate (h^-1) -- UNUSED in this file's own ODE, same as in the original: there is no GUT_DAS depot compartment, dosing enters CENT_DAS directly as a zero-order rate ("continuous approximation, rapid Tmax"). Dead parameter, carried over verbatim, not invented.
F_DAS     : 0.24   : Bioavailability (14-34%)
V1_DAS    : 2505.0 : Volume of distribution (L), highly distributed
CL_DAS    : 220.0  : Total clearance (L/h), t1/2~5-6h
KIC_DAS   : 0.8    : Intracellular accumulation rate constant (h^-1)
KOUT_DAS  : 0.4    : Intracellular efflux (h^-1)
EC50_DAS  : 0.025  : IC50 dasatinib (uM, ~10x more potent than imatinib; PD reads intracellular)
EMAX_DAS  : 0.95   : Maximum effect
GAMMA_DAS : 1.1    : Hill coefficient

// --- Nilotinib (NIL) PK Parameters (ENESTnd trial) -- [was ka_nil/F_nil/Vd_nil/CL_nil/Kic_nil/Kout_nil/IC50_nil/Emax_nil/Hill_nil]
// 300 mg BID; fasting required
KA_NIL    : 0.6    : Absorption rate (h^-1), slower (fasting)
F_NIL     : 0.35   : Bioavailability (fasting; food up to 4-fold but CL also up)
V1_NIL    : 3100.0 : Volume of distribution (L)
CL_NIL    : 42.0   : Total clearance (L/h), t1/2~17h
KIC_NIL   : 0.6    : Intracellular accumulation rate constant (h^-1)
KOUT_NIL  : 0.35   : Intracellular efflux (h^-1)
EC50_NIL  : 0.02   : IC50 nilotinib (uM, ~20x more potent than imatinib; PD reads intracellular)
EMAX_NIL  : 0.93   : Maximum effect
GAMMA_NIL : 1.15   : Hill coefficient

// --- Asciminib (ASC) PK Parameters (ASCEMBL, OPTIC trials) -- [was ka_asc/F_asc/Vd_asc/CL_asc/IC50_asc/IC50_asc_r/Emax_asc/Emax_asc_r/Hill_asc]
// 40 mg BID standard; 200 mg BID for T315I
KA_ASC        : 1.2    : Absorption rate (h^-1)
F_ASC         : 0.72   : Bioavailability (~72%)
V1_ASC        : 95.0   : Volume of distribution (L)
CL_ASC        : 7.5    : Total clearance (L/h), t1/2~8.7h
EC50_ASC      : 0.0005 : IC50 asciminib vs sensitive/WT BCR-ABL (uM, 0.5 nM, very potent STAMP); PD reads plasma directly (no intracellular compartment in the original)
EMAX_ASC      : 0.90   : Maximum effect (sensitive)
GAMMA_ASC     : 1.3    : Hill coefficient (sensitive)
EC50_ASC_T315I: 0.004  : IC50 asciminib vs T315I resistant clone (200mg BID needed, uM)
EMAX_ASC_T315I: 0.82   : Maximum effect vs T315I
GAMMA_ASC_T315I: 1.3   : Hill coefficient (T315I) -- same numeric value as GAMMA_ASC; the original used one shared Hill_asc for both effect terms, split here into two independently-named parameters per compound-effect pair, values unchanged

// --- Tumor suppression / competition ---
Kcomp : 1e-9     : Competition coefficient (density dependence)
K_total : 1e12   : Carrying capacity (total cells in marrow)

// --- Drug switches (0=off, 1=on) ---
dose_imt : 0  : Imatinib dose (mg/day)
dose_das : 0  : Dasatinib dose (mg/day)
dose_nil : 0  : Nilotinib dose (mg/day, BID; specify daily total)
dose_asc : 0  : Asciminib dose (mg/day, BID; specify daily total)

// --- Immune parameters ---
kNK_kill : 0.001 : NK cell kill rate of leukemic cells
kCTL_kill: 0.0005 : CTL kill rate of leukemic cells
NK_base  : 1e8   : Baseline NK cell count
CTL_base : 5e7   : Baseline CTL count
NK_imt_effect : 0.3 : Imatinib immune restoration (% NK increase)

$INIT @annotated
// Steady-state normal hematopoiesis (Michor 2005 calibrated)
y0  : 1e4    : HSC (normal hematopoietic stem cells) initial count
y1  : 5e4    : CMP (common myeloid progenitor, normal) initial count
y2  : 4e5    : GMP (granulocyte-macrophage progenitor, normal) initial count
y3  : 4e9    : Neutrophils_normal (mature blood cells) initial count (4e9/L x ~1L BM equivalent)
// CML at diagnosis (CP phase): ~10^12 leukemic cells total
x0q : 1e4    : LSC_quiescent (BCR-ABL+ quiescent, TKI-refractory) at diagnosis
x0p : 2e3    : LSC_cycling (BCR-ABL+ proliferating, TKI-sensitive) at diagnosis
x1  : 1e7    : LPC1 (leukemic progenitor committed) at diagnosis
x2  : 5e7    : LPC2 (leukemic progenitor differentiated) at diagnosis
x3  : 5e10   : WBC_leukemic (mature CML cells / blasts) at diagnosis (WBC ~80e9/L)
xs  : 8e3    : LSC_sensitive (TKI-sensitive, BCR-ABL WT), majority at diagnosis
xsp : 8e6    : LPC_sensitive (sensitive progenitors)
xr  : 10     : LSC_resistant (T315I/resistant LSC), rare at diagnosis (~10 cells)
xrp : 100    : LPC_resistant (resistant progenitors)
// Imatinib (IMT) PK -- all zero at t=0 [was Gut_imt/Cp_imt/Cic_imt]
GUT_IMT  : 0 : Imatinib gut depot
CENT_IMT : 0 : Imatinib plasma concentration (uM) -- state IS the concentration by construction, see PK note in refactor notes
IC_IMT   : 0 : Imatinib intracellular concentration (uM) -- PD-facing (bespoke biophase compartment)
// Dasatinib (DAS) PK -- all zero at t=0 [was Cp_das/Cic_das]
CENT_DAS : 0 : Dasatinib plasma concentration (uM), no depot (continuous-rate input, see PK note)
IC_DAS   : 0 : Dasatinib intracellular concentration (uM) -- PD-facing (bespoke biophase compartment)
// Nilotinib (NIL) PK -- all zero at t=0 [was Gut_nil/Cp_nil/Cic_nil]
GUT_NIL  : 0 : Nilotinib gut depot
CENT_NIL : 0 : Nilotinib plasma concentration (uM)
IC_NIL   : 0 : Nilotinib intracellular concentration (uM) -- PD-facing (bespoke biophase compartment)
// Asciminib (ASC) PK -- all zero at t=0 [was Gut_asc/Cp_asc]
GUT_ASC  : 0 : Asciminib gut depot
CENT_ASC : 0 : Asciminib plasma concentration (uM) -- PD-facing directly (no intracellular compartment in the original)

$ODE
// ============================================================
// Helper: MW conversions for dose (mg) -> umol
// Imatinib MW = 493.6 g/mol; Dasatinib = 488.0; Nilotinib = 529.5; Asciminib = 449.5
// Dose entered as mg/day; rate into gut = Dose/24 mg/h (continuous infusion approx)
// ============================================================

double dose_rate_imt = dose_imt / 24.0 / 493.6 * 1000.0;  // umol/h
double dose_rate_das = dose_das / 24.0 / 488.0 * 1000.0;
double dose_rate_nil = dose_nil / 24.0 / 529.5 * 1000.0;
double dose_rate_asc = dose_asc / 24.0 / 449.5 * 1000.0;

// ============================================================
// PK ODEs -- one clearly-delimited block per compound
// ============================================================

// --- Imatinib (IMT) PK: Archetype 3 (depot + central, linear) plus a
// bespoke intracellular biophase compartment (IC_IMT) that only receives
// from CENT_IMT (no back-flux) and is what PD actually reads. ---
dxdt_GUT_IMT  = F_IMT * dose_rate_imt - KA_IMT * GUT_IMT;
dxdt_CENT_IMT = KA_IMT * GUT_IMT / V1_IMT - (CL_IMT / V1_IMT) * CENT_IMT;
dxdt_IC_IMT   = KIN_IMT * CENT_IMT - KOUT_IMT * IC_IMT;

// --- Dasatinib (DAS) PK: no depot -- continuous zero-order infusion
// approximation straight into CENT_DAS (edge case in the guide: preserved
// exactly as the original modeled it), plus the same bespoke intracellular
// biophase pattern as IMT/NIL. ---
dxdt_CENT_DAS = F_DAS * dose_rate_das / V1_DAS - (CL_DAS / V1_DAS) * CENT_DAS;
dxdt_IC_DAS   = KIC_DAS * CENT_DAS - KOUT_DAS * IC_DAS;

// --- Nilotinib (NIL) PK: Archetype 3 (depot + central, linear) plus the
// same bespoke intracellular biophase compartment as IMT. ---
dxdt_GUT_NIL  = F_NIL * dose_rate_nil - KA_NIL * GUT_NIL;
dxdt_CENT_NIL = KA_NIL * GUT_NIL / V1_NIL - (CL_NIL / V1_NIL) * CENT_NIL;
dxdt_IC_NIL   = KIC_NIL * CENT_NIL - KOUT_NIL * IC_NIL;

// --- Asciminib (ASC) PK: Archetype 3 (depot + central, linear), no
// peripheral, no intracellular compartment -- PD reads plasma directly. ---
dxdt_GUT_ASC  = F_ASC * dose_rate_asc - KA_ASC * GUT_ASC;
dxdt_CENT_ASC = KA_ASC * GUT_ASC / V1_ASC - (CL_ASC / V1_ASC) * CENT_ASC;

// ============================================================
// Exposed concentrations (C_<STEM>) and Hill effect interface (EFFECT_<STEM>)
// PD: Drug Effect Functions (Emax model, Hill equation)
// Effect = fraction of BCR-ABL-driven proliferation inhibited
// ============================================================

// Imatinib: PD reads the INTRACELLULAR concentration (genuinely distinct
// tissue site from plasma, per the guide's two-concentration carve-out) --
// the original's own E_imt read Cic_imt, never Cp_imt.
double C_IMT = (IC_IMT > 0) ? IC_IMT : 0;
double EFFECT_IMT = EMAX_IMT * pow(C_IMT, GAMMA_IMT) /
                    (pow(EC50_IMT, GAMMA_IMT) + pow(C_IMT, GAMMA_IMT));

// Dasatinib: PD reads the intracellular concentration, same as imatinib.
double C_DAS = (IC_DAS > 0) ? IC_DAS : 0;
double EFFECT_DAS = EMAX_DAS * pow(C_DAS, GAMMA_DAS) /
                    (pow(EC50_DAS, GAMMA_DAS) + pow(C_DAS, GAMMA_DAS));

// Nilotinib: PD reads the intracellular concentration, same as imatinib.
double C_NIL = (IC_NIL > 0) ? IC_NIL : 0;
double EFFECT_NIL = EMAX_NIL * pow(C_NIL, GAMMA_NIL) /
                    (pow(EC50_NIL, GAMMA_NIL) + pow(C_NIL, GAMMA_NIL));

// Asciminib: PD reads plasma directly (40 mg BID dose regimen; sensitive cells).
double C_ASC = (CENT_ASC > 0) ? CENT_ASC : 0;
double EFFECT_ASC = EMAX_ASC * pow(C_ASC, GAMMA_ASC) /
                    (pow(EC50_ASC, GAMMA_ASC) + pow(C_ASC, GAMMA_ASC));

// Asciminib effect on T315I resistant cells (200 mg BID -- higher IC50);
// same C_ASC concentration, independent Hill parameters for the resistant target.
double EFFECT_ASC_T315I = EMAX_ASC_T315I * pow(C_ASC, GAMMA_ASC_T315I) /
                    (pow(EC50_ASC_T315I, GAMMA_ASC_T315I) + pow(C_ASC, GAMMA_ASC_T315I));

// Combined TKI effect (additive, capped at 0.98) -- combined only at the
// point the disease equations actually use them, exactly as the original did.
double E_total_sens = fmin(0.98, EFFECT_IMT + EFFECT_DAS + EFFECT_NIL + EFFECT_ASC);
double E_total_res  = fmin(0.98, EFFECT_ASC_T315I);  // Only asciminib (high dose) hits T315I

// ============================================================
// Density-dependent competition (Lotka-Volterra type)
// ============================================================
double Ntotal = x0q + x0p + x1 + x2 + x3 + xs + xsp + xr + xrp +
                y0 + y1 + y2 + y3;
double suppress = fmax(0.0, 1.0 - Kcomp * Ntotal);

// ============================================================
// Normal Hematopoiesis ODEs
// ============================================================
// y0: HSC — self-renewal + input - differentiation - death
dxdt_y0 = ay0 * y0 + suppress * 0.0 - by0 * y0 - dy0 * y0;
dxdt_y1 = c1 * by0 * y0 - by1 * y1 - dy1 * y1;
dxdt_y2 = c2 * by1 * y1 - by2 * y2 - dy2 * y2;
dxdt_y3 = c3 * by2 * y2 - dy3 * y3;

// ============================================================
// Leukemic Hierarchy ODEs (total CML pool: xs+xr tracking separately)
// ============================================================

// LSC quiescent: activated by TKI pressure -> quiescence; killed by NK
double q_in  = q_dorm * x0p;   // cycling->quiescent (increases under TKI)
double q_out = q_act  * x0q;   // quiescent->cycling
double NK_kill_x0q = kNK_kill * NK_base * x0q / (x0q + 1e3);

dxdt_x0q = q_in - q_out - d0 * x0q - NK_kill_x0q;

// LSC cycling: self-renewal + activation - quiescence - differentiation - death - TKI kill - NK
double TKI_kill_x0p = E_total_sens * x0p;
double NK_kill_x0p  = kNK_kill * NK_base * x0p / (x0p + 1e3);

dxdt_x0p = a0 * x0p + q_out - q_in - b0 * x0p - d0 * x0p
           - TKI_kill_x0p - NK_kill_x0p + mu * a0 * xs;  // mutation from xs

// LPC1
double TKI_kill_x1 = E_total_sens * x1 * 0.6;  // progenitors less sensitive
dxdt_x1 = lc1 * b0 * x0p - b1 * x1 - d1 * x1 - TKI_kill_x1;

// LPC2
double TKI_kill_x2 = E_total_sens * x2 * 0.8;
dxdt_x2 = lc2 * b1 * x1 - b2 * x2 - d2 * x2 - TKI_kill_x2;

// Leukemic WBC/blasts
double TKI_kill_x3 = E_total_sens * x3 * 1.0;  // most sensitive (post-mitotic)
double NK_kill_x3  = kNK_kill * NK_base * x3 / (x3 + 1e8);
double CTL_kill_x3 = kCTL_kill * CTL_base * x3 / (x3 + 1e8);

dxdt_x3 = lc3 * b2 * x2 - d3 * x3 - TKI_kill_x3 - NK_kill_x3 - CTL_kill_x3;

// ============================================================
// Sensitive Clone ODEs
// ============================================================
double TKI_kill_xs = E_total_sens * xs;
dxdt_xs  = as0 * xs - bs0 * xs - ds0 * xs - TKI_kill_xs - mu * as0 * xs;
dxdt_xsp = lc1 * bs0 * xs + asp * xsp - dsp * xsp - E_total_sens * xsp * 0.7;

// ============================================================
// Resistant Clone (T315I) ODEs
// ============================================================
double TKI_kill_xr  = E_total_res * xr;   // only asciminib 200mg hits this
double TKI_kill_xrp = E_total_res * xrp * 0.7;

dxdt_xr  = ar0 * xr - br0 * xr - dr0 * xr - TKI_kill_xr;
dxdt_xrp = lc1 * br0 * xr + arp * xrp - drp * xrp - TKI_kill_xrp;

$TABLE
// BCR-ABL IS% calculation
// IS% = CML cells / (CML + normal cells) x 100
// Approximate: total CML WBC / (total CML WBC + normal neutrophils)

double CML_total  = x3 + xrp + xsp;
double Norm_total = y3;
// NOTE: renamed to *_calc (build-compat fix, see refactor notes) -- BCRPCT,
// LOG_IS, Resist_frac are also bare names in $CAPTURE below, and mrgsolve
// 2.0.1 auto-promotes every bare "double NAME = ..." in $TABLE to a
// reportable member, which then collides with the same name's own
// "capture NAME = ...;" line ("redefinition of capture ...", confirmed via
// qspserver /model_manifest on the untouched original). Purely a local
// variable rename; the reported BCRPCT/LOG_IS/Resist_frac values and every
// formula that reads them are numerically identical to the original.
double BCRPCT_calc = 100.0 * CML_total / fmax(CML_total + Norm_total, 1.0);

// Log10 BCR-ABL IS
double LOG_IS_calc = (BCRPCT_calc > 0.0001) ? log10(BCRPCT_calc) : -5.0;

// Molecular response milestones
double CHR_reached  = (BCRPCT_calc < 10.0)      ? 1.0 : 0.0;
double MMR_reached  = (BCRPCT_calc < 0.1)       ? 1.0 : 0.0;
double MR4_reached  = (BCRPCT_calc < 0.01)      ? 1.0 : 0.0;
double MR45_reached = (BCRPCT_calc < 0.0032)    ? 1.0 : 0.0;

// WBC count (10^9/L, assuming 5L blood volume)
double WBC_total_blood = (x3 + Norm_total) / 5e9;  // cells/L / (cells/count unit)

// PK summary (informational only, plasma sum across all 4 TKIs; not read by any PD equation)
double Cp_active = CENT_IMT + CENT_DAS + CENT_NIL + CENT_ASC;

// Resistant fraction
double Resist_frac_calc = (xr + xrp) / fmax(CML_total, 1.0);

capture BCRPCT     = BCRPCT_calc;
capture LOG_IS     = LOG_IS_calc;
capture CHR        = CHR_reached;
capture MMR        = MMR_reached;
capture MR4        = MR4_reached;
capture MR45       = MR45_reached;
capture WBC        = WBC_total_blood;
capture LSC_total  = x0q + x0p + xs + xr;
capture LSC_quies  = x0q / fmax(x0q + x0p, 1.0);  // quiescent fraction
capture Resist_frac = Resist_frac_calc;

$CAPTURE BCRPCT LOG_IS CHR MMR MR4 MR45 WBC LSC_total LSC_quies
         Resist_frac C_IMT C_DAS C_NIL C_ASC
         EFFECT_IMT EFFECT_DAS EFFECT_NIL EFFECT_ASC EFFECT_ASC_T315I
'

# ============================================================
# Compile model
# ============================================================
mod <- mcode("cml_qsp_refactored", cml_code)
cat("Model compiled successfully. Compartments:", length(mod@cmts), "\n")
cat("Parameters:", length(param(mod)), "\n")

# ============================================================
# SIMULATION SCENARIOS
# ============================================================

# Common simulation time: 10 years = 87,600 hours
t_end_yr  <- 10        # years
t_end_hr  <- t_end_yr * 365.25 * 24  # hours
dt        <- 24        # output every 24h (daily)

times <- seq(0, t_end_hr, by = dt)
# Convert to months for display
to_months <- function(t_hr) t_hr / (365.25 * 24 / 12)

#-----------------------------------------------------------------
# SCENARIO 1: Untreated CML progression (CP -> potential AP/BC)
#-----------------------------------------------------------------
cat("\n--- Scenario 1: Untreated CML ---\n")

scen1 <- mod %>%
  param(dose_imt = 0, dose_das = 0, dose_nil = 0, dose_asc = 0) %>%
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Untreated", time_months = to_months(time))

cat("Final BCR-ABL IS% (untreated, 10yr):", tail(scen1$BCRPCT, 1), "%\n")

#-----------------------------------------------------------------
# SCENARIO 2: Imatinib 400 mg/day (IRIS trial — standard of care 2001)
#-----------------------------------------------------------------
cat("\n--- Scenario 2: Imatinib 400mg/day (IRIS) ---\n")

scen2 <- mod %>%
  param(dose_imt = 400, dose_das = 0, dose_nil = 0, dose_asc = 0) %>%
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Imatinib 400mg/day", time_months = to_months(time))

# Check IRIS-calibrated milestones:
# CHR @ 3mo: ~95%; CCyR @ 12mo: ~73%; MMR @ 18mo: ~39%
mmr_3mo  <- scen2$MMR[scen2$time_months >= 3][1]
mmr_12mo <- scen2$MMR[scen2$time_months >= 12][1]
mmr_18mo <- scen2$MMR[scen2$time_months >= 18][1]
cat("MMR achieved @ 3mo:", mmr_3mo, "| 12mo:", mmr_12mo, "| 18mo:", mmr_18mo, "\n")
cat("BCR-ABL IS% @ 12mo:", round(scen2$BCRPCT[scen2$time_months >= 12][1], 3), "%\n")

#-----------------------------------------------------------------
# SCENARIO 3: Dasatinib 100 mg/day (DASISION trial)
# Faster and deeper responses vs imatinib
#-----------------------------------------------------------------
cat("\n--- Scenario 3: Dasatinib 100mg/day (DASISION) ---\n")

scen3 <- mod %>%
  param(dose_imt = 0, dose_das = 100, dose_nil = 0, dose_asc = 0) %>%
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Dasatinib 100mg/day", time_months = to_months(time))

mmr_12mo_das <- scen3$MMR[scen3$time_months >= 12][1]
cat("MMR @ 12mo (Dasatinib):", mmr_12mo_das, "\n")
cat("BCR-ABL IS% @ 12mo:", round(scen3$BCRPCT[scen3$time_months >= 12][1], 3), "%\n")

#-----------------------------------------------------------------
# SCENARIO 4: Nilotinib 300mg BID (ENESTnd trial)
# Superior MMR rates vs imatinib
#-----------------------------------------------------------------
cat("\n--- Scenario 4: Nilotinib 300mg BID (ENESTnd) ---\n")

scen4 <- mod %>%
  param(dose_imt = 0, dose_das = 0, dose_nil = 600, dose_asc = 0) %>%
  # 300mg BID = 600mg/day total
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Nilotinib 300mg BID", time_months = to_months(time))

mmr_12mo_nil <- scen4$MMR[scen4$time_months >= 12][1]
mr4_12mo_nil <- scen4$MR4[scen4$time_months >= 12][1]
cat("MMR @ 12mo (Nilotinib):", mmr_12mo_nil, "\n")
cat("MR4 @ 12mo (Nilotinib):", mr4_12mo_nil, "\n")
cat("BCR-ABL IS% @ 12mo:", round(scen4$BCRPCT[scen4$time_months >= 12][1], 3), "%\n")

#-----------------------------------------------------------------
# SCENARIO 5: Asciminib 40mg BID (ASCEMBL trial)
# STAMP mechanism, active against most mutations
#-----------------------------------------------------------------
cat("\n--- Scenario 5: Asciminib 40mg BID (ASCEMBL) ---\n")

scen5 <- mod %>%
  param(dose_imt = 0, dose_das = 0, dose_nil = 0, dose_asc = 80) %>%
  # 40mg BID = 80mg/day
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Asciminib 40mg BID", time_months = to_months(time))

mmr_24mo_asc <- scen5$MMR[scen5$time_months >= 24][1]
cat("MMR @ 24mo (Asciminib):", mmr_24mo_asc, "\n")

#-----------------------------------------------------------------
# SCENARIO 6: Imatinib with T315I resistance emergence
# Initial response, then resistance clone outgrowth
#-----------------------------------------------------------------
cat("\n--- Scenario 6: Imatinib -> T315I Resistance Emergence ---\n")

scen6 <- mod %>%
  param(dose_imt = 400, dose_das = 0, dose_nil = 0, dose_asc = 0) %>%
  # Higher mutation rate for resistance emergence
  param(mu = 5e-7) %>%
  mrgsim(end = t_end_hr, delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "Imatinib + T315I resistance", time_months = to_months(time))

# When does BCR-ABL IS% start rising (resistance detection)?
first_rise <- which(diff(scen6$BCRPCT) > 0.001 & scen6$BCRPCT[-1] > 1.0)
if (length(first_rise) > 0) {
  cat("Resistance detected (IS% rising) at:", round(scen6$time_months[first_rise[1]], 1), "months\n")
}
cat("Resistant fraction @ 5yr:", round(tail(scen6$Resist_frac, 1) * 100, 2), "%\n")

#-----------------------------------------------------------------
# SCENARIO 7: TFR attempt after deep molecular response
# Patient achieves MR4.5 on nilotinib, then stops TKI
#-----------------------------------------------------------------
cat("\n--- Scenario 7: TFR Attempt after Sustained DMR ---\n")

# Phase 1: nilotinib until MR4.5 (simulate 4 years)
t_tfr_start  <- 4 * 365.25 * 24  # 4 years in hours
t_tfr_end    <- t_end_hr

# First, get state at TFR initiation after 4yr nilotinib
pre_TFR <- mod %>%
  param(dose_imt = 0, dose_das = 0, dose_nil = 600, dose_asc = 0) %>%
  mrgsim(end = t_tfr_start, delta = dt) %>%
  as.data.frame()

cat("BCR-ABL IS% at TFR start (4yr nilotinib):",
    round(tail(pre_TFR$BCRPCT, 1), 4), "%\n")
cat("MR4.5 achieved at TFR:", tail(pre_TFR$MR45, 1), "\n")

# Phase 2: TKI stopped — model natural clearance
# Extract end-state for continuation (simplified: reset PK, keep cell states)
end_state <- tail(pre_TFR, 1)
init_tfr <- c(
  y0   = end_state$y0,
  y1   = end_state$y1,
  y2   = end_state$y2,
  y3   = end_state$y3,
  x0q  = end_state$x0q,
  x0p  = end_state$x0p,
  x1   = end_state$x1,
  x2   = end_state$x2,
  x3   = end_state$x3,
  xs   = end_state$xs,
  xsp  = end_state$xsp,
  xr   = end_state$xr,
  xrp  = end_state$xrp,
  GUT_IMT = 0, CENT_IMT = 0, IC_IMT = 0,
  CENT_DAS = 0, IC_DAS = 0,
  GUT_NIL = 0, CENT_NIL = 0, IC_NIL = 0,
  GUT_ASC = 0, CENT_ASC = 0
)

# Simulate TFR phase (off TKI)
scen7_tfr <- mod %>%
  param(dose_imt = 0, dose_das = 0, dose_nil = 0, dose_asc = 0) %>%
  init(init_tfr) %>%
  mrgsim(end = (6 * 365.25 * 24), delta = dt) %>%
  as.data.frame() %>%
  mutate(scenario = "TFR (off nilotinib)",
         time_months = to_months(time) + 48)  # offset by 4yr

# Combine pre- and post-TFR
pre_TFR2 <- pre_TFR %>%
  mutate(scenario = "Nilotinib pre-TFR", time_months = to_months(time))
scen7 <- bind_rows(pre_TFR2, scen7_tfr)

# TFR outcome: molecular relapse if IS% > 0.1% within 6 months
tfr_6mo <- scen7_tfr$BCRPCT[scen7_tfr$time_months >= 48 + 6][1]
if (!is.na(tfr_6mo) && tfr_6mo > 0.1) {
  cat("TFR outcome: MOLECULAR RELAPSE @ 6mo (IS% =", round(tfr_6mo, 4), "%)\n")
} else {
  cat("TFR outcome: IN REMISSION @ 6mo (IS% =", round(tfr_6mo, 4), "%)\n")
}

# ============================================================
# COMBINED PLOT: All TKI scenarios — BCR-ABL IS%
# ============================================================

all_scenarios <- bind_rows(scen1, scen2, scen3, scen4, scen5, scen6) %>%
  filter(time_months <= 60)  # 5 years

p1 <- ggplot(all_scenarios, aes(x = time_months, y = BCRPCT,
                                color = scenario, linetype = scenario)) +
  geom_line(size = 1.2) +
  scale_y_log10(
    breaks = c(100, 10, 1, 0.1, 0.01, 0.001),
    labels = c("100%", "10%", "1%", "0.1%\n(MMR)", "0.01%\n(MR4)", "0.001%\n(MR4.5)"),
    limits = c(0.001, 100)
  ) +
  geom_hline(yintercept = 0.1,   linetype = "dashed", color = "blue",   alpha = 0.7) +
  geom_hline(yintercept = 0.01,  linetype = "dashed", color = "purple", alpha = 0.7) +
  geom_hline(yintercept = 0.0032, linetype = "dashed", color = "darkgreen", alpha = 0.7) +
  geom_vline(xintercept = c(3, 6, 12, 18, 36), linetype = "dotted", alpha = 0.4) +
  annotate("text", x = 18, y = 0.12,  label = "MMR (0.1%)",  color = "blue",   size = 3) +
  annotate("text", x = 18, y = 0.012, label = "MR4 (0.01%)", color = "purple", size = 3) +
  annotate("text", x = 18, y = 0.0035, label = "MR4.5",      color = "darkgreen", size = 3) +
  scale_color_manual(values = c(
    "Untreated"                  = "#E41A1C",
    "Imatinib 400mg/day"         = "#377EB8",
    "Dasatinib 100mg/day"        = "#4DAF4A",
    "Nilotinib 300mg BID"        = "#984EA3",
    "Asciminib 40mg BID"         = "#FF7F00",
    "Imatinib + T315I resistance" = "#A65628"
  )) +
  labs(
    title = "CML QSP Model — BCR-ABL IS% Over Time by TKI Therapy",
    subtitle = "Calibrated to IRIS (imatinib), DASISION (dasatinib), ENESTnd (nilotinib), ASCEMBL (asciminib)",
    x = "Time (months)",
    y = "BCR-ABL IS% (International Scale)",
    color = "Treatment Scenario",
    linetype = "Treatment Scenario",
    caption = "Dashed lines: ELN 2020 response milestones | Dotted verticals: key assessment timepoints"
  ) +
  theme_bw(base_size = 12) +
  theme(legend.position = "right")

# ============================================================
# PLOT 2: Cell population kinetics (Imatinib scenario)
# ============================================================

cells_imt <- scen2 %>%
  filter(time_months <= 60) %>%
  select(time_months, x0q, x0p, x1, x2, x3, y3, xs, xr) %>%
  pivot_longer(cols = -time_months, names_to = "population", values_to = "count") %>%
  mutate(population = case_when(
    population == "x0q" ~ "LSC Quiescent (CML)",
    population == "x0p" ~ "LSC Cycling (CML)",
    population == "x1"  ~ "LPC1 (CML)",
    population == "x2"  ~ "LPC2 (CML)",
    population == "x3"  ~ "Leukemic WBC",
    population == "y3"  ~ "Normal WBC",
    population == "xs"  ~ "Sensitive LSC Clone",
    population == "xr"  ~ "Resistant LSC (T315I)"
  ))

p2 <- ggplot(cells_imt, aes(x = time_months, y = count + 1,
                             color = population)) +
  geom_line(size = 1.0) +
  scale_y_log10() +
  labs(
    title = "CML Cell Population Kinetics — Imatinib 400mg/day",
    x = "Time (months)", y = "Cell Count (log10)",
    color = "Cell Population"
  ) +
  theme_bw(base_size = 12) +
  theme(legend.position = "right")

# ============================================================
# PLOT 3: PK profiles — Imatinib, Dasatinib, Nilotinib (plasma + intracellular)
# ============================================================

pk_data <- bind_rows(
  scen2 %>% filter(time_months <= 1) %>%
    select(time_months, CENT_IMT, IC_IMT) %>%
    pivot_longer(-time_months, names_to = "compartment", values_to = "conc") %>%
    mutate(drug = "Imatinib"),
  scen3 %>% filter(time_months <= 1) %>%
    select(time_months, CENT_DAS, IC_DAS) %>%
    pivot_longer(-time_months, names_to = "compartment", values_to = "conc") %>%
    mutate(drug = "Dasatinib"),
  scen4 %>% filter(time_months <= 1) %>%
    select(time_months, CENT_NIL, IC_NIL) %>%
    pivot_longer(-time_months, names_to = "compartment", values_to = "conc") %>%
    mutate(drug = "Nilotinib")
)

p3 <- ggplot(pk_data, aes(x = time_months * 30 * 24, y = conc,
                          color = compartment, linetype = drug)) +
  geom_line(size = 1.0) +
  scale_y_log10() +
  labs(
    title = "TKI Pharmacokinetic Profiles (First Month)",
    x = "Time (hours)", y = "Concentration (uM, log scale)",
    color = "Compartment", linetype = "Drug"
  ) +
  theme_bw(base_size = 12)

# Print summary
cat("\n=== SIMULATION COMPLETE ===\n")
cat("Scenarios simulated:\n")
cat("  1. Untreated CML (progression model)\n")
cat("  2. Imatinib 400mg/day (IRIS calibration)\n")
cat("  3. Dasatinib 100mg/day (DASISION calibration)\n")
cat("  4. Nilotinib 300mg BID (ENESTnd calibration)\n")
cat("  5. Asciminib 40mg BID (ASCEMBL calibration)\n")
cat("  6. Imatinib + T315I resistance emergence\n")
cat("  7. TFR attempt after sustained DMR on nilotinib\n")
cat("\nPlots created: p1 (BCR-ABL IS%), p2 (cell kinetics), p3 (PK)\n")
cat("Use print(p1), print(p2), print(p3) to display\n")

# Return models and results invisibly
invisible(list(
  model    = mod,
  scenarios = list(
    untreated    = scen1,
    imatinib     = scen2,
    dasatinib    = scen3,
    nilotinib    = scen4,
    asciminib    = scen5,
    resistance   = scen6,
    tfr          = scen7
  ),
  plots = list(p1 = p1, p2 = p2, p3 = p3)
))
