# =============================================================================
#  PROLACTINOMA QSP — Shiny dashboard
#
#  11 tabs built directly on the model spec in prl_mrgsolve_model.R, which is
#  read out of that file at start-up so the app and the model cannot drift
#  apart.
#
#  The organising ideas the dashboard is built to make visible:
#    * ONE D2 occupancy equation drives everything, so the same slider set
#      produces dopamine-agonist therapy, antipsychotic-induced
#      hyperprolactinaemia, the aripiprazole add-on paradox and stalk-effect
#      disconnection. Tab 2 shows the competition explicitly.
#    * The MEASUREMENT LAYER is separate from the biology. Tab 4 plots
#      bioactive, immunoreactive, reported and post-dilution prolactin on the
#      same axes, so the hook effect and macroprolactinaemia are visible as
#      gaps between curves rather than as footnotes.
#    * Efficacy runs off the PITUITARY BIOPHASE and valvular risk off PLASMA,
#      so tab 9 can show them diverging.
#    * Presenting values are GENERATED by a silent natural-history phase, not
#      typed in: every plot marks the day of presentation.
#
#  Run with:  shiny::runApp("prl_shiny_app.R")
# =============================================================================

library(shiny)
library(mrgsolve)
library(ggplot2)
library(dplyr)
library(tidyr)
library(DT)

MODEL_FILE <- "prl_mrgsolve_model.R"
stopifnot(file.exists(MODEL_FILE))
src  <- readLines(MODEL_FILE)
i0   <- grep("^prl_code <- '", src)[1]
i1   <- grep("^'$", src)
i1   <- i1[i1 > i0][1]
spec <- paste(src[(i0 + 1):(i1 - 1)], collapse = "\n")
mod  <- mcode("prl_shiny", spec)

PRESIM <- 730   # silent natural-history phase, as in the model file

theme_prl <- function() {
  theme_minimal(base_size = 12) +
    theme(panel.grid.minor = element_blank(),
          plot.title    = element_text(face = "bold", size = 13),
          plot.subtitle = element_text(colour = "grey35", size = 10),
          legend.position = "bottom", legend.title = element_blank(),
          strip.text = element_text(face = "bold"))
}
PAL <- c("#1565C0", "#C62828", "#2E7D32", "#E65100", "#6A1B9A",
         "#00838F", "#AD1457", "#37474F", "#827717", "#4527A0")

pres_line <- function()
  list(geom_vline(xintercept = PRESIM/365, linetype = "22", colour = "grey45"),
       annotate("text", x = PRESIM/365, y = Inf, label = " presentation",
                hjust = 0, vjust = 1.4, size = 3, colour = "grey35"))

# ---------------------------------------------------------------------------
#  Build parameter list and events from the UI state
# ---------------------------------------------------------------------------
build_par <- function(i) {
  p <- list(
    NS0     = i$ns0,
    NR0     = i$nr0,
    D2RS0   = i$d2rs,
    D2RR0   = 0.05,
    FDRIVE  = i$fdrive,
    FGEN    = i$fgen,
    SEX     = ifelse(i$sex == "male", 1, 0),
    STALKP  = i$stalkp,
    APABSET = i$apab,
    PRIMHYP = i$primhyp,
    FCLR    = i$fclr,
    MGMT0   = i$mgmt,
    FTREPL  = i$ftrepl,
    KI_5HT2B= i$ki5ht,
    ICDSUSC = i$icdsusc
  )
  if (i$preg) p$PREGON <- PRESIM + i$pregday
  if (i$surg) { p$SURGD <- PRESIM + i$surgday
                p$SURGRES <- i$surgres; p$SURGHYP <- i$surghyp }
  if (i$ap_drug == "aripiprazole") {
    p$EFF_AP <- 0.25; p$KI_AP <- 0.34; p$FU_AP <- 0.01
    p$CL_AP  <- 210;  p$V_AP  <- 1400
  } else if (i$ap_drug == "quetiapine (sparing)") {
    p$EFF_AP <- 0.00; p$KI_AP <- 45.0
  }
  p
}

build_ev <- function(i, end) {
  ee <- list()
  wk <- max(1, ceiling((end - PRESIM - i$startday)/7))
  if (i$da == "cabergoline" && i$cabdose > 0) {
    ii <- if (i$cabsplit) 3.5 else 7
    amt <- if (i$cabsplit) i$cabdose/2 else i$cabdose
    nd  <- max(1, ceiling((end - PRESIM - i$startday)/ii))
    stopd <- if (i$stopyr > 0) PRESIM + i$startday + i$stopyr*365 else Inf
    nd  <- min(nd, max(1, ceiling((stopd - PRESIM - i$startday)/ii)))
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = amt,
                             cmt = "CAB_G", ii = ii, addl = nd - 1)
  }
  if (i$da == "bromocriptine" && i$brcdose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = i$brcdose/3,
                             cmt = "BRC_G", ii = 1/3,
                             addl = 3*max(1, end - PRESIM - i$startday) - 1)
  if (i$da == "quinagolide" && i$quidose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = i$quidose/1000,
                             cmt = "QUI_G", ii = 1,
                             addl = max(1, end - PRESIM - i$startday) - 1)
  if (i$ap_drug != "none" && i$apdose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM, amt = i$apdose, cmt = "AP_G",
                             ii = 1, addl = max(1, end - PRESIM) - 1)
  if (i$tmz)
    for (k in 0:(i$tmzcyc - 1))
      ee[[length(ee)+1]] <- ev(time = PRESIM + i$tmzstart + 28*k,
                               amt = 180*1.8, cmt = "TMZ_C", ii = 1, addl = 4)
  if (!length(ee)) return(NULL)
  ds <- lapply(ee, as.data.frame)
  cn <- unique(unlist(lapply(ds, names)))
  ds <- lapply(ds, function(d) { for (k in setdiff(cn, names(d))) d[[k]] <- 0; d[cn] })
  as.ev(do.call(rbind, ds))
}

simulate <- function(i) {
  end <- PRESIM + i$horizon*365
  e   <- build_ev(i, end)
  m   <- param(mod, build_par(i))
  out <- if (is.null(e)) mrgsim(m, end = end, delta = 1, maxsteps = 500000, hmax = 0.5)
         else mrgsim(m, events = e, end = end, delta = 1, maxsteps = 500000, hmax = 0.5)
  d <- as.data.frame(out)
  d$year <- d$time/365
  d
}

atd  <- function(d, v, t) d[[v]][which.min(abs(d$time - t))]
prs  <- function(d, v) atd(d, v, PRESIM)

# ---------------------------------------------------------------------------
#  UI
# ---------------------------------------------------------------------------
ui <- fluidPage(
  titlePanel("Prolactinoma — QSP dashboard"),
  tags$p(style = "color:#555;margin-top:-8px",
         HTML("A single D2 occupancy equation generates dopamine-agonist therapy · antipsychotic-induced hyperprolactinaemia ·
               the aripiprazole paradox · and stalk compression (stalk effect) alike.
               The <b>measurement layer</b> is separate from the biology, so the hook effect and
               macroprolactin can be seen as gaps between the curves.")),
  sidebarLayout(
    sidebarPanel(
      width = 3,
      selectInput("preset", "Preset patient",
                  c("microadenoma (F)", "macroadenoma (F)", "giant, male",
                    "partial resistance", "true resistance (AIP-like)",
                    "stalk effect (NFPA)", "macroprolactinaemia",
                    "antipsychotic-induced", "healthy control")),
      hr(),
      h5("Tumour"),
      sliderInput("ns0", "D2R-sensitive tumour volume (mL)", 0.001, 25, 0.35, 0.01),
      sliderInput("nr0", "D2R-low resistant clone (mL)", 0, 2, 0, 0.01),
      sliderInput("d2rs", "D2 receptor density (normal = 1)", 0.02, 1.0, 0.50, 0.01),
      sliderInput("fdrive", "Endogenous transcriptional drive (FDRIVE)", 0.5, 2.0, 1.0, 0.05),
      sliderInput("fgen", "Proliferative drive (FGEN, AIP/SF3B1 > 1)", 0.7, 2.0, 1.0, 0.05),
      radioButtons("sex", "Sex", c("female", "male"), inline = TRUE),
      hr(),
      h5("Therapy"),
      selectInput("da", "Dopamine agonist",
                  c("none", "cabergoline", "bromocriptine", "quinagolide"),
                  selected = "cabergoline"),
      conditionalPanel("input.da == 'cabergoline'",
        sliderInput("cabdose", "Cabergoline (mg/week)", 0, 7, 1, 0.25),
        checkboxInput("cabsplit", "Split into two doses per week", FALSE)),
      conditionalPanel("input.da == 'bromocriptine'",
        sliderInput("brcdose", "Bromocriptine (mg/day, in 3 divided doses)", 0, 30, 7.5, 0.5)),
      conditionalPanel("input.da == 'quinagolide'",
        sliderInput("quidose", "Quinagolide (ug/day)", 0, 600, 300, 25)),
      sliderInput("startday", "Delay to treatment start (days after diagnosis)", 0, 1825, 0, 30),
      sliderInput("stopyr", "Treatment withdrawal (years, 0 = no withdrawal)", 0, 15, 0, 0.5),
      hr(),
      h5("Other interventions / settings"),
      selectInput("ap_drug", "Antipsychotic",
                  c("none", "risperidone-like", "aripiprazole",
                    "quetiapine (sparing)")),
      conditionalPanel("input.ap_drug != 'none'",
        sliderInput("apdose", "Antipsychotic dose (mg/day)", 0, 30, 6, 0.5)),
      checkboxInput("preg", "Pregnancy", FALSE),
      conditionalPanel("input.preg",
        sliderInput("pregday", "Pregnancy onset (days after treatment start)", 0, 1460, 400, 30)),
      checkboxInput("surg", "Transsphenoidal surgery (TSS)", FALSE),
      conditionalPanel("input.surg",
        sliderInput("surgday", "Time of surgery (days)", 0, 1460, 30, 10),
        sliderInput("surgres", "Residual fraction", 0, 1, 0.25, 0.05),
        sliderInput("surghyp", "Surgical hypopituitarism", 0, 0.6, 0.12, 0.02)),
      checkboxInput("tmz", "Temozolomide", FALSE),
      conditionalPanel("input.tmz",
        sliderInput("tmzstart", "TMZ start (days)", 0, 730, 30, 10),
        sliderInput("tmzcyc", "Number of cycles", 1, 12, 6, 1),
        sliderInput("mgmt", "MGMT activity (low = responsive)", 0.01, 1, 0.20, 0.01)),
      hr(),
      h5("Model axes / susceptibility"),
      sliderInput("stalkp", "Pituitary stalk patency", 0.001, 1, 1, 0.005),
      sliderInput("apab", "Anti-prolactin autoantibody (macroprolactin)", 0, 5, 0, 0.1),
      sliderInput("primhyp", "Primary hypothyroidism severity", 0, 1, 0, 0.05),
      sliderInput("fclr", "Prolactin clearance multiplier (CKD < 1)", 0.2, 1.2, 1, 0.05),
      sliderInput("ftrepl", "Sex-steroid replacement (vs normal)", 0, 1, 0, 0.05),
      sliderInput("ki5ht", "5-HT2B Ki (nM) — selectivity axis", 1, 1200, 12, 1),
      sliderInput("icdsusc", "Impulse-control disorder susceptibility", 0.3, 2, 1, 0.1),
      sliderInput("horizon", "Simulation horizon (years after diagnosis)", 1, 20, 5, 1)
    ),
    mainPanel(
      width = 9,
      tabsetPanel(
        id = "tabs",
        tabPanel("① Patient profile",
                 h4("Phenotype at diagnosis (generated, not typed in)"),
                 tags$p(style = "color:#666",
                        "Every presenting value is read out after simulating two years of
                         asymptomatic natural history (PRESIM). Prolactin, the gonadal axis, bone density and visual fields are outputs, not inputs."),
                 DTOutput("tbl_profile"),
                 hr(), plotOutput("p_profile", height = "420px")),
        tabPanel("② D2 occupancy equation",
                 h4("One competitive occupancy equation produces every direction"),
                 verbatimTextOutput("txt_occ"),
                 plotOutput("p_occ", height = "300px"),
                 hr(), plotOutput("p_branch", height = "300px")),
        tabPanel("③ Drug PK",
                 h4("Plasma vs pituitary biophase — why once-weekly dosing works"),
                 plotOutput("p_pk", height = "330px"),
                 hr(), verbatimTextOutput("txt_pk")),
        tabPanel("④ Prolactin & measurement layer",
                 h4("Biological prolactin and reported prolactin are not the same number"),
                 plotOutput("p_prl", height = "340px"),
                 hr(), h5("This patient's two-site sandwich immunoassay curve"),
                 plotOutput("p_hook", height = "300px")),
        tabPanel("⑤ Tumour",
                 h4("Cell volume (fast and reversible) vs cell number (slow and banked)"),
                 plotOutput("p_tum", height = "340px"),
                 hr(), plotOutput("p_clone", height = "260px")),
        tabPanel("⑥ Mass effect · visual fields",
                 h4("A geometry problem — reversible conduction block and irreversible axonal loss"),
                 plotOutput("p_vf", height = "330px"),
                 hr(), plotOutput("p_hypo", height = "280px")),
        tabPanel("⑦ Gonadal axis · reproduction",
                 h4("KNDy → GnRH pulsatility → LH/FSH → sex steroids"),
                 plotOutput("p_hpg", height = "340px"),
                 hr(), plotOutput("p_repro", height = "280px")),
        tabPanel("⑧ Bone · metabolism",
                 h4("What recovers and what is banked"),
                 plotOutput("p_bone", height = "330px"),
                 hr(), plotOutput("p_met", height = "260px")),
        tabPanel("⑨ Safety (selectivity)",
                 h4("An adverse effect is a different receptor read at the same concentration"),
                 plotOutput("p_safe", height = "330px"),
                 hr(), h5("5-HT2B/D2 selectivity sweep: efficacy flat, valvular risk collapses"),
                 plotOutput("p_sweep", height = "300px")),
        tabPanel("⑩ Scenario comparison",
                 h4("Predefined comparisons (all simulated live)"),
                 selectInput("cmp", "Comparison", width = "420px",
                   c("cabergoline vs bromocriptine vs quinagolide",
                     "cabergoline dose 0.25 / 0.5 / 1 / 2 / 3.5 mg/week",
                     "partial resistance vs true resistance (± dose escalation)",
                     "treatment delay 0 / 1 / 2 / 4 years",
                     "relapse after withdrawal by residual volume")),
                 plotOutput("p_cmp", height = "420px"),
                 hr(), DTOutput("tbl_cmp")),
        tabPanel("⑪ Withdrawal · pregnancy",
                 h4("When the drug is stopped, what comes back first"),
                 plotOutput("p_wd", height = "340px"),
                 hr(), verbatimTextOutput("txt_wd"))
      )
    )
  )
)

# ---------------------------------------------------------------------------
#  Server
# ---------------------------------------------------------------------------
server <- function(input, output, session) {

  observeEvent(input$preset, {
    p <- switch(input$preset,
      "microadenoma (F)"          = list(ns0=0.35, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "macroadenoma (F)"          = list(ns0=3.20, d2rs=0.35, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "giant, male"               = list(ns0=18.0, d2rs=0.25, sex="male", fgen=1.0,
                                         fdrive=1.3, stalkp=1, apab=0, ap_drug="none"),
      "partial resistance"        = list(ns0=3.20, d2rs=0.15, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "true resistance (AIP-like)"= list(ns0=3.20, d2rs=0.04, sex="male", fgen=1.3,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "stalk effect (NFPA)"       = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=0.05, apab=0, ap_drug="none"),
      "macroprolactinaemia"       = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=2.2, ap_drug="none"),
      "antipsychotic-induced"     = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0,
                                         ap_drug="risperidone-like"),
      "healthy control"           = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"))
    updateSliderInput(session, "ns0", value = p$ns0)
    updateSliderInput(session, "d2rs", value = p$d2rs)
    updateSliderInput(session, "fgen", value = p$fgen)
    updateSliderInput(session, "fdrive", value = p$fdrive)
    updateSliderInput(session, "stalkp", value = p$stalkp)
    updateSliderInput(session, "apab", value = p$apab)
    updateRadioButtons(session, "sex", selected = p$sex)
    updateSelectInput(session, "ap_drug", selected = p$ap_drug)
  })

  sim <- reactive({ simulate(reactiveValuesToList(input)) })

  # ---- tab 1 --------------------------------------------------------------
  output$tbl_profile <- renderDT({
    d <- sim()
    tt <- c(PRESIM, PRESIM + 365, max(d$time))
    lab <- c("At diagnosis", "After 1 year", sprintf("After %.0f years", (max(d$time)-PRESIM)/365))
    vars <- c(PRLB="Biological prolactin (ng/mL)", PRLMEAS_="Reported prolactin (ng/mL)",
              PEGREC="PEG recovery (%)", TVOL_="Tumour volume (mL)",
              CELLN="Tumour cell mass (mL)", VCELL="Mean cell volume",
              COMPR_="Optic chiasm compression (cm)", VFMD="Visual field MD (dB)",
              OVF="Ovulatory capacity", TST="Testosterone (ng/dL)", E2G="Oestradiol (pg/mL)",
              TSCORE="Lumbar T-score", PFRACT="Vertebral fracture probability (%)",
              BW="Body weight (kg)", IR="HOMA-IR", CORT="Cortisol reserve",
              SIGDRIVE="D2 signalling drive", PTR="Moderate-or-worse TR probability (%)",
              PICD="Impulse-control disorder probability (%)")
    m <- sapply(tt, function(t) sapply(names(vars), function(v) atd(d, v, t)))
    df <- data.frame(metric = unname(vars), round(m, 3), check.names = FALSE)
    names(df) <- c("Metric", lab)
    datatable(df, rownames = FALSE, options = list(pageLength = 20, dom = "t"))
  })

  output$p_profile <- renderPlot({
    d <- sim()
    dd <- d %>% select(year, PRLB, PRLMEAS_, TVOL_, VFMD, TSCORE, OVF) %>%
      pivot_longer(-year)
    lv <- c(PRLB="Biological PRL", PRLMEAS_="Reported PRL", TVOL_="Tumour volume mL",
            VFMD="Visual field MD dB", TSCORE="Lumbar T-score", OVF="Ovulatory capacity")
    dd$name <- factor(lv[dd$name], levels = lv)
    ggplot(dd, aes(year, value)) +
      geom_line(colour = PAL[1], linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y", ncol = 3) + pres_line() +
      labs(x = "Years (0 = tumour seeding)", y = NULL,
           title = "The whole course of the generated phenotype",
           subtitle = "Dashed line = the point at which the patient presents and treatment begins") +
      theme_prl()
  })

  # ---- tab 2 --------------------------------------------------------------
  output$txt_occ <- renderText({
    d <- sim(); r <- d[which.min(abs(d$time - max(d$time))), ]
    p <- build_par(reactiveValuesToList(input))
    paste0(
      "SIGDRIVE = SUM_i e_i (C_i/K_i) / (1 + SUM_j C_j/K_j)   x   D2R density\n\n",
      sprintf("  Healthy dopamine-only SIGDRIVE                        : %.4f\n", 0.0909),
      sprintf("  Current SIGDRIVE (after all ligands compete)          : %.4f  (%.2fx)\n",
              r$SIGDRIVE, r$SIGDRIVE/0.0909),
      sprintf("  Tumour-clone active receptor signal SIGS              : %.4f\n", r$SIGS),
      sprintf("  Residual transcription (branch 2, lower = suppressed) : %.4f\n", r$RTRS),
      sprintf("  Residual secretory-granule release (branch 1)         : %.4f\n", r$REXS),
      "\n  The four directions the same equation produces:\n",
      "    Agonist           -> SIGDRIVE rises -> prolactin falls\n",
      "    D2 antagonist     -> an e=0 ligand displaces dopamine -> prolactin rises\n",
      "    Aripiprazole      -> e=0.25, high affinity -> alone it exceeds physiological tone\n",
      "    Stalk compression -> the delivery (DAP) term is cut -> only normal cells are disinhibited (a ceiling exists)\n")
  })

  output$p_occ <- renderPlot({
    d <- sim()
    dd <- d %>% select(year, SIGDRIVE, SIGS, DAP) %>% pivot_longer(-year)
    lv <- c(SIGDRIVE="SIGDRIVE (total D2 drive)", SIGS="SIGS (tumour active receptors)",
            DAP="Portal dopamine (nM)")
    dd$name <- factor(lv[dd$name], levels = lv)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Occupancy and delivery",
           subtitle = "Portal dopamine rises through the short loop — the deliverer is normal, the receptor is the problem") +
      theme_prl()
  })

  output$p_branch <- renderPlot({
    d <- sim(); r0 <- d[which.min(abs(d$time - PRESIM)), ]
    dd <- d %>% filter(time >= PRESIM) %>%
      transmute(day = time - PRESIM,
                `branch 1 exocytosis` = REXS/r0$REXS,
                `branch 2 transcription` = RTRS/r0$RTRS,
                `branch 3 cell volume` = VCELL/r0$VCELL,
                `branch 4 cell number` = CELLN/r0$CELLN,
                `prolactin` = PRLB/r0$PRLB) %>%
      pivot_longer(-day)
    ggplot(dd, aes(day + 1, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_x_log10() + scale_colour_manual(values = PAL) +
      labs(x = "Days after treatment start + 1 (log)", y = "Ratio to the value at diagnosis",
           title = "One receptor, four clocks",
           subtitle = "Secretion and transcription settle within days, cell volume takes two months, cell number takes years") +
      theme_prl()
  })

  # ---- tab 3 --------------------------------------------------------------
  output$p_pk <- renderPlot({
    d <- sim() %>% filter(time >= PRESIM)
    dd <- d %>% transmute(day = time - PRESIM,
                          `Plasma cabergoline (nM)` = CABNM,
                          `Pituitary biophase (nM)` = CAB_E,
                          `Plasma bromocriptine (nM)` = BRC_C/10700*1e6/654.6,
                          `Plasma quinagolide (nM)` = QUI_C/1200*1e6/395.6) %>%
      pivot_longer(-day) %>% filter(value > 1e-9)
    if (!nrow(dd)) return(NULL)
    ggplot(dd, aes(day, value, colour = name)) + geom_line(linewidth = 0.8) +
      scale_colour_manual(values = PAL) +
      labs(x = "Days after treatment start", y = "Concentration (nM)",
           title = "Why once weekly is enough",
           subtitle = "The biophase sits at about 60x the plasma concentration with a ~4 day half-life, so it is close to an infusion") +
      theme_prl()
  })

  output$txt_pk <- renderText({
    d <- sim() %>% filter(time > max(time) - 28)
    sprintf(paste0("  Plasma cabergoline, last 4 weeks    mean %.4f nM (= %.1f pg/mL)\n",
                   "  Biophase, last 4 weeks              mean %.3f nM (%.1fx the D2 Ki of 0.70 nM)\n",
                   "  Biophase peak/trough ratio          %.2f\n",
                   "  5-HT2B occupancy (plasma-driven)    mean %.4f\n",
                   "  D3 occupancy (plasma-driven)        mean %.4f\n"),
            mean(d$CABNM), mean(d$CABNM)*451.6, mean(d$CAB_E),
            mean(d$CAB_E)/0.7,
            ifelse(min(d$CAB_E) > 0, max(d$CAB_E)/min(d$CAB_E), NA),
            mean(d$OCC5HT), mean(d$OCCD3))
  })

  # ---- tab 4 --------------------------------------------------------------
  output$p_prl <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year,
                          `Biological (monomer)` = PRLB,
                          `Immunoreactive analyte` = PRLIMM,
                          `Reported value (assay)` = PRLMEAS_,
                          `After 1:100 dilution` = PRLDIL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_y_log10() + scale_colour_manual(values = PAL) + pres_line() +
      geom_hline(yintercept = 25, linetype = "33", colour = "grey50") +
      labs(x = "Years", y = "Prolactin (ng/mL, log)",
           title = "Four different prolactins",
           subtitle = "The gaps between the curves are the hook effect (reported value falls) and macroprolactin (it rises)") +
      theme_prl()
  })

  output$p_hook <- renderPlot({
    a <- 10^seq(1, 5, length.out = 300)
    dd <- data.frame(analyte = a,
                     `Reported_value` = a/(1 + (a/4000)^4),
                     `True_value` = a) %>% pivot_longer(-analyte)
    cur <- prs(sim(), "PRLIMM")
    ggplot(dd, aes(analyte, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_x_log10() + scale_y_log10() + scale_colour_manual(values = PAL[c(2,8)]) +
      geom_vline(xintercept = cur, linetype = "22", colour = PAL[3]) +
      annotate("text", x = cur, y = 20, label = " this patient", hjust = 0,
               colour = PAL[3], size = 3.5) +
      labs(x = "True immunoreactive analyte (ng/mL, log)", y = "Reported value (ng/mL, log)",
           title = "The hook of a two-site sandwich assay",
           subtitle = "Peaks at about 3000 ng/mL; above that antigen excess collapses the signal") +
      theme_prl()
  })

  # ---- tab 5 --------------------------------------------------------------
  output$p_tum <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Tumour volume (MRI, mL)` = TVOL_,
                          `Cell mass (mL)` = CELLN,
                          `Mean cell volume (relative)` = VCELL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Volume first, cell number later",
           subtitle = "Cell volume comes back within weeks, but the cells that are gone do not come back") +
      theme_prl()
  })

  output$p_clone <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Sensitive clone (mL)` = NS, `Resistant clone (mL)` = NR,
                          `Resistant fraction (%)` = 100*NR/(NS+NR+1e-12)) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL[c(3,2,4)]) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Clonal selection (Darwinian escape)",
           subtitle = "Under constant selection pressure the fraction of the low-D2R clone rises slowly") +
      theme_prl()
  })

  # ---- tab 6 --------------------------------------------------------------
  output$p_vf <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Visual field MD (dB)` = VFMD,
                          `Reversible conduction block (dB)` = -VFR,
                          `Irreversible axonal loss (dB)` = -AXL,
                          `Effective compressive force` = CEFF_) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Visual fields: what comes back and what is left as debt",
           subtitle = "Axonal loss accumulates in proportion to the time spent above the compression threshold and does not recover") +
      theme_prl()
  })

  output$p_hypo <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Hypopituitarism` = HYPOP,
                          `Cortisol reserve` = CORT, `FT4` = FT4, `IGF-1` = IGF1) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "Years", y = "vs normal", title = "Compressive hypopituitarism",
           subtitle = "Recovery is set slower than onset (surgical loss is permanent)") +
      theme_prl()
  })

  # ---- tab 7 --------------------------------------------------------------
  output$p_hpg <- renderPlot({
    d <- sim(); male <- input$sex == "male"
    dd <- d %>% transmute(year, `KNDy/kisspeptin` = KISS, `GnRH pulsatility` = GNRH,
                          `LH` = LH, `FSH` = FSH,
                          `Sex steroid (vs normal)` = if (male) TST/550 else E2G/60) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "Years", y = "vs normal",
           title = "The route by which prolactin causes infertility",
           subtitle = "Prolactin → STAT5 → Kiss1 suppression → reduced GnRH pulsatility → LH/FSH → sex steroids") +
      theme_prl()
  })

  output$p_repro <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Ovulatory capacity` = OVF, `Spermatogenesis index` = SPZ,
                          `Anovulation/amenorrhoea probability (%)` = AMENP/100,
                          `Galactorrhoea index (%)` = GALA/100) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "Years", y = "0-1", title = "Reproductive clinical endpoints") + theme_prl()
  })

  # ---- tab 8 --------------------------------------------------------------
  output$p_bone <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Lumbar BMD (g/cm2)` = BMD,
                          `Irreversible loss (g/cm2)` = BLOSSI,
                          `T-score` = TSCORE,
                          `Vertebral fracture probability (%)` = PFRACT) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Bone: the pathology that remains after prolactin normalises",
           subtitle = "Part of the loss is banked as a ratchet and never recovers at any time point") +
      theme_prl()
  })

  output$p_met <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `Body weight (kg)` = BW, `HOMA-IR` = IR,
                          `Bone resorption (OCF)` = OCF, `Bone formation (OBF)` = OBF) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "Years", y = NULL, title = "Metabolic and bone turnover") + theme_prl()
  })

  # ---- tab 9 --------------------------------------------------------------
  output$p_safe <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `5-HT2B occupancy (plasma)` = OCC5HT,
                          `Valvular fibrosis burden` = VALV/100,
                          `Moderate-or-worse TR probability (%)` = PTR/100,
                          `Impulse-control disorder probability (%)` = PICD/100,
                          `Nausea index (tolerance included)` = NAUS/100) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "Years", y = "0-1 scale",
           title = "Efficacy runs off the biophase, the valves off plasma — the two are not proportional",
           subtitle = "Impulse-control disorder comes from D3 occupancy, so avoiding the ergot scaffold does not reduce it") +
      theme_prl()
  })

  output$p_sweep <- renderPlot({
    i <- reactiveValuesToList(input); i$horizon <- 5
    kis <- c(1.2, 3.6, 12, 36, 120, 1200)
    res <- do.call(rbind, lapply(kis, function(k) {
      j <- i; j$ki5ht <- k; d <- simulate(j)
      data.frame(ki = k, PRL = d$PRLB[nrow(d)], valve = d$VALV[nrow(d)],
                 PTR = d$PTR[nrow(d)])
    }))
    res2 <- res %>% transmute(ki, `Prolactin (ng/mL)` = PRL,
                              `Valvular burden` = valve,
                              `TR probability (%)` = PTR) %>% pivot_longer(-ki)
    ggplot(res2, aes(ki, value, colour = name)) +
      geom_line(linewidth = 0.9) + geom_point() +
      facet_wrap(~name, scales = "free_y") + scale_x_log10() +
      scale_colour_manual(values = PAL) + guides(colour = "none") +
      labs(x = "5-HT2B Ki (nM, log — further right is more selective)", y = NULL,
           title = "Selectivity sweep across 4 orders of magnitude",
           subtitle = "Prolactin control does not change; only valvular risk collapses") +
      theme_prl()
  })

  # ---- tab 10 -------------------------------------------------------------
  cmp_runs <- reactive({
    i <- reactiveValuesToList(input)
    mk <- function(lab, mod_fn) { j <- mod_fn(i); d <- simulate(j); d$arm <- lab; d }
    switch(input$cmp,
      "cabergoline vs bromocriptine vs quinagolide" = rbind(
        mk("cabergoline 1 mg/wk", function(j){j$da<-"cabergoline";j$cabdose<-1;j}),
        mk("bromocriptine 7.5 mg/d", function(j){j$da<-"bromocriptine";j$brcdose<-7.5;j}),
        mk("quinagolide 300 ug/d", function(j){j$da<-"quinagolide";j$quidose<-300;j}),
        mk("no treatment", function(j){j$da<-"none";j})),
      "cabergoline dose 0.25 / 0.5 / 1 / 2 / 3.5 mg/week" = do.call(rbind,
        lapply(c(0.25,0.5,1,2,3.5), function(x)
          mk(sprintf("%.2f mg/wk", x),
             function(j){j$da<-"cabergoline";j$cabdose<-x;j}))),
      "partial resistance vs true resistance (± dose escalation)" = rbind(
        mk("partial resistance 0.5 mg/wk", function(j){j$d2rs<-0.15;j$cabdose<-0.5;j$da<-"cabergoline";j}),
        mk("partial resistance 3.5 mg/wk", function(j){j$d2rs<-0.15;j$cabdose<-3.5;j$da<-"cabergoline";j}),
        mk("true resistance 0.5 mg/wk", function(j){j$d2rs<-0.04;j$cabdose<-0.5;j$da<-"cabergoline";j}),
        mk("true resistance 3.5 mg/wk", function(j){j$d2rs<-0.04;j$cabdose<-3.5;j$da<-"cabergoline";j})),
      "treatment delay 0 / 1 / 2 / 4 years" = do.call(rbind,
        lapply(c(0, 365, 730, 1460), function(x)
          mk(sprintf("%.0f-year delay", x/365),
             function(j){j$startday<-x;j$da<-"cabergoline";j$cabdose<-1;j}))),
      "relapse after withdrawal by residual volume" = do.call(rbind,
        lapply(c(0.05, 0.2, 0.6, 1.6), function(x)
          mk(sprintf("initial %.2f mL", x),
             function(j){j$ns0<-x;j$d2rs<-0.5;j$da<-"cabergoline";j$cabdose<-1;
                         j$stopyr<-3;j$horizon<-max(j$horizon,12);j})))
    )
  })

  output$p_cmp <- renderPlot({
    d <- cmp_runs()
    dd <- d %>% transmute(year, arm, `Prolactin (ng/mL)` = PRLB,
                          `Tumour volume (mL)` = TVOL_,
                          `Visual field MD (dB)` = VFMD, `T-score` = TSCORE) %>%
      pivot_longer(-c(year, arm))
    ggplot(dd, aes(year, value, colour = arm)) + geom_line(linewidth = 0.85) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() +
      labs(x = "Years", y = NULL, title = input$cmp) + theme_prl()
  })

  output$tbl_cmp <- renderDT({
    d <- cmp_runs()
    s <- d %>% group_by(arm) %>%
      summarise(`PRL at diagnosis` = round(PRLB[which.min(abs(time - PRESIM))], 1),
                `Final PRL` = round(last(PRLB), 1),
                `Final volume mL` = round(last(TVOL_), 3),
                `Shrinkage %` = round(100*(1 - last(TVOL_)/TVOL_[which.min(abs(time-PRESIM))]), 0),
                `Final MD dB` = round(last(VFMD), 1),
                `Final T-score` = round(last(TSCORE), 2),
                `TR probability %` = round(last(PTR), 2), .groups = "drop")
    datatable(s, rownames = FALSE, options = list(dom = "t"))
  })

  # ---- tab 11 -------------------------------------------------------------
  output$p_wd <- renderPlot({
    i <- reactiveValuesToList(input)
    i$da <- "cabergoline"; i$cabdose <- max(i$cabdose, 1); i$stopyr <- 3
    i$horizon <- max(i$horizon, 12)
    d <- simulate(i)
    dd <- d %>% transmute(year, `Prolactin (ng/mL)` = PRLB,
                          `Tumour volume (mL)` = TVOL_, `Cell mass (mL)` = CELLN,
                          `Mean cell volume` = VCELL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() +
      geom_vline(xintercept = (PRESIM + 3*365)/365, linetype = "22",
                 colour = PAL[2]) +
      guides(colour = "none") +
      labs(x = "Years", y = NULL,
           title = "Withdrawal after 3 years of treatment (red dashed line = withdrawal)",
           subtitle = "Volume re-expands within weeks, but that is not regrowth, it is cell re-swelling") +
      theme_prl()
  })

  output$txt_wd <- renderText({
    i <- reactiveValuesToList(input)
    i$da <- "cabergoline"; i$cabdose <- max(i$cabdose, 1); i$stopyr <- 3
    i$horizon <- max(i$horizon, 12)
    d <- simulate(i); tstop <- PRESIM + 3*365
    aft <- d$time > tstop + 30
    irec <- which(d$PRLB[aft] > 25)[1]
    paste0(
      sprintf("  Cell mass at withdrawal                 %.4f mL\n", atd(d,"CELLN",tstop)),
      sprintf("  Prolactin at withdrawal                 %.1f ng/mL\n", atd(d,"PRLB",tstop)),
      sprintf("  Volume change 30 days after stopping    %+.1f%% (cell-number change %+.1f%%)\n",
              100*(atd(d,"TVOL_",tstop+30)/atd(d,"TVOL_",tstop) - 1),
              100*(atd(d,"CELLN",tstop+30)/atd(d,"CELLN",tstop) - 1)),
      sprintf("  Time to biochemical relapse             %s\n",
              ifelse(is.na(irec), "none within the observation period",
                     sprintf("%.1f years", (d$time[aft][irec] - tstop)/365))),
      "\n  This model does not produce a cure. Whenever residual cells remain there is always relapse,\n",
      "  and a smaller residual only delays it. This in fact refutes the hypothesis the mechanistic map\n",
      "  set out (that endogenous dopamine holds a small residual in check), and it does so because\n",
      "  the short loop is driven by prolactin, so endogenous tone is at its weakest exactly when the\n",
      "  residual is small. See diagnostic D10 in the model file.\n")
  })
}

shinyApp(ui, server)
