#!/usr/bin/env python3
# Generate the Korean spoken-script document with SLIDE NUMBERS -> script_ko.docx
import os
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.oxml.ns import qn

HERE=os.path.dirname(os.path.abspath(__file__))
OUT=os.path.join(HERE,"..","script_ko.docx")
TITLE="An LLM-Augmented R/Shiny Platform for Quantitative Systems Pharmacology — presentation script (40 slides)"
NAVY=RGBColor(0x16,0x3A,0x5F)

# (slide number, short Korean title, narration). Use \n\n inside text for paragraph breaks.
SLIDES=[
(1,"Title · greeting",
 "Good afternoon. I am Sungpil Han, from the Department of Pharmacology and the PIPET pharmacokinetics laboratory at the Catholic University of Korea College of Medicine. Today I will speak under the title ‘An LLM-based R/Shiny platform for quantitative systems pharmacology’. Standing before an audience that works on mathematical modelling, I would like to describe how one problem in drug development is being solved with mathematics, and how artificial intelligence is accelerating that process."),
(2,"Presentation overview",
 "The one-line thesis of today's talk is this. Quantitative systems pharmacology, or QSP, is the discipline that expresses drug action as a large system of nonlinear ordinary differential equations. But building such a model by hand is very slow, and therefore very rare. So we let an autonomous large language model agent build these models instead, and as a result more than 190 disease models now exist, with roughly one more being added almost every day. I will speak in the order of the problem statement, the mathematics of QSP, the autonomous engine, the usefulness of artificial intelligence, the scale and breadth, and then concrete cases and open mathematical problems."),
(3,"The cost and the failures of drug development",
 "Let me start with the problem. Taking a single new drug through to approval usually takes 10 to 15 years and, in capitalised cost, on the order of one to two point six trillion won. What is more painful is that about 90 percent of the candidates that enter clinical trials never reach a patient. The failures cluster at two points. One is early, where the target was never mechanistically validated in the first place; the other is late, in the large trials, where unexpected lack of efficacy or a safety problem emerges."),
(4,"The mechanistic gap",
 "This is where the difference between statistical and mechanistic models matters. A statistical model interpolates well ‘inside’ the observed data. It predicts what happened well, but it is weak at extrapolating to a new dose, a new patient population, or a new combination. A mechanistic model such as QSP, by contrast, directly encodes the causal structure that runs from target to pathway and from pathway to disease. Because it explains why, and how, such a result arises, we arrive at the conclusion that to predict a drug that does not yet exist you must in the end model the mechanism through which it will act."),
(5,"What is QSP",
 "So what exactly is QSP? QSP is a field that combines systems biology with pharmacokinetics and pharmacodynamics. It describes in mathematics the causal chain that runs from drug to target, from target to pathway, and on to disease and patient. This kind of model answers questions statistics cannot: if this target is modulated, how far does the effect propagate downstream; which patient subtype responds and why; which dose, which dosing interval, or which combination optimises the balance of efficacy and safety."),
(6,"Anatomy of a QSP model",
 "Mathematically a QSP model is an initial value problem. It is a coupled nonlinear dynamical system in which the time derivative of the state vector x is given as a function f of x, the parameters theta and the dosing input u. Here the state x includes drug concentrations, receptor occupancy, signalling molecules, cell populations, biomarkers and even clinical endpoints. The parameters theta are rate constants, half-maximal effect concentrations, maximum effects, Hill coefficients, clearances and binding affinities, and the input u is the dosing regimen, the only handle we can actually turn. The models in our library usually consist of 15 to 35 or more coupled differential equations and 70 to over 100 parameters."),
(7,"Recurring nonlinear structures",
 "What is interesting is that even when the disease changes, the mathematical structure recurs. There is a kind of common grammar. The Hill and Emax expressions of pharmacodynamics; indirect response, that is turnover, models expressed as a balance of synthesis and degradation; mass-action binding such as immune complex formation; logistic growth as seen in tumours or in vascular remodelling; target-mediated drug disposition, TMDD; and structures such as the power-law feedback of erythropoietin on anaemia, or threshold switching. These motifs appear in common in almost every disease model."),
(8,"Why QSP matters (MIDD)",
 "QSP matters in drug development because it is a core tool of model-informed drug development, MIDD, which the regulators themselves recommend. At the target validation stage it assesses whether target modulation actually reaches the phenotype and whether bypass routes or resistance exist, weeding out hopeless targets early. It quantifies the mechanism of action, builds the biomarker strategy, and sets the first-in-human dose on mechanistic grounds, making the clinical programme safer and more efficient. It designs trials using virtual patients, performs cross-species and cross-population extrapolation, and explores the synergy and the antagonism of combinations in advance. In short, QSP lets you close down the programmes that will fail sooner and more cheaply, and grow the ones that will succeed strategically."),
(9,"The bottleneck",
 "The problem is the cost. Traditionally, building a single QSP model properly takes an expert months to years. You have to synthesise a vast literature, set up the differential equations carefully and fix the parameters, then implement, calibrate and visualise it in software. As a result only a handful of diseases ever get a model, those models are closed and hard to reproduce, and the many diseases in the long tail are left never modelled at all."),
(10,"The core proposal — LLM-based generation",
 "So our proposal is this. Use an autonomous large language model coding agent to build complete, quality-controlled, literature-anchored QSP models at a rate of roughly one disease per day, with every artefact under version control. Each model consists of four artefacts: a mechanistic map drawn in Graphviz, a differential equation model written in mrgsolve, a Shiny dashboard, and an organised reference list."),
(11,"Platform structure",
 "These four artefacts are not outputs that stand apart from one another; they interlock. An autonomous agent called Claude Code Routine starts from the literature and builds the map, the differential equation model, the dashboard and the references, and commits all of it to a Git repository. It is a pipeline that runs from one agent to four interoperable artefacts and on to a version-controlled repository."),
(12,"Claude Code Routine — the autonomous loop",
 "The engine is called Claude Code Routine. It is a coding agent that runs on a schedule, roughly once a day. Each time it runs it completes one disease from beginning to end and pushes it. It picks a disease not yet covered, reads and synthesises about 50 papers, draws a map with more than 100 nodes, writes 15 or more differential equations, builds a dashboard with 6 or more tabs, organises the references, and then commits and pushes automatically. The key is the Git stop hook. Because it forces the session not to end until everything is committed and pushed, no work is ever left half finished."),
(13,"Inside one session, and the safeguards",
 "It would mean nothing if the artificial intelligence had written code a human cannot trust. So trust is secured by three devices. First, structural and quality gates. The map must have at least 100 nodes and 8 clusters, the model at least 15 compartments and 5 scenarios, the dashboard at least 6 tabs, and the references at least 30 papers; these minima are enforced. Second, reusable mathematical templates. Because it uses validated motifs such as Hill, turnover and TMDD, there is less room to go wrong. Third, literature anchoring. Every parameter carries a calibration note citing a clinical trial, and this is the single most important device against hallucination. And because everything is code inside Git, it can be diffed, audited and re-run, and a human reviews it scientifically before use."),
(14,"Why LLM/AI",
 "Why should a large language model be the engine suited to this job? First, it works continuously without tiring. It runs all day without fatigue and completes a complex, multi-artefact disease model almost every day. No human team can sustain that pace. Second, it synthesises a vast literature. Across the whole library it integrates about 9,700 papers, roughly 50 per model, reading and organising the evidence far faster than a person reviewing by hand. Third, the breadth of diseases and drugs is wide. It handles more than 190 diseases and hundreds of drugs and targets within a single consistent framework. Fourth, it is standardised, so the models are comparable and reusable, and it turns an expert's months into hours. In the end the scarce resource is modelling expertise, and artificial intelligence is exactly what scales that expertise."),
(15,"Artefact ① the mechanistic map",
 "Now let us look at the four artefacts in turn. The first is the mechanistic map. This is a directed multigraph with clusters. The vertices are species or states, the edges are mechanistic interactions such as activation, inhibition or mass transfer, and the clusters correspond to pathway modules, that is, to community structure on the graph. It is built with Graphviz, rendered to SVG and PNG, and version controlled. Each model has around twelve pathway modules on average, and some maps hold more than 600 graph elements."),
(16,"Artefact ② the mrgsolve model",
 "The second is the mrgsolve differential equation model. What you see is a fragment of the real code that transcribes the four-hit hypothesis of IgA nephropathy. Immune complexes form by mass action, complement amplifies, the drug effect enters through a Hill function, and combination effects are combined under a Bliss independence assumption. A compiled C++ solver handles the stiff equations and the event-driven dosing, connecting pharmacokinetics, disease pharmacodynamics and clinical endpoints into one. This is not pseudocode; it is systems pharmacology that actually runs."),
(17,"Artefacts ③·④ the dashboard and the evidence",
 "The third and fourth are the Shiny dashboard and the reference evidence. In the dashboard you can look through patient profile, pharmacokinetics, pathophysiology, clinical endpoints, scenario comparison and biomarkers across six to eight tabs without knowing any code. The references organise about 50 PubMed citations per model by mechanism, tying every parameter and every claim to the literature. It is the evidence that separates a model from a guess."),
(18,"Code — mrgsolve",
 "Now let us go briefly into the code. The first screen is the model expressed in mrgsolve. It is a short programme made of a parameter block, a compartment block and a differential equation block. It computes the plasma drug concentration, defines the Hill inhibition, and writes the gut and central compartments, oestradiol turnover, and the oestradiol-driven lesion growth in a few lines. About 40 lines give you a complete model running from pharmacokinetics through hormone to disease."),
(19,"Code — Shiny",
 "The second screen is the same model made into a Shiny app. A reactive server takes the slider inputs, updates the model parameters, sets up the dosing events, runs the simulation and draws the oestradiol and pain curves. Move a slider and the differential equations are solved again, and oestradiol, pain and bone mineral density update in real time."),
(20,"Code — routine pseudocode",
 "The third screen summarises Claude Code Routine itself as pseudocode. Inside an infinite loop that repeats on a schedule, it picks an uncovered disease, reads the literature, builds the map, writes the differential equations, builds the dashboard, passes the quality gates, and then commits and pushes under the compulsion of the stop hook. One disease from beginning to end, on every run, and never tiring."),
(21,"Scale",
 "Let us look at the scale of the library that has grown this way. There are currently more than 190 disease models, about 15 therapeutic areas, more than 190 differential equation systems, about 2,200 pathway clusters and about 9,700 PubMed references. And it keeps growing by roughly one a day. Each one is a complete, executable, literature-supported QSP model."),
(22,"Map gallery",
 "This screen gathers together some of those maps. Each picture is the mechanistic map of one disease, produced by a single autonomous build. Work that used to take days per figure is now accumulating at a rate of one a day."),
(23,"Breadth of coverage",
 "I would also like to stress the breadth of coverage. Solid tumours and haematological malignancies, autoimmunity and rheumatology, vasculitis, cardiovascular, respiratory, renal and urological, gastrointestinal and hepatobiliary, endocrine and metabolic, neurological, psychiatric, dermatological, infectious, ophthalmic, and rare and genetic disease: one consistent framework runs across the spectrum of human disease. It includes cancers such as breast and lung cancer, glioblastoma, leukaemia and multiple myeloma; rare and genetic diseases such as Fabry disease, Gaucher disease, muscular dystrophy and amyloidosis; common chronic diseases such as diabetes and heart failure; and immune and haematological diseases such as lupus and sickle cell disease. Inside it are hundreds of different drugs and molecular targets."),
(24,"Case collection 1",
 "Let me introduce a few cases in one line each. In non-small cell lung cancer the model predicts when the T790M and C797S resistant clones will emerge against osimertinib, giving a rationale for combination or sequential therapy. In heart failure with reduced ejection fraction it explores the dosing order and up-titration rate of ARNI, beta-blocker, aldosterone antagonist and SGLT2 inhibitor against left ventricular reverse remodelling. In transthyretin amyloidosis it follows the tetramer and monomer kinetics when TTR is silenced with patisiran or vutrisiran, and the neuropathy and cardiac burden over several years."),
(25,"Case collection 2",
 "Next, three more. In systemic lupus erythematosus anifrolumab inhibits type I interferon signalling, and the model links the chain that runs from interferon to autoantibody and on to flare risk. In type 2 diabetes it looks at the glycated haemoglobin and body weight trajectories through the glucose, insulin and weight feedback of incretin drugs such as tirzepatide. In immune thrombocytopenia it compares the effect of a thrombopoietin receptor agonist and of antiplatelet antibodies through the balance of platelet production and destruction."),
(26,"Drug · target · endpoint",
 "We have also organised these drug, target and endpoint relationships into a table. Tocilizumab in rheumatoid arthritis targets the interleukin-6 receptor and moves disease activity and C-reactive protein; semaglutide in type 2 diabetes moves glycated haemoglobin and body weight through the GLP-1 receptor; and sacubitril-valsartan in heart failure with reduced ejection fraction moves left ventricular ejection fraction and NT-proBNP through neprilysin and the angiotensin receptor. From osimertinib in non-small cell lung cancer, macitentan in pulmonary arterial hypertension, sparsentan in IgA nephropathy, voxelotor in sickle cell disease, through to daratumumab in multiple myeloma, hundreds of drug, target and endpoint relationships are all grounded in the clinical literature."),
(27,"Deep dive — IgA nephropathy",
 "Now let us look at three cases in a little more depth. First, IgA nephropathy. It is the most common primary glomerulonephritis in the world, and about 30 percent of patients reach renal failure within 20 years. Galactose-deficient IgA1 is the first hit, the autoantibody against it the second, the circulating immune complex the third, and mesangial deposition with complement activation the fourth, leading on to glomerular injury, proteinuria and declining renal function. The model contains RAAS blockade, budesonide aimed at gut mucosal B cells, sparsentan which blocks the endothelin and angiotensin receptors simultaneously, iptacopan which blocks complement factor B, and sibeprenlimab directed at APRIL, and it was calibrated against the NefIgArd, PROTECT and APPLAUSE trials."),
(28,"Deep dive — sickle cell disease",
 "The second is sickle cell disease. A single point mutation in beta-globin makes a lifelong multi-organ disease. When HbS polymerises in the deoxygenated state the red cell deforms into a sickle shape and haemolysis occurs, free haemoglobin consumes nitric oxide, the endothelium is activated, and this leads on to vaso-occlusive crises, chronic anaemia and progressive organ damage. The model contains hydroxyurea as a fetal haemoglobin inducer, voxelotor which raises the oxygen affinity of HbS, crizanlizumab which blocks P-selectin, and L-glutamine which reduces oxidative stress, and it was calibrated against the MSH, HOPE and SUSTAIN trials."),
(29,"Deep dive — multiple myeloma",
 "The third is multiple myeloma, the representative case in oncology. A plasma cell clone in the bone marrow secretes a monoclonal protein, interleukin-6 drives growth in an autocrine fashion, and an imbalance of RANKL, OPG and DKK1 causes lytic bone disease and immune paresis. The model contains the proteasome inhibitors bortezomib and carfilzomib, the immunomodulator lenalidomide, the anti-CD38 antibody daratumumab expressed with target-mediated disposition, and the BCL-2 inhibitor venetoclax together with bone-directed zoledronic acid. Tumour burden is described by an equation that adds a resistant clone and an interleukin-6 term to logistic growth, and several standard combination regimens are compared."),
(30,"Simulation snapshot",
 "These curves show the dynamics of reduced models of the three cases. They are representative trajectories comparing treated and untreated arms; the actual mrgsolve models drive the interactive Shiny dashboards."),
(31,"Flagship case — the merigolix model",
 "Now let me show you today's flagship case. Merigolix is an oral gonadotropin-releasing hormone antagonist for endometriosis. It blocks the receptor to lower luteinising hormone and follicle-stimulating hormone, and as a result suppresses ovarian oestradiol, reducing oestrogen-dependent lesions and pain. A single model ties together two-compartment pharmacokinetics, the pharmacodynamics of the hypothalamic-pituitary-gonadal axis, and clinical endpoints such as pain, lesion size, hot flushes, bone mineral density and endometrial thickness. The chain that runs from drug to hormone, from hormone to lesion, and from lesion to symptom sits inside one system of differential equations."),
(32,"Merigolix — the oestrogen threshold trade-off",
 "The heart of this case is a trade-off called the oestrogen threshold. This idea, also known as Barbieri's hypothesis, is that if oestradiol is suppressed too little there is no symptom relief, and if it is suppressed too much hot flushes and bone loss follow. So you have to aim for a partial suppression window of roughly 20 to 40 picograms. The model quantifies this. The dose sets the oestradiol trough, and that trough simultaneously governs the benefit, pain and lesion, and the risk, bone mineral density and hot flushes. In this simulation the oestradiol trough was 2.6, pain fell from 3.1 to 1.1 and the lesion from 18.5 to 5.3 millimetres, but bone mineral density fell by 1.22 percent and hot flushes rose from 5.4 to 7.9 per day. This is exactly the point that shows the need for dose titration and add-back hormone therapy. QSP turns a clinical trade-off into a tractable optimisation problem."),
(33,"The live app",
 "And this is not merely a picture. This dashboard is a genuinely deployed, publicly available Shiny app. The address is pipetqsp.shinyapps.io slash merigolix, and scanning the QR code on the screen or clicking the link opens it straight away. Change the dose, the dosing interval, the cycle timing, or the IC50 and clearance multipliers, and the equations are solved again and every endpoint updates immediately. I encourage you to try it for yourselves after the talk."),
(34,"The mathematics of the library as a whole",
 "Beyond the individual cases, the mathematics of the library as a whole also becomes an object of study. These distributions show the number of pathway clusters, the number of references and the graph size across the roughly 190 models. A collection of standardised nonlinear dynamical systems is itself a mathematically interesting object."),
(35,"Open mathematical problems — an invitation to collaborate",
 "This is exactly where your role, the role of the mathematicians, begins. Roughly 190 nonlinear differential equation systems are a playground for applied mathematics. Structural and practical identifiability, which asks which parameters can be recovered from realistic measurements; global sensitivity analysis such as Sobol or Morris; model reduction such as time-scale separation and the quasi-steady-state approximation; uncertainty quantification that carries parameter and structural uncertainty through into prediction intervals; stability and bifurcation analysis, such as the threshold at which the right ventricle in pulmonary arterial hypertension crosses from adaptation into maladaptation; and inverse problems that fit parameter distributions to data, along with virtual population generation. Because the roughly 190 models share one schema, any method you develop carries over to every model unchanged. I sincerely hope we can work together."),
(36,"Validation and limitations",
 "Of course I must state the limitations plainly. These models are mechanistically structured, they are anchored in the literature, and they are calibrated to published clinical trial endpoints. For hypothesis generation, for teaching, and as the skeleton of model-informed drug development they are excellent. But they are not yet fitted to individual patient data and cannot be used directly for clinical decision-making. Because a model that looks plausible can still be wrong, the references and human verification are essential, and formal validation is future work. Stating the scope honestly is also part of the method. Artificial intelligence writes the draft; science validates it."),
(37,"Reproducibility and openness",
 "I would also like to stress reproducibility and openness. Every model, made up of code, map and references, is open in a single public Git repository. Each one can be run independently and explored through a dashboard, and for every parameter there is a record of who changed what and when, so it can be diffed and audited. This library grows in the open, one verifiable commit at a time."),
(38,"Comparison with the traditional approach",
 "Compared with the traditional approach this is not an incremental improvement but a step change, both in the number of diseases that can be covered and in the effort spent per model. Work that took an expert months has come down to hours, and a handful of diseases has become a library of more than 190."),
(39,"Future directions",
 "As future directions we are thinking about Bayesian calibration against real pharmacokinetic and pharmacodynamic and electronic health record data; virtual populations that sample parameter distributions, and clinical trial simulation; automated model reduction that extracts the minimal mechanistic core; coupling with clinical pharmacometrics pipelines; formal verification of the generated equation structures and units; and community contribution as an open, extensible standard."),
(40,"Conclusion and an open invitation",
 "Let me summarise. Drug development needs mechanism, and that mechanism is expressed as a system of nonlinear differential equations. QSP provides it, but until now it has been slow, rare and closed. An autonomous large language model agent changes that economics, producing roughly 190 complete, evidence-based, reproducible models, and one more almost every day. The result is a standardised mathematical corpus of human disease, and it lies open to your methods.\n\nFinally I would like to make one thing clear. This project is completely open. Whether you would like to extend the models, apply your own methods, or develop a new disease together, if there is any researcher who would like to attempt this with us, we would be glad to work together. The repository is at github.com slash pipetcpt slash qsp, and my email is shan at catholic.ac.kr. Thank you for your attention. Questions and collaboration are both welcome."),
]

def set_ko(run):
    run.font.name="Malgun Gothic"; run.element.rPr.rFonts.set(qn("w:eastAsia"),"Malgun Gothic")

doc=Document()
st=doc.styles["Normal"]; st.font.name="Malgun Gothic"; st.font.size=Pt(11)
st.element.rPr.rFonts.set(qn("w:eastAsia"),"Malgun Gothic")
for s in doc.sections:
    s.top_margin=s.bottom_margin=Cm(2.2); s.left_margin=s.right_margin=Cm(2.5)

p=doc.add_paragraph(); r=p.add_run(TITLE); r.bold=True; r.font.size=Pt(13); set_ko(r)
doc.add_paragraph("")
for n,title,text in SLIDES:
    hp=doc.add_paragraph(); hp.paragraph_format.space_before=Pt(8); hp.paragraph_format.space_after=Pt(3)
    hr=hp.add_run(f"[Slide {n}] {title}"); hr.bold=True; hr.font.size=Pt(11.5); hr.font.color.rgb=NAVY; set_ko(hr)
    for chunk in text.split("\n\n"):
        bp=doc.add_paragraph(chunk); bp.paragraph_format.line_spacing=1.5; bp.paragraph_format.space_after=Pt(8)
        for rr in bp.runs: set_ko(rr)
doc.save(OUT)
print("saved", OUT, "slides:", len(SLIDES))
