##############################################################################
# CML QSP Shiny Application
# Chronic Myeloid Leukemia — Interactive Dashboard
#
# 6 Tabs:
#   1. Patient Profile — Sokal/EUTOS score, baseline BCR-ABL
#   2. PK Profiles — TKI plasma concentration vs time
#   3. Molecular Response — BCR-ABL IS%, ELN milestones
#   4. Cell Kinetics — Normal vs leukemic populations
#   5. TKI Comparison — Multiple drugs head-to-head
#   6. Resistance & TFR — T315I probability, TFR success
#
# Author: Generated by Claude Code (CCR) — 2026-06-20
##############################################################################

library(shiny)
library(shinydashboard)
library(mrgsolve)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(DT)

# ============================================================
# MODEL CODE (inline for self-contained app)
# ============================================================
cml_model_code <- '
$PARAM @annotated
ay0:0.008:HSC self-renewal rate
by0:0.004:HSC differentiation rate
dy0:0.003:HSC death rate
by1:0.05:CMP differentiation rate
dy1:0.02:CMP death rate
by2:0.2:GMP differentiation rate
dy2:0.05:GMP death rate
dy3:0.10:Neutrophil death rate
c1:10.0:HSC→CMP amplification
c2:8.0:CMP→GMP amplification
c3:16.0:GMP→Neutrophil amplification
a0:0.04:LSC self-renewal
b0:0.01:LSC differentiation
d0:0.003:LSC death
q_act:0.005:Quiescent LSC activation rate
q_dorm:0.02:LSC quiescence rate
a1:0.03:LPC1 self-renewal
b1:0.08:LPC1 differentiation
d1:0.015:LPC1 death
b2:0.15:LPC2 differentiation
d2:0.04:LPC2 death
d3:0.12:Leukemic blast death
lc1:15.0:LSC→LPC1 amplification
lc2:10.0:LPC1→LPC2 amplification
lc3:20.0:LPC2→WBC amplification
as0:0.035:Sensitive LSC self-renewal
bs0:0.012:Sensitive LSC differentiation
ds0:0.004:Sensitive LSC death
asp:0.04:Sensitive progenitor proliferation
dsp:0.02:Sensitive progenitor death
ar0:0.032:Resistant LSC self-renewal
br0:0.010:Resistant LSC differentiation
dr0:0.005:Resistant LSC death
arp:0.038:Resistant progenitor proliferation
drp:0.022:Resistant progenitor death
mu:1e-8:Mutation rate
ka_imt:0.8:Imatinib absorption rate
F_imt:0.98:Imatinib bioavailability
Vd_imt:435.0:Imatinib Vd (L)
CL_imt:14.0:Imatinib CL (L/h)
Kin_imt:0.5:OCT1 influx rate
Kout_imt:0.3:Intracellular efflux rate
IC50_imt:0.25:Imatinib IC50 (µM)
Emax_imt:0.90:Imatinib Emax
Hill_imt:1.2:Imatinib Hill coefficient
ka_das:3.5:Dasatinib absorption rate
F_das:0.24:Dasatinib bioavailability
Vd_das:2505.0:Dasatinib Vd (L)
CL_das:220.0:Dasatinib CL (L/h)
Kic_das:0.8:Dasatinib IC accumulation
Kout_das:0.4:Dasatinib IC efflux
IC50_das:0.025:Dasatinib IC50 (µM)
Emax_das:0.95:Dasatinib Emax
Hill_das:1.1:Dasatinib Hill
ka_nil:0.6:Nilotinib absorption rate
F_nil:0.35:Nilotinib bioavailability
Vd_nil:3100.0:Nilotinib Vd (L)
CL_nil:42.0:Nilotinib CL (L/h)
Kic_nil:0.6:Nilotinib IC accumulation
Kout_nil:0.35:Nilotinib IC efflux
IC50_nil:0.02:Nilotinib IC50 (µM)
Emax_nil:0.93:Nilotinib Emax
Hill_nil:1.15:Nilotinib Hill
ka_asc:1.2:Asciminib absorption rate
F_asc:0.72:Asciminib bioavailability
Vd_asc:95.0:Asciminib Vd (L)
CL_asc:7.5:Asciminib CL (L/h)
IC50_asc:0.0005:Asciminib IC50 (µM)
Emax_asc:0.90:Asciminib Emax
Hill_asc:1.3:Asciminib Hill
Kcomp:1e-9:Competition coefficient
kNK_kill:0.001:NK kill rate
kCTL_kill:0.0005:CTL kill rate
NK_base:1e8:Baseline NK count
CTL_base:5e7:Baseline CTL count
dose_imt:0:Imatinib dose (mg/day)
dose_das:0:Dasatinib dose (mg/day)
dose_nil:0:Nilotinib dose (mg/day)
dose_asc:0:Asciminib dose (mg/day)
risk_mult:1.0:Patient risk multiplier (Sokal)
OCT1_func:1.0:OCT1 functional activity (0-2)

$CMT y0 y1 y2 y3 x0q x0p x1 x2 x3 xs xsp xr xrp
     Gut_imt Cp_imt Cic_imt Cp_das Cic_das
     Gut_nil Cp_nil Cic_nil Gut_asc Cp_asc

$INIT
y0=1e4 y1=5e4 y2=4e5 y3=4e9
x0q=1e4 x0p=2e3 x1=1e7 x2=5e7 x3=5e10
xs=8e3 xsp=8e6 xr=10 xrp=100
Gut_imt=0 Cp_imt=0 Cic_imt=0
Cp_das=0 Cic_das=0
Gut_nil=0 Cp_nil=0 Cic_nil=0
Gut_asc=0 Cp_asc=0

$ODE
double dose_rate_imt = dose_imt / 24.0 / 493.6 * 1000.0;
double dose_rate_das = dose_das / 24.0 / 488.0 * 1000.0;
double dose_rate_nil = dose_nil / 24.0 / 529.5 * 1000.0;
double dose_rate_asc = dose_asc / 24.0 / 449.5 * 1000.0;

dxdt_Gut_imt = F_imt * dose_rate_imt - ka_imt * Gut_imt;
dxdt_Cp_imt  = ka_imt * Gut_imt / Vd_imt - (CL_imt / Vd_imt) * Cp_imt;
dxdt_Cic_imt = OCT1_func * Kin_imt * Cp_imt - Kout_imt * Cic_imt;

dxdt_Cp_das  = F_das * dose_rate_das / Vd_das - (CL_das / Vd_das) * Cp_das;
dxdt_Cic_das = Kic_das * Cp_das - Kout_das * Cic_das;

dxdt_Gut_nil = F_nil * dose_rate_nil - ka_nil * Gut_nil;
dxdt_Cp_nil  = ka_nil * Gut_nil / Vd_nil - (CL_nil / Vd_nil) * Cp_nil;
dxdt_Cic_nil = Kic_nil * Cp_nil - Kout_nil * Cic_nil;

dxdt_Gut_asc = F_asc * dose_rate_asc - ka_asc * Gut_asc;
dxdt_Cp_asc  = ka_asc * Gut_asc / Vd_asc - (CL_asc / Vd_asc) * Cp_asc;

double Cimt_eff = fmax(Cic_imt, 0.0);
double E_imt = Emax_imt * pow(Cimt_eff, Hill_imt) /
               (pow(IC50_imt, Hill_imt) + pow(Cimt_eff, Hill_imt) + 1e-15);
double Cdas_eff = fmax(Cic_das, 0.0);
double E_das = Emax_das * pow(Cdas_eff, Hill_das) /
               (pow(IC50_das, Hill_das) + pow(Cdas_eff, Hill_das) + 1e-15);
double Cnil_eff = fmax(Cic_nil, 0.0);
double E_nil = Emax_nil * pow(Cnil_eff, Hill_nil) /
               (pow(IC50_nil, Hill_nil) + pow(Cnil_eff, Hill_nil) + 1e-15);
double Casc_eff = fmax(Cp_asc, 0.0);
double E_asc = Emax_asc * pow(Casc_eff, Hill_asc) /
               (pow(IC50_asc, Hill_asc) + pow(Casc_eff, Hill_asc) + 1e-15);

double E_total_sens = fmin(0.98, E_imt + E_das + E_nil + E_asc);

double Ntotal = x0q + x0p + x1 + x2 + x3 + xs + xsp + xr + xrp +
                y0 + y1 + y2 + y3;
double suppress = fmax(0.0, 1.0 - Kcomp * Ntotal);

dxdt_y0 = ay0 * y0 - by0 * y0 - dy0 * y0;
dxdt_y1 = c1 * by0 * y0 - by1 * y1 - dy1 * y1;
dxdt_y2 = c2 * by1 * y1 - by2 * y2 - dy2 * y2;
dxdt_y3 = c3 * by2 * y2 - dy3 * y3;

double q_in  = q_dorm * x0p;
double q_out = q_act  * x0q;
double NK_kill_x0q = kNK_kill * NK_base * x0q / (x0q + 1e3 + 1e-15);

dxdt_x0q = q_in - q_out - d0 * x0q - NK_kill_x0q;
dxdt_x0p = a0 * risk_mult * x0p + q_out - q_in - b0 * x0p - d0 * x0p
           - E_total_sens * x0p
           - kNK_kill * NK_base * x0p / (x0p + 1e3 + 1e-15)
           + mu * a0 * xs;
dxdt_x1  = lc1 * b0 * x0p - b1 * x1 - d1 * x1 - E_total_sens * x1 * 0.6;
dxdt_x2  = lc2 * b1 * x1 - b2 * x2 - d2 * x2 - E_total_sens * x2 * 0.8;
dxdt_x3  = lc3 * b2 * x2 - d3 * x3 - E_total_sens * x3
           - kNK_kill * NK_base * x3 / (x3 + 1e8 + 1e-15)
           - kCTL_kill * CTL_base * x3 / (x3 + 1e8 + 1e-15);

double TKI_kill_xs = E_total_sens * xs;
dxdt_xs  = as0 * xs - bs0 * xs - ds0 * xs - TKI_kill_xs - mu * as0 * xs;
dxdt_xsp = lc1 * bs0 * xs + asp * xsp - dsp * xsp - E_total_sens * xsp * 0.7;

dxdt_xr  = ar0 * xr - br0 * xr - dr0 * xr;
dxdt_xrp = lc1 * br0 * xr + arp * xrp - drp * xrp;

$TABLE
double CML_total = x3 + xrp + xsp;
double Norm_total = y3;
double BCRPCT = 100.0 * CML_total / fmax(CML_total + Norm_total, 1.0);
double LOG_IS = (BCRPCT > 0.0001) ? log10(BCRPCT) : -5.0;

capture BCRPCT = BCRPCT;
capture LOG_IS = LOG_IS;
capture CHR = (BCRPCT < 10.0) ? 1.0 : 0.0;
capture MMR = (BCRPCT < 0.1) ? 1.0 : 0.0;
capture MR4 = (BCRPCT < 0.01) ? 1.0 : 0.0;
capture MR45 = (BCRPCT < 0.0032) ? 1.0 : 0.0;
capture WBC_total = (x3 + Norm_total) / 5e9;
capture LSC_quies_frac = x0q / fmax(x0q + x0p + xs, 1.0);
capture Resist_frac = (xr + xrp) / fmax(CML_total, 1.0);
capture Cp_imt_out = Cp_imt;
capture Cic_imt_out = Cic_imt;
capture Cp_das_out = Cp_das;
capture Cic_das_out = Cic_das;
capture Cp_nil_out = Cp_nil;
capture Cic_nil_out = Cic_nil;
capture Cp_asc_out = Cp_asc;
capture x0q_out = x0q;
capture x0p_out = x0p;
capture x3_out = x3;
capture y3_out = y3;
capture xr_out = xr;
capture xs_out = xs;
'

# ============================================================
# Compile model (once at startup)
# ============================================================
mod <- mcode("cml_shiny", cml_model_code)

# ============================================================
# Helper functions
# ============================================================
to_months <- function(t_hr) t_hr / (365.25 * 24 / 12)

run_sim <- function(mod, drug, dose, years = 5, risk_mult = 1.0, oct1 = 1.0, mu_rate = 1e-8) {
  t_end <- years * 365.25 * 24
  dt    <- 24
  times <- seq(0, t_end, by = dt)

  dose_params <- list(dose_imt = 0, dose_das = 0, dose_nil = 0, dose_asc = 0,
                      risk_mult = risk_mult, OCT1_func = oct1, mu = mu_rate)
  dose_params[[paste0("dose_", drug)]] <- dose

  mod %>%
    param(dose_params) %>%
    mrgsim(end = t_end, delta = dt) %>%
    as.data.frame() %>%
    mutate(time_months = to_months(time))
}

sokal_score <- function(age, spleen_cm, plt, blast_pct) {
  # Sokal 1984 formula
  score <- exp(0.0116 * (age - 43.4) +
               0.0345 * (spleen_cm - 7.51) +
               0.188  * ((plt / 700)^2 - 0.563) +
               0.0887 * (blast_pct - 2.10))
  risk <- ifelse(score < 0.8, "Low", ifelse(score < 1.2, "Intermediate", "High"))
  list(score = round(score, 3), risk = risk)
}

eutos_score <- function(spleen_cm, baso_pct) {
  # EUTOS 2011 formula
  score <- 7 * baso_pct + 4 * spleen_cm
  risk  <- ifelse(score <= 87, "Low", "High")
  list(score = round(score, 1), risk = risk)
}

# ============================================================
# Drug metadata
# ============================================================
drug_info <- data.frame(
  drug        = c("imt", "das", "nil", "asc"),
  name        = c("Imatinib", "Dasatinib", "Nilotinib", "Asciminib"),
  generation  = c("1st Gen", "2nd Gen", "2nd Gen", "3rd Gen (STAMP)"),
  std_dose_mg = c(400, 100, 600, 80),
  label       = c("Imatinib 400mg/day", "Dasatinib 100mg/day",
                  "Nilotinib 300mg BID", "Asciminib 40mg BID"),
  color       = c("#377EB8", "#4DAF4A", "#984EA3", "#FF7F00"),
  stringsAsFactors = FALSE
)

# ============================================================
# UI
# ============================================================
ui <- dashboardPage(
  skin = "blue",

  dashboardHeader(
    title = "CML QSP Dashboard",
    titleWidth = 260
  ),

  dashboardSidebar(
    width = 260,
    sidebarMenu(
      menuItem("Patient profile",    tabName = "patient",  icon = icon("user-md")),
      menuItem("Pharmacokinetics",   tabName = "pk",       icon = icon("chart-line")),
      menuItem("Molecular response", tabName = "molecular", icon = icon("dna")),
      menuItem("Cell kinetics",      tabName = "cells",    icon = icon("microscope")),
      menuItem("Scenario comparison", tabName = "compare",  icon = icon("balance-scale")),
      menuItem("Resistance / TFR",   tabName = "resist",   icon = icon("shield-alt"))
    ),

    hr(),
    h4("Treatment settings", style = "color:white; margin-left:15px;"),

    selectInput("drug", "Select TKI:",
                choices = c("Imatinib (1st)" = "imt",
                            "Dasatinib (2nd)" = "das",
                            "Nilotinib (2nd)" = "nil",
                            "Asciminib (STAMP)" = "asc"),
                selected = "imt"),

    uiOutput("dose_ui"),

    sliderInput("sim_years", "Simulation duration (years):",
                min = 1, max = 10, value = 5, step = 1),

    sliderInput("risk_mult", "Rate of disease progression (reflecting Sokal):",
                min = 0.5, max = 2.0, value = 1.0, step = 0.1),

    sliderInput("oct1_func", "OCT1 activity (imatinib uptake):",
                min = 0.1, max = 2.0, value = 1.0, step = 0.1),

    actionButton("run_sim", "Run simulation",
                 class = "btn-primary btn-block",
                 style = "margin:10px 15px; width:230px;"),

    hr(),
    p("Calibrated to IRIS, ENESTnd,\nDASISION, ASCEMBL trials",
      style = "color:#aaa; margin-left:15px; font-size:11px;")
  ),

  dashboardBody(
    tags$head(
      tags$style(HTML("
        .content-wrapper { background-color: #f4f6f9; }
        .box-header { background-color: #3c8dbc !important; }
        .milestone-box { padding: 10px; border-radius: 5px; margin: 5px;
                         text-align: center; font-weight: bold; }
        .milestone-achieved { background-color: #dff0d8; color: #3c763d; }
        .milestone-pending  { background-color: #f2dede; color: #a94442; }
      "))
    ),

    tabItems(

      # --------------------------------------------------------
      # TAB 1: Patient Profile
      # --------------------------------------------------------
      tabItem(tabName = "patient",
        fluidRow(
          box(title = "Basic patient information", width = 6, status = "primary",
            numericInput("pt_age",   "Age (years):", 45, min = 18, max = 85),
            numericInput("pt_spleen","Spleen size (cm, below the costal margin):", 5, min = 0, max = 25),
            numericInput("pt_plt",   "Platelets (×10⁹/L):", 350, min = 50, max = 1500),
            numericInput("pt_blast", "Peripheral blood blasts (%):", 2, min = 0, max = 30),
            numericInput("pt_baso",  "Basophils (%):", 5, min = 0, max = 30),
            numericInput("pt_bcrabl","BCR-ABL IS% at diagnosis :", 80, min = 1, max = 100)
          ),

          box(title = "Risk score", width = 6, status = "info",
            actionButton("calc_score", "Calculate score", class = "btn-info btn-block"),
            hr(),
            h4("Sokal Score"),
            verbatimTextOutput("sokal_out"),
            h4("EUTOS Score"),
            verbatimTextOutput("eutos_out"),
            hr(),
            h4("ELN 2020 recommended treatment"),
            verbatimTextOutput("eln_rec"),
            hr(),
            h4("Summary of patient characteristics"),
            tableOutput("patient_summary")
          )
        ),

        fluidRow(
          box(title = "CML phase determination", width = 12, status = "warning",
            column(4,
              h4("Chronic phase (CP) criteria"),
              tags$ul(
                tags$li("Peripheral blood blasts < 10%"),
                tags$li("Marrow blasts < 10%"),
                tags$li("Ph chromosome positive"),
                tags$li("Symptoms: fatigue, splenomegaly, left upper quadrant pain")
              )
            ),
            column(4,
              h4("Accelerated phase (AP) criteria — EWI 2022"),
              tags$ul(
                tags$li("Blasts 10–19% (peripheral blood or marrow)"),
                tags$li("Basophils ≥ 20%"),
                tags$li("Platelets < 100×10⁹/L (unrelated to treatment)"),
                tags$li("Rising Ph+ cells on treatment")
              )
            ),
            column(4,
              h4("Blast crisis (BC) criteria"),
              tags$ul(
                tags$li("Blasts ≥ 20% (peripheral blood or marrow)"),
                tags$li("Extramedullary blast proliferation"),
                tags$li("Large blast clusters on marrow biopsy")
              )
            )
          )
        )
      ),

      # --------------------------------------------------------
      # TAB 2: PK Profiles
      # --------------------------------------------------------
      tabItem(tabName = "pk",
        fluidRow(
          box(title = "TKI plasma concentration", width = 12,
              status = "primary", solidHeader = TRUE,
            plotlyOutput("pk_plasma_plot", height = "350px")
          )
        ),
        fluidRow(
          box(title = "Intracellular concentration", width = 8,
              status = "info",
            plotlyOutput("pk_ic_plot", height = "300px")
          ),
          box(title = "PK parameters", width = 4, status = "success",
            tableOutput("pk_params_table")
          )
        ),
        fluidRow(
          box(title = "Summary of pharmacokinetic measures", width = 12, status = "warning",
            tableOutput("pk_summary_table")
          )
        )
      ),

      # --------------------------------------------------------
      # TAB 3: Molecular Response
      # --------------------------------------------------------
      tabItem(tabName = "molecular",
        fluidRow(
          valueBoxOutput("vbox_CHR",  width = 3),
          valueBoxOutput("vbox_CCyR", width = 3),
          valueBoxOutput("vbox_MMR",  width = 3),
          valueBoxOutput("vbox_MR45", width = 3)
        ),
        fluidRow(
          box(title = "BCR-ABL IS% over time (molecular response profile)", width = 8,
              status = "primary", solidHeader = TRUE,
            plotlyOutput("bcrabl_plot", height = "400px")
          ),
          box(title = "ELN 2020 response checklist", width = 4,
              status = "success",
            h4("3-month assessment"),
            uiOutput("milestone_3mo"),
            h4("6-month assessment"),
            uiOutput("milestone_6mo"),
            h4("12-month assessment"),
            uiOutput("milestone_12mo"),
            h4("18 months onwards"),
            uiOutput("milestone_18mo")
          )
        ),
        fluidRow(
          box(title = "Time to molecular response (months)", width = 12, status = "info",
            tableOutput("response_time_table")
          )
        )
      ),

      # --------------------------------------------------------
      # TAB 4: Cell Kinetics
      # --------------------------------------------------------
      tabItem(tabName = "cells",
        fluidRow(
          box(title = "Leukaemic cell population kinetics", width = 8,
              status = "primary", solidHeader = TRUE,
            plotlyOutput("leuk_cells_plot", height = "400px")
          ),
          box(title = "Normal haematopoietic cells", width = 4, status = "success",
            plotlyOutput("normal_cells_plot", height = "400px")
          )
        ),
        fluidRow(
          box(title = "LSC kinetics — quiescent vs proliferating", width = 6,
              status = "warning",
            plotlyOutput("lsc_plot", height = "300px")
          ),
          box(title = "Sensitive / resistant clone kinetics", width = 6,
              status = "danger",
            plotlyOutput("clone_plot", height = "300px")
          )
        )
      ),

      # --------------------------------------------------------
      # TAB 5: Scenario Comparison
      # --------------------------------------------------------
      tabItem(tabName = "compare",
        fluidRow(
          box(title = "Select the drugs to compare", width = 12, status = "primary",
            checkboxGroupInput("compare_drugs",
                               "TKIs to compare (multiple selection):",
                               choices = c("Imatinib 400mg" = "imt",
                                           "Dasatinib 100mg" = "das",
                                           "Nilotinib 300mg BID" = "nil",
                                           "Asciminib 40mg BID" = "asc"),
                               selected = c("imt", "das", "nil"),
                               inline = TRUE),
            actionButton("run_compare", "Run comparison simulation",
                         class = "btn-warning btn-block")
          )
        ),
        fluidRow(
          box(title = "BCR-ABL IS% comparison (whole period)", width = 12,
              status = "primary", solidHeader = TRUE,
            plotlyOutput("compare_plot", height = "450px")
          )
        ),
        fluidRow(
          box(title = "MMR/MR4/MR4.5 attainment compared (simulation-based)", width = 12,
              status = "info",
            tableOutput("compare_milestone_table")
          )
        )
      ),

      # --------------------------------------------------------
      # TAB 6: Resistance & TFR
      # --------------------------------------------------------
      tabItem(tabName = "resist",
        fluidRow(
          box(title = "T315I resistant clone kinetics", width = 8,
              status = "danger", solidHeader = TRUE,
            plotlyOutput("resist_plot", height = "350px")
          ),
          box(title = "Resistance assessment parameters", width = 4, status = "warning",
            sliderInput("mu_rate_exp", "Mutation rate (log10):",
                        min = -10, max = -5, value = -8, step = 0.5),
            sliderInput("tfr_threshold", "TFR entry criterion (MR):",
                        min = 3, max = 4.5, value = 4.0, step = 0.5),
            sliderInput("tfr_duration_yr", "Duration on treatment before TFR (years):",
                        min = 1, max = 5, value = 2, step = 0.5),
            actionButton("run_tfr", "Run TFR simulation",
                         class = "btn-danger btn-block")
          )
        ),
        fluidRow(
          box(title = "Predicted TFR success (BCR-ABL IS% after stopping the TKI)", width = 8,
              status = "primary",
            plotlyOutput("tfr_plot", height = "350px")
          ),
          box(title = "Predictors of TFR success", width = 4, status = "success",
            h4("Favourable predictors"),
            tags$ul(
              tags$li("MR4.5 sustained ≥ 2 years"),
              tags$li("High NK cell activity"),
              tags$li("Treatment duration ≥ 5 years"),
              tags$li("ENESTfreedom: second-generation TKI")
            ),
            hr(),
            h4("Unfavourable predictors"),
            tags$ul(
              tags$li("High Sokal risk group"),
              tags$li("Prior AP/BC phase"),
              tags$li("Short duration of DMR"),
              tags$li("Residual quiescent LSC clone")
            ),
            hr(),
            verbatimTextOutput("tfr_probability")
          )
        ),
        fluidRow(
          box(title = "TKI resistance profile by mutation", width = 12, status = "info",
            tableOutput("mutation_table")
          )
        )
      )
    )  # end tabItems
  )  # end dashboardBody
)  # end dashboardPage

# ============================================================
# SERVER
# ============================================================
server <- function(input, output, session) {

  # Reactive simulation result
  sim_result <- eventReactive(input$run_sim, {
    withProgress(message = "Running simulation...", {
      drug <- input$drug
      dose_val <- switch(drug,
                         imt = input$dose_imt %||% 400,
                         das = input$dose_das %||% 100,
                         nil = input$dose_nil %||% 600,
                         asc = input$dose_asc %||% 80)

      dose_params <- list(dose_imt = 0, dose_das = 0,
                          dose_nil = 0, dose_asc = 0,
                          risk_mult = input$risk_mult,
                          OCT1_func = input$oct1_func,
                          mu        = 1e-8)
      dose_params[[paste0("dose_", drug)]] <- dose_val

      t_end <- input$sim_years * 365.25 * 24
      mod %>%
        param(dose_params) %>%
        mrgsim(end = t_end, delta = 24) %>%
        as.data.frame() %>%
        mutate(time_months = to_months(time))
    })
  }, ignoreNULL = FALSE)

  # Initial simulation on load (imatinib default)
  observe({
    input$run_sim
  })

  # Dynamic dose UI
  output$dose_ui <- renderUI({
    drug <- input$drug
    switch(drug,
      imt = sliderInput("dose_imt", "Imatinib dose (mg/day):",
                        min = 200, max = 800, value = 400, step = 100),
      das = sliderInput("dose_das", "Dasatinib dose (mg/day):",
                        min = 50, max = 140, value = 100, step = 10),
      nil = sliderInput("dose_nil", "Nilotinib dose (mg/day):",
                        min = 300, max = 900, value = 600, step = 150),
      asc = sliderInput("dose_asc", "Asciminib dose (mg/day):",
                        min = 40, max = 400, value = 80, step = 40)
    )
  })

  # --------------------------------------------------------
  # TAB 1: Patient Profile
  # --------------------------------------------------------
  output$sokal_out <- renderPrint({
    req(input$calc_score)
    s <- sokal_score(input$pt_age, input$pt_spleen, input$pt_plt, input$pt_blast)
    cat("Sokal score:", s$score, "\nRisk group:", s$risk, "\n")
  })

  output$eutos_out <- renderPrint({
    req(input$calc_score)
    e <- eutos_score(input$pt_spleen, input$pt_baso)
    cat("EUTOS score:", e$score, "\nRisk group:", e$risk, "\n")
  })

  output$eln_rec <- renderPrint({
    req(input$calc_score)
    s <- sokal_score(input$pt_age, input$pt_spleen, input$pt_plt, input$pt_blast)
    if (s$risk == "Low") {
      cat("Recommended: imatinib 400mg or a second-generation TKI\n(TFR is an attainable goal)")
    } else if (s$risk == "Intermediate") {
      cat("Recommended: second-generation TKI (dasatinib/nilotinib)\n(aim for an early deep molecular response)")
    } else {
      cat("Recommended: second-generation TKI or consider ponatinib\n(close monitoring required)")
    }
  })

  output$patient_summary <- renderTable({
    data.frame(
      Item = c("Age", "Spleen size", "Platelets", "Blasts", "BCR-ABL at diagnosis"),
      Value = c(paste0(input$pt_age, " years"),
               paste0(input$pt_spleen, " cm"),
               paste0(input$pt_plt, " ×10⁹/L"),
               paste0(input$pt_blast, "%"),
               paste0(input$pt_bcrabl, "% IS"))
    )
  })

  # --------------------------------------------------------
  # TAB 2: PK Profiles
  # --------------------------------------------------------
  output$pk_plasma_plot <- renderPlotly({
    df <- sim_result()
    req(df)
    drug <- input$drug

    pk_col <- switch(drug,
                     imt = "Cp_imt_out", das = "Cp_das_out",
                     nil = "Cp_nil_out", asc = "Cp_asc_out")

    df_pk <- df %>% filter(time_months <= 1) %>%
      mutate(time_h = time_months * 30 * 24,
             Cp = .data[[pk_col]])

    p <- ggplot(df_pk, aes(x = time_h, y = Cp)) +
      geom_line(color = "#377EB8", size = 1.2) +
      labs(title = paste("Plasma concentration:", drug_info$name[drug_info$drug == drug]),
           x = "Time (h)", y = "Concentration (µM)") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$pk_ic_plot <- renderPlotly({
    df <- sim_result()
    req(df)
    drug <- input$drug

    ic_col <- switch(drug,
                     imt = "Cic_imt_out", das = "Cic_das_out",
                     nil = "Cic_nil_out", asc = "Cp_asc_out")

    df_ic <- df %>% filter(time_months <= 3) %>%
      mutate(time_h = time_months * 30 * 24,
             Cic = .data[[ic_col]])

    p <- ggplot(df_ic, aes(x = time_h, y = Cic)) +
      geom_line(color = "#E41A1C", size = 1.2) +
      labs(title = "Intracellular concentration",
           x = "Time (h)", y = "Concentration (µM)") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$pk_params_table <- renderTable({
    drug <- input$drug
    info <- drug_info[drug_info$drug == drug, ]
    data.frame(
      Parameter = c("Drug", "Generation", "Standard dose", "Bioavailability", "Half-life"),
      Value = c(info$name, info$generation, info$label,
             switch(drug, imt="98%", das="24%", nil="35%", asc="72%"),
             switch(drug, imt="18h", das="5-6h", nil="17h", asc="8.7h"))
    )
  })

  output$pk_summary_table <- renderTable({
    drug <- input$drug
    data.frame(
      TKI      = c("Imatinib", "Dasatinib", "Nilotinib", "Asciminib"),
      Dose     = c("400mg/day", "100mg/day", "300mg BID", "40mg BID"),
      IC50_µM  = c("0.25", "0.025", "0.020", "0.0005"),
      Bioavailability = c("98%", "14-34%", "30-40%", "~72%"),
      t1_2     = c("18h", "5-6h", "17h", "8.7h"),
      Main_action = c("DFG-out", "DFG-in (Src)", "DFG-in", "STAMP/myristoyl"),
      T315I    = c("Resistant", "Resistant", "Resistant", "Partly sensitive\n(200mg BID)")
    )
  })

  # --------------------------------------------------------
  # TAB 3: Molecular Response
  # --------------------------------------------------------
  output$bcrabl_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    # Reference lines data
    milestones <- data.frame(
      y    = c(0.1, 0.01, 0.0032, 10),
      label = c("MMR (0.1%)", "MR4 (0.01%)", "MR4.5 (0.0032%)", "CHR (<10%)"),
      color = c("blue", "purple", "darkgreen", "orange")
    )

    p <- ggplot(df, aes(x = time_months, y = BCRPCT)) +
      geom_line(color = "#E41A1C", size = 1.4) +
      scale_y_log10(
        breaks = c(100, 10, 1, 0.1, 0.01, 0.001),
        labels = c("100%", "10%", "1%", "0.1%", "0.01%", "0.001%")
      ) +
      geom_hline(yintercept = 0.1,    linetype = "dashed", color = "blue",      size = 0.8) +
      geom_hline(yintercept = 0.01,   linetype = "dashed", color = "purple",    size = 0.8) +
      geom_hline(yintercept = 0.0032, linetype = "dashed", color = "darkgreen", size = 0.8) +
      geom_hline(yintercept = 10,     linetype = "dashed", color = "orange",    size = 0.8) +
      geom_vline(xintercept = c(3, 6, 12, 18, 24, 36, 48),
                 linetype = "dotted", alpha = 0.5) +
      annotate("text", x = max(df$time_months) * 0.6, y = 0.12,
               label = "MMR", color = "blue", size = 3.5) +
      annotate("text", x = max(df$time_months) * 0.6, y = 0.012,
               label = "MR4", color = "purple", size = 3.5) +
      annotate("text", x = max(df$time_months) * 0.6, y = 0.004,
               label = "MR4.5", color = "darkgreen", size = 3.5) +
      labs(
        title = "BCR-ABL IS% — the molecular response profile",
        x = "Treatment duration (months)", y = "BCR-ABL IS% (log scale)"
      ) +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  # Response milestones
  get_milestone_time <- function(df, threshold) {
    idx <- which(df$BCRPCT <= threshold)[1]
    if (is.na(idx)) return(NA) else return(df$time_months[idx])
  }

  output$vbox_CHR <- renderValueBox({
    df <- sim_result()
    t  <- get_milestone_time(df, 10)
    valueBox(
      value = if (is.na(t)) "Not reached" else paste0(round(t, 0), " months"),
      subtitle = "CHR achieved (IS% <10%)",
      icon  = icon("check-circle"),
      color = if (is.na(t)) "red" else "green"
    )
  })

  output$vbox_CCyR <- renderValueBox({
    df <- sim_result()
    t  <- get_milestone_time(df, 1)
    valueBox(
      value = if (is.na(t)) "Not reached" else paste0(round(t, 0), " months"),
      subtitle = "CCyR (IS% <1%)",
      icon  = icon("check-circle"),
      color = if (is.na(t)) "red" else "blue"
    )
  })

  output$vbox_MMR <- renderValueBox({
    df <- sim_result()
    t  <- get_milestone_time(df, 0.1)
    valueBox(
      value = if (is.na(t)) "Not reached" else paste0(round(t, 0), " months"),
      subtitle = "MMR achieved (IS% ≤0.1%)",
      icon  = icon("star"),
      color = if (is.na(t)) "orange" else "purple"
    )
  })

  output$vbox_MR45 <- renderValueBox({
    df <- sim_result()
    t  <- get_milestone_time(df, 0.0032)
    valueBox(
      value = if (is.na(t)) "Not reached" else paste0(round(t, 0), " months"),
      subtitle = "MR4.5 (TFR criterion)",
      icon  = icon("trophy"),
      color = if (is.na(t)) "orange" else "yellow"
    )
  })

  milestone_status_ui <- function(achieved, label, detail) {
    cls <- if (achieved) "milestone-achieved" else "milestone-pending"
    icon_txt <- if (achieved) "✓" else "✗"
    div(class = paste("milestone-box", cls),
        paste(icon_txt, label, "|", detail))
  }

  output$milestone_3mo <- renderUI({
    df <- sim_result()
    val_3 <- df$BCRPCT[df$time_months >= 3][1]
    tagList(
      milestone_status_ui(!is.na(val_3) && val_3 < 10,
                          "BCR-ABL <10%", paste0(round(val_3, 2), "%")),
      milestone_status_ui(!is.na(val_3) && val_3 < 1,
                          "BCR-ABL <1%", "(optimal response)")
    )
  })

  output$milestone_6mo <- renderUI({
    df <- sim_result()
    val_6 <- df$BCRPCT[df$time_months >= 6][1]
    tagList(
      milestone_status_ui(!is.na(val_6) && val_6 < 10,
                          "BCR-ABL <10%", paste0(round(val_6, 2), "%")),
      milestone_status_ui(!is.na(val_6) && val_6 < 1,
                          "BCR-ABL <1%", "heading for CCyR")
    )
  })

  output$milestone_12mo <- renderUI({
    df <- sim_result()
    val_12 <- df$BCRPCT[df$time_months >= 12][1]
    tagList(
      milestone_status_ui(!is.na(val_12) && val_12 < 1,
                          "CCyR (BCR-ABL <1%)", paste0(round(val_12, 3), "%")),
      milestone_status_ui(!is.na(val_12) && val_12 < 0.1,
                          "MMR (BCR-ABL ≤0.1%)", "achieved early, by 12 months")
    )
  })

  output$milestone_18mo <- renderUI({
    df <- sim_result()
    val_18 <- df$BCRPCT[df$time_months >= 18][1]
    tagList(
      milestone_status_ui(!is.na(val_18) && val_18 < 0.1,
                          "MMR maintained", paste0(round(val_18, 4), "%")),
      milestone_status_ui(!is.na(val_18) && val_18 < 0.01,
                          "MR4 achieved", "Deep remission")
    )
  })

  output$response_time_table <- renderTable({
    df <- sim_result()
    data.frame(
      Response   = c("CHR (IS% <10%)", "CCyR (IS% <1%)", "MMR (IS% ≤0.1%)",
                     "MR4 (IS% ≤0.01%)", "MR4.5 (IS% ≤0.0032%)"),
      Threshold  = c("10%", "1%", "0.1%", "0.01%", "0.0032%"),
      Months_to_achieve  = c(
        ifelse(is.na(get_milestone_time(df, 10)),    "Not reached", paste0(round(get_milestone_time(df, 10), 0), " months")),
        ifelse(is.na(get_milestone_time(df, 1)),     "Not reached", paste0(round(get_milestone_time(df, 1),  0), " months")),
        ifelse(is.na(get_milestone_time(df, 0.1)),   "Not reached", paste0(round(get_milestone_time(df, 0.1),0), " months")),
        ifelse(is.na(get_milestone_time(df, 0.01)),  "Not reached", paste0(round(get_milestone_time(df, 0.01), 0), " months")),
        ifelse(is.na(get_milestone_time(df, 0.0032)),"Not reached", paste0(round(get_milestone_time(df, 0.0032), 0), " months"))
      ),
      ELN_2020_criterion = c("Recommended by 3 months", "Optimal by 12 months", "Target by 18 months", "Deep response", "Prerequisite for TFR")
    )
  })

  # --------------------------------------------------------
  # TAB 4: Cell Kinetics
  # --------------------------------------------------------
  output$leuk_cells_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    df_cells <- df %>%
      select(time_months, x0q_out, x0p_out, x1, x2, x3_out) %>%
      pivot_longer(-time_months, names_to = "pop", values_to = "count") %>%
      mutate(
        population = case_when(
          pop == "x0q_out" ~ "LSC quiescent (x0q)",
          pop == "x0p_out" ~ "LSC proliferating (x0p)",
          pop == "x1"      ~ "LPC1 (x1)",
          pop == "x2"      ~ "LPC2 (x2)",
          pop == "x3_out"  ~ "Leukaemic WBC (x3)"
        ),
        count = pmax(count, 1)
      )

    p <- ggplot(df_cells, aes(x = time_months, y = count,
                              color = population)) +
      geom_line(size = 1.1) +
      scale_y_log10() +
      scale_color_brewer(palette = "Set1") +
      labs(title = "CML cell population kinetics (log scale)",
           x = "Time (months)", y = "Cell number (log10)",
           color = "Cell population") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$normal_cells_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    df_norm <- df %>%
      select(time_months, y0, y1, y2, y3_out) %>%
      pivot_longer(-time_months, names_to = "pop", values_to = "count") %>%
      mutate(
        population = case_when(
          pop == "y0"     ~ "HSC (y0)",
          pop == "y1"     ~ "CMP (y1)",
          pop == "y2"     ~ "GMP (y2)",
          pop == "y3_out" ~ "Normal WBC (y3)"
        ),
        count = pmax(count, 1)
      )

    p <- ggplot(df_norm, aes(x = time_months, y = count, color = population)) +
      geom_line(size = 1.1) +
      scale_y_log10() +
      scale_color_brewer(palette = "Set2") +
      labs(title = "Normal haematopoietic cells",
           x = "Time (months)", y = "Cell number (log10)",
           color = "Cell population") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$lsc_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    p <- ggplot(df, aes(x = time_months)) +
      geom_line(aes(y = x0q_out, color = "LSC quiescent"), size = 1.1) +
      geom_line(aes(y = x0p_out, color = "LSC proliferating"), size = 1.1) +
      geom_line(aes(y = LSC_quies_frac * 1e5, color = "Quiescent fraction (×10⁵)"),
                size = 1.0, linetype = "dashed") +
      scale_y_log10() +
      scale_color_manual(values = c("LSC quiescent" = "#E41A1C",
                                    "LSC proliferating" = "#377EB8",
                                    "Quiescent fraction (×10⁵)" = "#4DAF4A")) +
      labs(title = "LSC quiescent / proliferating kinetics",
           x = "Time (months)", y = "Cell number (log10)",
           color = "") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$clone_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    p <- ggplot(df, aes(x = time_months)) +
      geom_line(aes(y = xs_out + 1, color = "Sensitive LSC clone (xs)"), size = 1.1) +
      geom_line(aes(y = xr_out + 1, color = "T315I resistant clone (xr)"), size = 1.1) +
      scale_y_log10() +
      scale_color_manual(values = c("Sensitive LSC clone (xs)" = "#4DAF4A",
                                    "T315I resistant clone (xr)" = "#E41A1C")) +
      labs(title = "Sensitive / resistant clone kinetics",
           x = "Time (months)", y = "Cell number (log10)",
           color = "") +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  # --------------------------------------------------------
  # TAB 5: Scenario Comparison
  # --------------------------------------------------------
  compare_result <- eventReactive(input$run_compare, {
    withProgress(message = "Running comparison simulation...", {
      drugs <- input$compare_drugs
      doses <- c(imt = 400, das = 100, nil = 600, asc = 80)

      results <- lapply(drugs, function(d) {
        dose_params <- list(dose_imt = 0, dose_das = 0,
                            dose_nil = 0, dose_asc = 0,
                            risk_mult = input$risk_mult,
                            OCT1_func = input$oct1_func)
        dose_params[[paste0("dose_", d)]] <- doses[d]

        t_end <- input$sim_years * 365.25 * 24
        mod %>%
          param(dose_params) %>%
          mrgsim(end = t_end, delta = 24) %>%
          as.data.frame() %>%
          mutate(time_months = to_months(time),
                 drug_label  = drug_info$label[drug_info$drug == d])
      })
      bind_rows(results)
    })
  })

  output$compare_plot <- renderPlotly({
    df <- compare_result()
    req(df)

    colors <- setNames(drug_info$color, drug_info$label)

    p <- ggplot(df, aes(x = time_months, y = BCRPCT,
                        color = drug_label)) +
      geom_line(size = 1.2) +
      scale_y_log10(
        breaks = c(100, 10, 1, 0.1, 0.01, 0.001),
        labels = c("100%", "10%", "1%", "MMR 0.1%", "MR4 0.01%", "MR4.5 0.001%")
      ) +
      geom_hline(yintercept = c(0.1, 0.01, 0.0032),
                 linetype = "dashed", alpha = 0.6) +
      scale_color_manual(values = colors, na.value = "#999999") +
      labs(
        title = "TKI scenarios compared — BCR-ABL IS%",
        subtitle = "Molecular response against the ELN 2020 criteria",
        x = "Treatment duration (months)", y = "BCR-ABL IS% (log scale)",
        color = "Treatment"
      ) +
      theme_bw(base_size = 12) +
      theme(legend.position = "right")
    ggplotly(p)
  })

  output$compare_milestone_table <- renderTable({
    df <- compare_result()
    req(df)

    thresholds <- c(CHR = 10, CCyR = 1, MMR = 0.1, MR4 = 0.01, MR45 = 0.0032)
    drugs_sel  <- unique(df$drug_label)

    rows <- lapply(drugs_sel, function(d) {
      sub_df <- df[df$drug_label == d, ]
      times  <- sapply(thresholds, function(thr) {
        idx <- which(sub_df$BCRPCT <= thr)[1]
        if (is.na(idx)) "Not reached" else paste0(round(sub_df$time_months[idx], 0), " months")
      })
      c(TKI = d, times)
    })

    do.call(rbind, lapply(rows, as.data.frame, stringsAsFactors = FALSE))
  })

  # --------------------------------------------------------
  # TAB 6: Resistance & TFR
  # --------------------------------------------------------
  output$resist_plot <- renderPlotly({
    df <- sim_result()
    req(df)

    mu_rate <- 10^input$mu_rate_exp

    dose_params <- list(dose_imt = 400, dose_das = 0,
                        dose_nil = 0, dose_asc = 0,
                        mu = mu_rate,
                        risk_mult = input$risk_mult)

    t_end <- input$sim_years * 365.25 * 24
    df_r  <- mod %>%
      param(dose_params) %>%
      mrgsim(end = t_end, delta = 24) %>%
      as.data.frame() %>%
      mutate(time_months = to_months(time))

    p <- ggplot(df_r, aes(x = time_months)) +
      geom_line(aes(y = BCRPCT, color = "BCR-ABL IS% (total)"), size = 1.2) +
      geom_line(aes(y = Resist_frac * 100, color = "T315I clone fraction (%)"),
                size = 1.1, linetype = "dashed") +
      scale_y_log10() +
      scale_color_manual(values = c("BCR-ABL IS% (total)" = "#E41A1C",
                                    "T315I clone fraction (%)" = "#9966CC")) +
      geom_hline(yintercept = 0.1, linetype = "dashed", color = "blue", alpha = 0.7) +
      labs(
        title = paste0("Emergence of T315I resistance on imatinib\n(mutation rate: 10^", input$mu_rate_exp, ")"),
        x = "Treatment duration (months)",
        y = "% (log scale)", color = ""
      ) +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  tfr_result <- eventReactive(input$run_tfr, {
    withProgress(message = "Running TFR simulation...", {
      drug   <- input$drug
      doses  <- c(imt = 400, das = 100, nil = 600, asc = 80)
      t_pre  <- input$tfr_duration_yr * 365.25 * 24  # pre-TFR treatment
      t_post <- 3 * 365.25 * 24   # 3 years post-TFR

      dose_params <- list(dose_imt = 0, dose_das = 0,
                          dose_nil = 0, dose_asc = 0,
                          risk_mult = input$risk_mult)
      dose_params[[paste0("dose_", drug)]] <- doses[drug]

      # Pre-TFR phase
      pre_df <- mod %>%
        param(dose_params) %>%
        mrgsim(end = t_pre, delta = 24) %>%
        as.data.frame()

      # Extract end-state
      es <- tail(pre_df, 1)
      init_off <- c(
        y0 = es$y0, y1 = es$y1, y2 = es$y2, y3 = es$y3,
        x0q = es$x0q, x0p = es$x0p, x1 = es$x1, x2 = es$x2, x3 = es$x3,
        xs = es$xs, xsp = es$xsp, xr = es$xr, xrp = es$xrp,
        Gut_imt = 0, Cp_imt = 0, Cic_imt = 0,
        Cp_das = 0, Cic_das = 0,
        Gut_nil = 0, Cp_nil = 0, Cic_nil = 0,
        Gut_asc = 0, Cp_asc = 0
      )

      # Post-TFR (off treatment)
      post_df <- mod %>%
        param(dose_imt = 0, dose_das = 0, dose_nil = 0, dose_asc = 0,
              risk_mult = input$risk_mult) %>%
        init(init_off) %>%
        mrgsim(end = t_post, delta = 24) %>%
        as.data.frame() %>%
        mutate(time_months = to_months(time) + input$tfr_duration_yr * 12)

      pre_df2 <- pre_df %>%
        mutate(time_months = to_months(time),
               phase = "On TKI")
      post_df$phase <- "TFR (drug stopped)"

      list(
        combined = bind_rows(pre_df2, post_df),
        pre_IS = tail(pre_df$BCRPCT, 1),
        post_6mo_IS = post_df$BCRPCT[post_df$time_months >= input$tfr_duration_yr * 12 + 6][1]
      )
    })
  })

  output$tfr_plot <- renderPlotly({
    res <- tfr_result()
    req(res)

    vline_x <- input$tfr_duration_yr * 12

    p <- ggplot(res$combined, aes(x = time_months, y = BCRPCT + 0.0001, color = phase)) +
      geom_line(size = 1.3) +
      scale_y_log10(
        breaks = c(100, 10, 1, 0.1, 0.01, 0.001, 0.0001),
        labels = c("100%", "10%", "1%", "0.1%", "0.01%", "0.001%", "0.0001%")
      ) +
      geom_vline(xintercept = vline_x, linetype = "longdash",
                 color = "red", size = 1.2) +
      geom_hline(yintercept = 0.1, linetype = "dashed", color = "blue", alpha = 0.7) +
      annotate("text", x = vline_x + 1, y = 50, label = "TKI stopped",
               color = "red", hjust = 0, size = 4) +
      scale_color_manual(values = c("On TKI" = "#377EB8",
                                    "TFR (drug stopped)" = "#E41A1C")) +
      labs(
        title = "TFR simulation — BCR-ABL IS% after stopping the TKI",
        x = "Time (months)", y = "BCR-ABL IS% (log scale)", color = ""
      ) +
      theme_bw(base_size = 12)
    ggplotly(p)
  })

  output$tfr_probability <- renderPrint({
    res <- tfr_result()
    req(res)

    pre_IS    <- res$pre_IS
    post_6mo  <- res$post_6mo_IS

    cat("=== TFR simulation result ===\n")
    cat("BCR-ABL IS% at the time the TKI is stopped:", round(pre_IS, 5), "%\n")
    if (!is.na(post_6mo)) {
      cat("BCR-ABL IS% 6 months after stopping:", round(post_6mo, 4), "%\n")
      if (post_6mo < 0.1) {
        cat("Prediction: TFR maintained (molecular remission sustained)\n")
        cat("Estimated probability of success: ~45-55%\n")
      } else {
        cat("Prediction: molecular relapse (loss of MMR)\n")
        cat("Recommendation on retreatment: restart the previous TKI\n")
        cat("Response rate on retreatment: >90%\n")
      }
    }
    cat("\nClinical evidence (EURO-SKI):\n")
    cat("  - MR4.5 sustained ≥ 2 years: TFR success 43-50%\n")
    cat("  - First-generation TKI (STIM): 38%\n")
    cat("  - Second-generation TKI (ENESTfreedom): 51%\n")
    cat("  - The higher the NK activity, the higher the success rate ↑\n")
  })

  output$mutation_table <- renderTable({
    data.frame(
      Mutation   = c("T315I (gatekeeper)", "E255K (P-loop)", "Y253H (P-loop)",
                     "F317L (SH2 contact)", "T315A", "E459K (myristoyl pocket)"),
      Position   = c("315", "255", "253", "317", "315", "459"),
      Imatinib   = c("Resistant", "Resistant", "Resistant", "Sensitive", "Resistant", "Sensitive"),
      Dasatinib  = c("Resistant", "Resistant", "Resistant", "Resistant", "Sensitive", "Sensitive"),
      Nilotinib  = c("Resistant", "Resistant", "Resistant", "Sensitive", "Sensitive", "Sensitive"),
      Ponatinib  = c("Sensitive", "Sensitive", "Sensitive", "Sensitive", "Sensitive", "Sensitive"),
      Asciminib_40mg  = c("Resistant", "Sensitive", "Sensitive", "Sensitive", "Sensitive", "Resistant"),
      Asciminib_200mg = c("Sensitive", "Sensitive", "Sensitive", "Sensitive", "Sensitive", "Resistant"),
      Frequency  = c("~15%", "~7%", "~7%", "~5%", "~3%", "~2%")
    )
  })

}  # end server

# ============================================================
# Null-coalescing helper
# ============================================================
`%||%` <- function(a, b) if (is.null(a)) b else a

# ============================================================
# Run the app
# ============================================================
shinyApp(ui = ui, server = server)
