################################################################################
## Sarcoidosis QSP Model — mrgsolve ODE Implementation
## File: sarc_mrgsolve_model.R
##
## Disease: Sarcoidosis (pulmonary + systemic)
## Model scope:
##   - Drug PK:  Prednisone/Prednisolone, Methotrexate (MTX + polyglutamates),
##               Azathioprine (AZA, simplified steady-state TGN),
##               Hydroxychloroquine (HCQ, simplified steady-state),
##               Infliximab (IFX, simplified 1-compartment IV)
##   - Disease PD: macrophage activation → granuloma formation → fibrosis
##                 + biomarkers (ACE, calcitriol, calcium, sIL-2R, FVC)
##
## 20 ODE compartments total (7 PK + 13 PD)
##
## Key clinical references used for parameter calibration:
##   - Baughman et al. (2006) FIRST trial  — prednisone vs. infliximab for
##     pulmonary sarcoidosis (Chest 130:1119-1126)
##   - Gibson et al. (1996) — ACE 25 trial, prednisone in pulmonary sarcoidosis
##     (Eur Respir J 9:2115-2122)
##   - Judson et al. (2000) — ACCESS cohort (Am J Respir Crit Care Med 161:1785)
##   - Paramothayan & Jones (2002) Cochrane — corticosteroids for pulmonary sarc
##   - Vorselaars et al. (2015) — MTX vs AZA for pulmonary sarcoidosis
##     (Eur Respir J 46:1426-1435)
##   - Baughman et al. (2012) — Infliximab for chronic pulmonary sarcoidosis
##     (Respir Med 106:897-903)
##   - Ogura et al. (2014) — HCQ for hypercalcemia in sarcoidosis
##   - Prednisone PK: Derendorf et al. (1985) Clin Pharmacol Ther 37:502-507
##   - Prednisolone PK: Czock et al. (2005) Clin Pharmacokinet 44:811-827
##   - MTX PK: Bressolle et al. (1998) J Clin Pharmacol 38:458-469
##   - MTX polyglutamate PK: Kager et al. (2014) Cancer Res 74:5140-5152
##
## Author: Generated by Claude Code Routine (CCR) — 2026-06-17
## License: MIT
################################################################################

# =============================================================================
# PK/PD REFACTOR (fork sibling; original sarc_mrgsolve_model.R untouched)
# =============================================================================
#  Scope: PREDNISONE (PRED), PREDNISOLONE (PREDL), and METHOTREXATE (MTX)
#  only -- their PK blocks and their downstream effect equations.
#  Azathioprine (AZA), hydroxychloroquine (HCQ), and infliximab (IFX) --
#  all modeled in the original as constant steady-state concentration
#  placeholders (*_CSS params), not real PK compartments -- are completely
#  untouched: same params, same Eaza/Ehcq/Eifx formulas, same combination
#  structure. All 13 disease-PD compartments and their kinetics are also
#  untouched, except for a build-compatibility rename described below.
#
#  PARENT-METABOLITE LINK (read the code before assuming PRED/PREDL are
#  independent): PREDL is prednisone's own active metabolite, not a
#  second independently-dosed compound -- the original's own header already
#  says so ("Prednisone (prodrug) --> Prednisolone (active)"), and the code
#  confirms it: PREDL has no GUT_/depot compartment or KA_/F_ absorption
#  params of its own; its only inflow is a conversion term computed from
#  PRED's own plasma concentration (`k_predl_conv * CL_pred * pred_conc_ug_mL
#  * Vc_predl_ode / 1000.0` in the original, renamed `CONV_PRED_TO_PREDL` in
#  $ODE below). Handled here as a genuine parent-metabolite chain: PRED
#  keeps its own PK block and its own C_PRED (used only to drive the
#  conversion, since prednisone has no direct PD effect in the original);
#  PREDL keeps its own PK block, fed by that conversion, and exposes the
#  single C_PREDL/EFFECT_PREDL pair the disease equations actually read.
#
#  Archetypes:
#    - PRED: Archetype 3 minus the peripheral compartment (depot + central,
#      linear elimination, no bioavailability factor -- none in the
#      original either).
#    - PREDL: Archetype 2 (2-compartment, linear, CL/Q/V), fed by the
#      conversion inflow above. The original's k12_predl/k21_predl
#      micro-constants were converted to Q_PREDL/V2_PREDL via
#      Q = k12*V1, V2 = Q/k21 (both expressed per-kg, matching V1_PREDL's
#      own per-kg convention) -- an exact algebraic reparameterization, not
#      a new value; see refactor notes for the derivation.
#    - MTX: Archetype 3 minus the peripheral compartment (depot + central,
#      linear) plus a bespoke third compartment (POLY_MTX, unchanged name)
#      for the intracellular active polyglutamate moiety the original's
#      own Hill term reads -- the same POLY_MTX structure already used for
#      methotrexate in rheumatoid-arthritis/ra_mrgsolve_model_refactored.R.
#
#  Renamed to convention (values unchanged unless noted):
#    - PRED_GUT/PRED_C/ka_pred/Vd_pred/CL_pred ->
#      GUT_PRED/CENT_PRED/KA_PRED/V1_PRED/CL_PRED
#    - PREDL_C/PREDL_P/k_predl_conv/ka_predl/Vd_predl/CL_predl/
#      k12_predl/k21_predl -> CENT_PREDL/PERI_PREDL/FCONV_PREDL/KA_PREDL
#      (declared, never referenced by any dxdt_ line in the original --
#      preserved unused, same treatment as RTOT_TCZ in
#      rheumatoid-arthritis/ra_refactor_notes.md)/V1_PREDL/CL_PREDL/
#      Q_PREDL (derived)/V2_PREDL (derived)
#    - Emax_pred/EC50_pred -> EMAX_PREDL/EC50_PREDL; GAMMA_PREDL = 2.000
#      added (new $PARAM, copied from the original's shared HILL_n)
#    - MTX_GUT/MTX_C/ka_mtx/Vd_mtx/CL_mtx/k_poly/k_poly_el ->
#      GUT_MTX (name unchanged)/CENT_MTX/KA_MTX/V1_MTX/CL_MTX/KPOLY_MTX/
#      KDEPOLY_MTX; MTX_POLY -> POLY_MTX (name unchanged, already matched
#      convention)
#    - Emax_mtx/EC50_mtx_poly -> EMAX_MTX/EC50_MTX; GAMMA_MTX = 2.000 added
#      (new $PARAM, copied from the original's shared HILL_n)
#
#  Hill interface: RENAME, not a refit, for both compounds. The original's
#  Epred/Emtx terms were already the exact `Emax*C^n/(EC50^n+C^n)` shape
#  (shared Hill exponent HILL_n=2 across every compound in the file) --
#  EFFECT_PREDL/EFFECT_MTX below use the identical formula with the
#  compound's own EMAX_/EC50_/GAMMA_ params (GAMMA_ copied from HILL_n),
#  algebraically identical to the original. Every direct downstream use of
#  Epred (dxdt_TREG, dxdt_IFNG, dxdt_IL12, dxdt_CALIT, and the Elymph/Emac/
#  Etnf_inhib combination terms) and Emtx (inside Elymph only) was
#  redirected to EFFECT_PREDL/EFFECT_MTX -- same formulas, same execution
#  order, zero numeric change.
#
#  Build-compat fix (mrgsolve 2.0.1; unrelated to PRED/PREDL/MTX scope --
#  entirely inside the disease-PD initial-condition block -- logged as
#  UPSTREAM_ISSUES.md #60): the untouched original does not compile at all
#  under mrgsolve 2.0.1. Three layered defects: (1) the deprecated
#  "_init_<CMT> = value;" idiom used for all 13 disease-compartment initial
#  conditions, not accepted by this mrgsolve version; (2) $PARAM baseline
#  names TH1_0/TREG_0/IL12_0 collide with mrgsolve's own auto-reserved
#  per-compartment "<CMT>_0" initial-value symbol for compartments
#  TH1/TREG/IL12; (3) a pre-existing typo independent of (1)/(2): the
#  original declares "TREG_0" but reads it back as "TREG0" (no underscore)
#  in three places, so "TREG_0" as declared was never actually the symbol
#  being used. Fixed here, syntax-only, non-numeric: TH1_0/TREG_0/IL12_0
#  renamed to TH10/TREG0/IL120 (matching the no-underscore convention every
#  other baseline in the same block already uses, which also resolves the
#  typo in the same stroke), and all 13 "_init_<CMT>" lines converted to
#  the modern "<CMT>_0 = value;" idiom. See sarc_refactor_notes.md and
#  UPSTREAM_ISSUES.md #60 for full disclosure; sarc_mrgsolve_model.R itself
#  is untouched and still carries all three defects exactly as written.
#
#  Verification: ran the original file's own Scenario 2 (prednisone 40mg
#  taper) and Scenario 3 (prednisone 20mg + MTX 10mg/wk) dosing through
#  both models via the qspserver mrgsolve_api container (both models built
#  with the build-compat fix above applied identically; the true untouched
#  original does not build at all, see UPSTREAM_ISSUES.md #60). Every
#  shared compartment and $CAPTURE output matched to floating-point noise
#  (max abs diff ~1e-10 to ~1e-12) across the full 104-week/2913-point
#  6-hourly grid, both scenarios -- the expected result for a pure
#  structural rename with no Hill-refitting. See sarc_refactor_notes.md.
# =============================================================================

library(mrgsolve)
library(dplyr)
library(ggplot2)
library(tidyr)
library(gridExtra)

##==============================================================================
## mrgsolve MODEL DEFINITION
##==============================================================================

sarc_code <- '
$PROB
// Sarcoidosis QSP Model — mrgsolve implementation
// 20 compartments: 7 drug PK + 13 disease PD
// See file header for full reference list.

$PARAM @annotated
//--------------------------------------------------------------------
// Drug PK -- Prednisone (PRED; prodrug, the dosed compound). Archetype 3
// minus the peripheral compartment: depot + central, linear elimination.
// The original has no bioavailability factor for this compound -- none
// invented here either.
//--------------------------------------------------------------------
KA_PRED    : 1.50  : Prednisone gut absorption rate constant (1/h) (was ka_pred)
// Ref: Derendorf et al. (1985) -- ka ~1.5 h-1, Tmax ~1.5 h
V1_PRED    : 1.00  : Prednisone apparent central Vd (L/kg) (was Vd_pred)
CL_PRED    : 3.50  : Prednisone total clearance (L/h) (was CL_pred). The
// original’s own comment reads "per 70 kg" but the ODE never actually
// rescales this by WT/70 -- only V1_PRED is WT-scaled. Preserved exactly
// as the original computed it (not "fixed"); see refactor notes.
// Prednisone t1/2 ~3 h; CL dominated by first-pass conversion to prednisolone

//--------------------------------------------------------------------
// Drug PK -- Prednisolone (PREDL; the ACTIVE METABOLITE of prednisone,
// not an independently dosed compound -- see refactor notes for the
// parent-metabolite link and why PREDL has no GUT_/depot compartment of
// its own). Archetype 2 (2-compartment, linear, CL/Q/V), fed by a
// conversion inflow from PRED’s own central compartment.
//--------------------------------------------------------------------
FCONV_PREDL : 0.89 : Fraction of prednisone converted to prednisolone (was k_predl_conv)
KA_PREDL   : 0.80  : Declared in the original ("Prednisolone absorption/
// intercompartment rate", was ka_predl) but never referenced by any
// dxdt_ line in the original file -- preserved unused, renamed only, per
// the "don’t invent, don’t drop the original’s parameters" rule (same
// treatment given to RTOT_TCZ in rheumatoid-arthritis/ra_refactor_notes.md)
V1_PREDL   : 1.50  : Prednisolone central Vd (L/kg) (was Vd_predl)
CL_PREDL   : 2.80  : Prednisolone clearance (L/h) (was CL_predl); same
// "per 70 kg"-labelled-but-not-WT-rescaled quirk as CL_PRED, preserved
// Czock et al. (2005): prednisolone CL ~2.8 L/h, Vd ~1.5 L/kg
Q_PREDL    : 1.20  : Prednisolone inter-compartmental CL, expressed PER KG
// (L/h/kg) to match V1_PREDL/V2_PREDL’s own per-kg convention. Derived
// algebraically from the original’s own micro-constant and volume:
// k12_predl * Vd_predl = 0.80 * 1.50 = 1.20 -- not a new value; see
// refactor notes for the full derivation showing this reproduces the
// original’s k12_predl/k21_predl transfer exactly, for any WT.
V2_PREDL   : 3.00  : Prednisolone peripheral Vd, PER KG (L/kg), derived as
// Q_PREDL / k21_predl = 1.20 / 0.40 = 3.00 -- see refactor notes
// Peripheral distribution: t_eq ~1.5 h, ratio Vp/Vc ~2
EMAX_PREDL : 0.80  : Max inhibition by prednisolone (fraction 0-1) (was Emax_pred)
EC50_PREDL : 100.0 : Prednisolone EC50 for immune suppression (ng/mL) (was EC50_pred)
// Calibrated to ACE-25 trial: 40 mg/d pred achieves ~60% inhibition
// Prednisolone Cmax at 40 mg/d ~300-400 ng/mL; EC50 ~100 ng/mL
GAMMA_PREDL : 2.000 : Prednisolone Hill coefficient (new $PARAM; copied
// from the original’s shared HILL_n -- HILL_n itself is untouched below
// and still governs AZA/HCQ/IFX, which are out of this refactor’s scope)

//--------------------------------------------------------------------
// Drug PK -- Methotrexate (MTX). Archetype 3 minus the peripheral
// compartment (depot + central, linear) plus a bespoke third
// compartment for the intracellular active polyglutamate moiety
// (POLY_MTX) that the original’s own Hill effect term actually reads --
// not a second independently-dosed compound, an
// accumulation/elimination extension of MTX’s own single stem (see
// refactor notes; the identical POLY_MTX name/structure is already used
// for methotrexate in rheumatoid-arthritis/ra_mrgsolve_model_refactored.R).
//--------------------------------------------------------------------
KA_MTX     : 1.20  : MTX gut absorption rate constant (1/h) (was ka_mtx)
// Bressolle et al. (1998): oral MTX Tmax ~1.2 h at 10 mg dose
V1_MTX     : 0.80  : MTX apparent central Vd (L/kg) (was Vd_mtx)
CL_MTX     : 5.50  : MTX renal + biliary clearance (L/h) (was CL_mtx); same
// "per 70 kg" quirk as CL_PRED/CL_PREDL above, preserved
// MTX t1/2 ~6-7 h at low dose; CL_MTX = 5.5 L/h matches clinical
KPOLY_MTX  : 0.05  : MTX->polyglutamate formation rate constant (1/h) (was k_poly)
// Kager et al. (2014): intracellular MTXPG accumulates over weeks
KDEPOLY_MTX : 0.008 : MTX polyglutamate elimination rate constant (1/h) (was k_poly_el)
// t1/2 of MTXPG ~86 h (slow intracellular turnover)
EMAX_MTX   : 0.60  : Max inhibition by MTX-polyglutamates (was Emax_mtx)
EC50_MTX   : 5.0   : MTX polyglutamate EC50 for lymphocyte inhibition (nmol/L) (was EC50_mtx_poly)
// Vorselaars et al. (2015): MTX 10 mg/wk -> MTXPG ~5-15 nmol/L
GAMMA_MTX  : 2.000 : MTX Hill coefficient (new $PARAM; copied from the
// original’s shared HILL_n, see GAMMA_PREDL above)

//--------------------------------------------------------------------
// Patient covariate
//--------------------------------------------------------------------
WT         : 70.0  : Body weight (kg)

//--------------------------------------------------------------------
// Disease PD — Baseline steady-state values
//--------------------------------------------------------------------
MAC_ACT0   : 10.0  : Baseline activated macrophage burden (normalized units)
// Calibrated to ACE-25 trial: moderate disease, ACE ~45 U/L at baseline
TH10       : 15.0  : Baseline Th1 cell count (relative units) (renamed
// from TH1_0 -- mrgsolve 2.0.1 auto-reserves "<CMT>_0" per compartment,
// which collided with this param name for the TH1 compartment; build-
// compat fix, unrelated to PRED/PREDL/MTX scope, see refactor notes)
TREG0      :  5.0  : Baseline regulatory T cell count (relative units)
// (renamed from TREG_0 -- fixes both the <CMT>_0 collision above AND a
// pre-existing typo: the original’s own $MAIN/$ODE code already read
// this baseline as "TREG0" (no underscore) in three places, so the
// declared "TREG_0" was never actually the symbol being used; see
// refactor notes / UPSTREAM_ISSUES.md #60)
TNF0       : 20.0  : Baseline TNF-alpha (pg/mL)
// Judson et al. (2000): sarcoid BAL TNF elevated 3-5x vs. normal (~4 pg/mL)
IFNG0      :  5.0  : Baseline IFN-gamma (pg/mL)
IL120      : 15.0  : Baseline IL-12 (pg/mL) (renamed from IL12_0 --
// same <CMT>_0 collision as TH10 above, build-compat fix)
GRAN0      : 50.0  : Baseline granuloma burden (0-100; moderate pulmonary)
// Stage II-III disease: ~50 units; Stage I: ~20-30 units
FIBR0      :  0.05 : Baseline fibrosis extent (0-1 scale)
ACE0       : 45.0  : Baseline serum ACE (U/L; normal <52 U/L)
// ACE-25 trial baseline: 45 U/L (moderate active disease)
CALIT0     : 30.0  : Baseline calcitriol/1,25(OH)2D (pg/mL; normal 18-72)
// Sarcoid: granuloma macrophages over-hydroxylate 25-OHD -> 1,25-D
CA0        :  9.5  : Baseline serum calcium (mg/dL; normal 8.5-10.5)
SIL2R0     : 800.0 : Baseline serum sIL-2R (U/mL; normal <496 U/mL)
// Elevated sIL-2R reflects activated T cells; used as activity marker
FVC_P0     : 85.0  : Baseline FVC % predicted (moderate pulmonary restriction)
// FIRST trial: mean baseline FVC ~85% pred in treated patients

//--------------------------------------------------------------------
// Disease kinetic parameters
//--------------------------------------------------------------------
k_mac_stim : 0.020 : Macrophage activation stimulation rate (per unit TNF/IL-12)
k_mac_el   : 0.100 : Macrophage activated-state decay/clearance (1/h)
k_th1_stim : 0.050 : Th1 stimulation rate by IL-12 + IFN-g feedback
k_th1_el   : 0.080 : Th1 clearance rate (1/h)
k_treg_stim: 0.010 : Treg induction rate (by activated macrophages)
k_treg_el  : 0.050 : Treg clearance rate (1/h)
k_tnf      : 0.300 : TNF production rate by macrophages (pg/mL per MAC unit/h)
k_tnf_el   : 0.500 : TNF clearance rate (1/h)
// TNF half-life in vivo ~18-20 min -> k_el ~2 h-1; slowed here due to
// chronic replenishment (effective clearance reflects net dynamics)
k_ifng     : 0.100 : IFN-gamma production by Th1 cells
k_ifng_el  : 0.300 : IFN-gamma clearance (1/h)
k_il12     : 0.200 : IL-12 production by activated macrophages
k_il12_el  : 0.400 : IL-12 clearance rate (1/h)
k_gran_form: 0.010 : Granuloma formation rate (per MAC*TNF*IFNG product)
k_gran_res : 0.005 : Spontaneous granuloma resolution rate (1/h, ~8 wks t1/2)
// Spontaneous resolution seen in Stage I: t1/2 ~6-12 weeks
k_fibr     : 5e-4  : Fibrosis induction rate from chronic granuloma burden
k_fibr_max : 1.00  : Maximum fibrosis extent (0-1 scale)
k_ace      : 0.500 : ACE release rate proportional to granuloma burden
k_ace_el   : 0.200 : ACE clearance/degradation rate (1/h)
k_calit    : 0.300 : Calcitriol production by granuloma macrophages
k_calit_el : 0.250 : Calcitriol clearance (renal + hepatic, 1/h)
// Calcitriol t1/2 ~5-8 h -> k_el ~0.1-0.15; effective rate elevated here
// to account for rapid regulation in chronic state
k_ca_abs   : 0.050 : Calcium absorption increase per calcitriol unit
k_ca_el    : 0.150 : Calcium renal/intestinal clearance (1/h)
k_sil2r    : 2.000 : sIL-2R secretion rate per activated Th1+Treg units
k_sil2r_el : 0.500 : sIL-2R clearance rate (1/h)
k_fvc      : 0.002 : FVC % decline per unit fibrosis per hour
HILL_n     : 2.000 : Hill coefficient for drug PD Emax models

//--------------------------------------------------------------------
// Drug effect parameters
// NOTE: prednisolone’s (EMAX_PREDL/EC50_PREDL/GAMMA_PREDL) and MTX’s
// (EMAX_MTX/EC50_MTX/GAMMA_MTX) Hill-interface params moved up into their
// own PK blocks above, next to each compound’s other params -- same
// values, new location, per this refactor’s scope. AZA/HCQ/IFX below are
// completely untouched (out of scope for this refactor).
//--------------------------------------------------------------------
EC50_aza   :  50.0  : Azathioprine (TGN) EC50 for lymphocyte suppression
// TGN levels at therapeutic AZA dose: 200-400 pmol/8x10^8 RBC; normalized
Emax_aza   :   0.55 : Max inhibition by AZA/TGN
EC50_hcq   : 200.0  : Hydroxychloroquine EC50 for TLR/macrophage inhibition (ng/mL)
// HCQ 400 mg/d -> Csteady ~400-700 ng/mL; EC50 ~200 ng/mL
Emax_hcq   :   0.40 : Max inhibition by HCQ (primarily macrophage/IL-12)
EC50_ifx   :   1.0  : Infliximab EC50 for TNF neutralization (mcg/mL)
// Infliximab 3 mg/kg IV -> Cmax ~70 mcg/mL; trough ~1-3 mcg/mL
Emax_ifx   :   0.90 : Max TNF neutralization by infliximab

//--------------------------------------------------------------------
// Simplified drug steady-state concentrations for scenarios
// (AZA, HCQ: use constant Css placeholders; switched on by dose flags)
//--------------------------------------------------------------------
AZA_CSS    :   0.0  : AZA/TGN effective concentration (normalized, set by scenario)
HCQ_CSS    :   0.0  : HCQ steady-state concentration (ng/mL, set by scenario)
IFX_CSS    :   0.0  : Infliximab trough concentration (mcg/mL, set by scenario)

// Spontaneous resolution flag (1 = mild/Stage I disease, lower GRAN0)
SPON_RES   :   0.0  : Spontaneous resolution flag (set to 1 for Stage I)

$CMT @annotated
//--------------------------------------------------------------------
// 7 PK compartments
//--------------------------------------------------------------------
GUT_PRED   : Prednisone gut absorption depot (mg) (was PRED_GUT)
CENT_PRED  : Prednisone central plasma, mg (was PRED_C)
CENT_PREDL : Prednisolone central plasma, mg -- active metabolite (was PREDL_C)
PERI_PREDL : Prednisolone peripheral tissue depot, mg (was PREDL_P)
GUT_MTX    : Methotrexate gut absorption depot (mg) (unchanged name)
CENT_MTX   : MTX central plasma, mg (was MTX_C)
POLY_MTX   : MTX intracellular polyglutamates, nmol/L -- active form;
// this IS the exposed C_MTX read by the Hill effect (unchanged name,
// already matched the convention; was MTX_POLY)

//--------------------------------------------------------------------
// 13 PD compartments
//--------------------------------------------------------------------
MAC_ACT    : Activated macrophage burden (normalized units)
TH1        : Th1 effector cell count (relative units)
TREG       : Regulatory T cell count (relative units)
TNF        : TNF-alpha (pg/mL)
IFNG       : IFN-gamma (pg/mL)
IL12       : IL-12 (pg/mL)
GRAN       : Total granuloma burden (0-100 arbitrary units)
FIBR       : Pulmonary fibrosis extent (0-1)
ACE_BM     : Serum ACE biomarker (U/L)
CALIT      : Serum 1,25-dihydroxyvitamin D / calcitriol (pg/mL)
SERUM_CA   : Serum calcium (mg/dL)
SIL2R      : Serum sIL-2R (U/mL)
FVC_P      : FVC percent predicted (%)

$MAIN
//--------------------------------------------------------------------
// Derived PK constants (renamed to convention; same formulas)
//--------------------------------------------------------------------
double V1_PRED_L  = V1_PRED  * WT;        // L
double V1_PREDL_L = V1_PREDL * WT;        // L
double V2_PREDL_L = V2_PREDL * WT;        // L (see Q_PREDL/V2_PREDL derivation in $PARAM)
double Q_PREDL_L  = Q_PREDL  * WT;        // L/h
double V1_MTX_L   = V1_MTX   * WT;        // L

//--------------------------------------------------------------------
// Initial conditions -- set from baseline params.
// Build-compat fix (mrgsolve 2.0.1, unrelated to PRED/PREDL/MTX scope,
// see UPSTREAM_ISSUES.md #60): the original used the legacy
// "_init_<CMT> = value;" idiom, which this mrgsolve version does not
// accept ("’_init_MAC_ACT’ was not declared in this scope" etc.) --
// switched to the modern "<CMT>_0 = value;" idiom. TH1_0/TREG_0/IL12_0
// below are mrgsolve’s own auto-reserved per-compartment symbols (not the
// renamed TH10/TREG0/IL120 baseline params on the right-hand side --
// those are different symbols after the $PARAM rename above).
//--------------------------------------------------------------------
MAC_ACT_0  = MAC_ACT0;
TH1_0      = TH10;
TREG_0     = TREG0;
TNF_0      = TNF0;
IFNG_0     = IFNG0;
IL12_0     = IL120;
GRAN_0     = GRAN0;
FIBR_0     = FIBR0;
ACE_BM_0   = ACE0;
CALIT_0    = CALIT0;
SERUM_CA_0 = CA0;
SIL2R_0    = SIL2R0;
FVC_P_0    = FVC_P0;

$ODE
//====================================================================
// SECTION 1: Drug PK ODEs
//====================================================================

//--------------------------------------------------------------------
// 1a. Prednisone (PRED) -- depot -> central, linear elimination.
//    Prodrug; ~89% converted to prednisolone (see PREDL block below).
//    Ref: Derendorf et al. (1985), Czock et al. (2005)
//--------------------------------------------------------------------
dxdt_GUT_PRED  = -KA_PRED * GUT_PRED;
dxdt_CENT_PRED =  KA_PRED * GUT_PRED - (CL_PRED / V1_PRED_L) * CENT_PRED;

// C_PRED: prednisone plasma concentration (mg/L = ug/mL). Not itself an
// effect-driving concentration (prednisone has no direct PD effect in the
// original) -- it exists solely to drive the conversion into prednisolone
// immediately below. See refactor notes for the parent-metabolite link.
double C_PRED = CENT_PRED / V1_PRED_L;

//--------------------------------------------------------------------
// Prednisolone (PREDL) -- central + peripheral, linear CL/Q/V, fed by a
// conversion inflow from PRED’s own plasma concentration. Algebraically
// identical to the original’s k12_predl/k21_predl micro-constant form;
// see the Q_PREDL/V2_PREDL derivation in $PARAM and refactor notes.
//--------------------------------------------------------------------
// Conversion inflow: fraction FCONV_PREDL of the mass PRED eliminates,
// scaled into PREDL’s own central volume -- same formula as the
// original’s "k_predl_conv * CL_pred * pred_conc_ug_mL * Vc_predl_ode /
// 1000.0" line, renamed variables only, zero numeric change.
double CONV_PRED_TO_PREDL = FCONV_PREDL * CL_PRED * C_PRED * V1_PREDL_L / 1000.0;

dxdt_CENT_PREDL = CONV_PRED_TO_PREDL
                 + (Q_PREDL_L / V2_PREDL_L) * PERI_PREDL
                 - ((CL_PREDL + Q_PREDL_L) / V1_PREDL_L) * CENT_PREDL;

dxdt_PERI_PREDL = (Q_PREDL_L / V1_PREDL_L) * CENT_PREDL
                 - (Q_PREDL_L / V2_PREDL_L) * PERI_PREDL;

// C_PREDL: the exposed prednisolone concentration (ng/mL) -- the single
// point where an external covariate could later be substituted in. Same
// scale as the original’s PREDL_conc_ng_mL/predl_c.
double C_PREDL = (CENT_PREDL / V1_PREDL_L) * 1000.0; // ng/mL
double c_predl_nn = (C_PREDL < 0) ? 0 : C_PREDL; // non-negative clamp, as original

//--------------------------------------------------------------------
// 1b. Methotrexate (MTX) -- depot -> central -> intracellular
//     polyglutamates (POLY_MTX, the active moiety the original’s own
//     Hill term reads). Oral MTX 10 mg/week dosed once weekly.
//     Ref: Bressolle et al. (1998), Kager et al. (2014)
//--------------------------------------------------------------------
dxdt_GUT_MTX  = -KA_MTX * GUT_MTX;

dxdt_CENT_MTX =  KA_MTX * GUT_MTX
              - (CL_MTX / V1_MTX_L) * CENT_MTX
              - KPOLY_MTX * CENT_MTX;

// Cp_MTX_plasma: MTX plasma concentration (mg/L = ug/mL) -- informational
// only, NOT the exposed effect-driving concentration (same "kept only as
// an informational, non-exposed diagnostic" pattern documented for the
// tissue/plasma split in abdominal-aortic-aneurysm/aaa_refactor_notes.md).
double Cp_MTX_plasma = CENT_MTX / V1_MTX_L;

// MTX polyglutamates: slow formation, slow elimination (t1/2 ~86 h).
// Units: nmol/L; the original converts directly from CENT_MTX (mg), not
// from a mg/L concentration -- preserved exactly as originally computed
// (not "fixed"), see refactor notes.
double MTXPG_input_nmol = CENT_MTX * 1e6 / 454.0;  // was mtx_nmol
dxdt_POLY_MTX = KPOLY_MTX * MTXPG_input_nmol - KDEPOLY_MTX * POLY_MTX;

// C_MTX: the exposed MTX effect-driving concentration. POLY_MTX (the
// intracellular active moiety) already IS this concentration -- the
// compartment needs no further division, same "compartment IS
// concentration" pattern documented in eosinophilic-esophagitis/
// eoe_refactor_notes.md and dengue/denv_refactor_notes.md.
double C_MTX = POLY_MTX;
double c_mtx_nn = (C_MTX < 0) ? 0 : C_MTX; // non-negative clamp, as original

//====================================================================
// SECTION 2: Drug Effect Calculations (Emax models)
//====================================================================

double aza_c   = (AZA_CSS  < 0)         ? 0 : AZA_CSS;
double hcq_c   = (HCQ_CSS  < 0)         ? 0 : HCQ_CSS;
double ifx_c   = (IFX_CSS  < 0)         ? 0 : IFX_CSS;

// Hill function: f(C) = Emax * C^n / (EC50^n + C^n)
double n = HILL_n;

// Prednisolone -- broad immunosuppression; primary effect on macrophages
// & T cells. Rename of the original’s "Epred", not a refit: the original’s
// term was already this exact Hill shape (see refactor notes).
double EFFECT_PREDL = EMAX_PREDL * pow(c_predl_nn, GAMMA_PREDL) /
               (pow(EC50_PREDL, GAMMA_PREDL) + pow(c_predl_nn, GAMMA_PREDL) + 1e-9);

// MTX-polyglutamates -- inhibit lymphocyte proliferation & cytokine
// release. Rename of the original’s "Emtx", not a refit.
double EFFECT_MTX = EMAX_MTX * pow(c_mtx_nn, GAMMA_MTX) /
              (pow(EC50_MTX, GAMMA_MTX) + pow(c_mtx_nn, GAMMA_MTX) + 1e-9);

// AZA (constant CSS) -- inhibit T cell proliferation [unchanged, out of scope]
double Eaza = Emax_aza * pow(aza_c, n) /
              (pow(EC50_aza, n) + pow(aza_c, n) + 1e-9);

// HCQ (constant CSS) -- inhibit TLR-mediated macrophage activation and IL-12 [unchanged, out of scope]
double Ehcq = Emax_hcq * pow(hcq_c, n) /
              (pow(EC50_hcq, n) + pow(hcq_c, n) + 1e-9);

// Infliximab (constant trough) -- neutralize TNF [unchanged, out of scope]
// At 3 mg/kg q8w: Cmax ~70 mcg/mL, trough ~1-3 mcg/mL
// FIRST trial (Baughman 2006): 5% improvement in FVC at 24 wks
double Eifx = Emax_ifx * pow(ifx_c, n) /
              (pow(EC50_ifx, n) + pow(ifx_c, n) + 1e-9);

// Combined lymphocyte inhibition (pred + MTX + AZA act additively on T cells)
// Cap combined effect at 0.95 to avoid complete ablation
double Elymph = 1.0 - (1.0 - EFFECT_PREDL) * (1.0 - EFFECT_MTX) * (1.0 - Eaza);
if (Elymph > 0.95) Elymph = 0.95;

// Combined macrophage inhibition (pred + HCQ)
double Emac = 1.0 - (1.0 - EFFECT_PREDL) * (1.0 - Ehcq);
if (Emac > 0.95) Emac = 0.95;

// TNF inhibition: pred + infliximab (infliximab highly specific for TNF)
double Etnf_inhib = 1.0 - (1.0 - EFFECT_PREDL * 0.5) * (1.0 - Eifx);
if (Etnf_inhib > 0.98) Etnf_inhib = 0.98;

//====================================================================
// SECTION 3: Disease PD ODEs
//====================================================================

// ── Clamp state variables to physiological range ─────────────────
double mac  = (MAC_ACT  < 0) ? 0 : MAC_ACT;
double th1  = (TH1      < 0) ? 0 : TH1;
double treg = (TREG     < 0) ? 0 : TREG;
double tnf  = (TNF      < 0) ? 0 : TNF;
double ifng = (IFNG     < 0) ? 0 : IFNG;
double il12 = (IL12     < 0) ? 0 : IL12;
double gran = (GRAN     < 0) ? 0 : ((GRAN > 100) ? 100 : GRAN);
double fibr = (FIBR     < 0) ? 0 : ((FIBR > 1)   ? 1   : FIBR);

// ── Regulatory suppression factor: Tregs suppress effector responses ──
// Treg effect: reduces macrophage + Th1 activity
double treg_ratio = TREG0 / (treg + 1e-9);  // ratio: elevated Tregs = protection
double treg_suppress = 1.0 / (1.0 + treg / (TREG0 * 2.0));  // sigmoidal suppression

//--------------------------------------------------------------------
// 3a. Activated macrophages (MAC_ACT)
//     Stimulated by: self (autocrine TNF), IL-12 from prior activation
//     Inhibited by: prednisolone, HCQ (TLR blockade), Tregs
//     Ref: Salgame et al. (2014) J Immunol; Iannuzzi et al. (2007) NEJM
//--------------------------------------------------------------------
// Antigen-driven persistent stimulation (mycobacterial/environmental trigger)
// In sarcoidosis: persistent antigen drives chronic macrophage activation
double mac_stim_input = k_mac_stim * (tnf / TNF0) * (il12 / IL120) * treg_ratio;
// Spontaneous resolution: SPON_RES flag reduces antigenic stimulation
double antigen_drive = 1.0 - SPON_RES * 0.8;  // 80% reduction for Stage I

dxdt_MAC_ACT = mac_stim_input * MAC_ACT0 * antigen_drive
              - k_mac_el * mac * (1.0 + Emac);

//--------------------------------------------------------------------
// 3b. Th1 cells
//     Stimulated by: IL-12 (critical Th1 polarization), IFN-g (amplification)
//     Inhibited by: prednisolone, MTX, AZA, Tregs
//     Ref: Müller-Quernheim (1998) Sarcoidosis Vasc Diffuse Lung Dis
//--------------------------------------------------------------------
double th1_stim = k_th1_stim * (il12 / IL120) * (1.0 + ifng / IFNG0);
dxdt_TH1 = th1_stim * TH10 * treg_suppress
           - k_th1_el * th1 * (1.0 + Elymph);

//--------------------------------------------------------------------
// 3c. Regulatory T cells (TREG)
//     Induced by: activated macrophages (via TGF-β signaling)
//     Prednisolone has complex effect: transiently spares Tregs
//     Ref: Miyara et al. (2006) J Exp Med
//--------------------------------------------------------------------
double treg_stim = k_treg_stim * mac;
dxdt_TREG = treg_stim * (1.0 + EFFECT_PREDL * 0.2)  // pred mildly spares Tregs
           - k_treg_el * treg;

//--------------------------------------------------------------------
// 3d. TNF-alpha
//     Produced by: activated macrophages (central cytokine in sarcoid granuloma)
//     Inhibited by: prednisolone (via NF-kB), infliximab (direct neutralization)
//     Ref: Ziegenhagen & Müller-Quernheim (2003) J Intern Med
//     FIRST trial: infliximab 3 mg/kg improved FVC by ~5% at 24 wks
//--------------------------------------------------------------------
dxdt_TNF = k_tnf * mac * MAC_ACT0 / (MAC_ACT0 + mac)  // Michaelis-Menten production
          * (1.0 - Etnf_inhib)
          - k_tnf_el * tnf;

//--------------------------------------------------------------------
// 3e. IFN-gamma
//     Produced by: Th1 cells (hallmark cytokine of sarcoidosis)
//     Inhibited by: prednisolone
//     Amplifies macrophage activation -> positive feedback loop
//     Ref: Agostini et al. (1998) Eur Respir J
//--------------------------------------------------------------------
dxdt_IFNG = k_ifng * th1 * TH10 / (TH10 + th1)
           * (1.0 - EFFECT_PREDL * 0.6)
           - k_ifng_el * ifng;

//--------------------------------------------------------------------
// 3f. IL-12
//     Produced by: activated macrophages and DCs (key Th1 polarizer)
//     Inhibited by: HCQ (blocks TLR7/9-mediated production), prednisolone
//     Ref: Minozzi et al. (2010) — HCQ reduces IL-12 in sarcoid macrophages
//--------------------------------------------------------------------
dxdt_IL12 = k_il12 * mac
           * (1.0 - Ehcq * 0.8) * (1.0 - EFFECT_PREDL * 0.5)
           - k_il12_el * il12;

//--------------------------------------------------------------------
// 3g. Granuloma burden (GRAN)
//     Formation: driven by macrophage activation + TNF + IFN-g
//     (Multinucleated giant cell formation requires all three signals)
//     Resolution: spontaneous (slow, years) or treatment-accelerated
//     Ref: Mushaben et al. — granuloma dynamics
//     ACE-25 trial: ~25% reduction in granuloma-related ACE over 2 years
//--------------------------------------------------------------------
// Formation signal: product of key drivers (normalized)
double gran_drive = (mac / MAC_ACT0) * (tnf / TNF0) * (ifng / IFNG0);

// Net drug effect on granuloma resolution: combined suppression
double Edrug_gran = 1.0 - (1.0 - Emac) * (1.0 - Elymph * 0.5);

// Spontaneous resolution enhanced for Stage I (SPON_RES=1)
double k_spon_boost = k_gran_res * (1.0 + SPON_RES * 3.0);

dxdt_GRAN = k_gran_form * gran_drive * (100.0 - gran) * GRAN0
           - k_spon_boost * gran
           - k_gran_res * gran * Edrug_gran * 5.0;

//--------------------------------------------------------------------
// 3h. Pulmonary fibrosis (FIBR)
//     Driven by: chronic granuloma burden (irreversible remodeling)
//     Cannot regress below FIBR0 (established fibrosis)
//     FVC declines proportionally to fibrosis extent
//     Ref: Nardi et al. (2011) Eur Respir J — fibrosis progression in sarc
//--------------------------------------------------------------------
double fibr_drive = gran / 100.0;  // normalized granuloma -> fibrosis
// Fibrosis is quasi-irreversible; no effective drug reversal
// Corticosteroids can slow progression but not reverse established fibrosis
double fibr_floor = FIBR0;
double fibr_incr  = k_fibr * fibr_drive * (k_fibr_max - fibr) * (fibr > fibr_floor ? 1 : 0.1);
// Very slow reversal with effective treatment (clinical observation)
double fibr_decr  = k_fibr * 0.05 * Edrug_gran * fibr;

dxdt_FIBR = fibr_incr - fibr_decr;

//--------------------------------------------------------------------
// 3i. Serum ACE (ACE_BM)
//     Produced by: granuloma macrophages (epithelioid cells)
//     ACE is diagnostic/monitoring biomarker; normal <52 U/L
//     ACE-25 trial: baseline ~45, prednisone -> ~30 at 6 months
//     Ref: Studdy & Bird (1989) — ACE as sarcoidosis activity marker
//--------------------------------------------------------------------
dxdt_ACE_BM = k_ace * gran - k_ace_el * ACE_BM;

//--------------------------------------------------------------------
// 3j. Calcitriol / 1,25(OH)2D (CALIT)
//     Sarcoid macrophages express CYP27B1 -> over-convert 25-OHD to 1,25-D
//     Granuloma burden drives excess calcitriol -> hypercalcemia risk
//     HCQ inhibits CYP27B1 in macrophages (key mechanism)
//     Ref: Adams & Hewison (2012) — HCQ reduces calcitriol in sarcoidosis
//--------------------------------------------------------------------
dxdt_CALIT = k_calit * gran * (1.0 - Ehcq * 0.7) * (1.0 - EFFECT_PREDL * 0.4)
            - k_calit_el * CALIT;

//--------------------------------------------------------------------
// 3k. Serum calcium (SERUM_CA)
//     Elevated calcitriol -> increased GI calcium absorption
//     Hypercalcemia (>10.5 mg/dL) in ~10% of sarcoid patients
//     Ref: Sharma (1996) — hypercalcemia in sarcoidosis
//--------------------------------------------------------------------
double calit_excess = (CALIT - CALIT0);  // excess above normal
if (calit_excess < 0) calit_excess = 0;
dxdt_SERUM_CA = k_ca_abs * calit_excess
               - k_ca_el * (SERUM_CA - CA0);  // homeostatic regulation toward CA0

//--------------------------------------------------------------------
// 3l. Serum sIL-2R (SIL2R)
//     Shed from activated T cells (CD4+ Th1 primarily)
//     Strong marker of T cell activation; elevated in active sarcoidosis
//     Ref: Ziegenhagen et al. (2003) — sIL-2R vs. ACE in monitoring
//     Vorselaars trial: sIL-2R decreases with MTX/AZA treatment
//--------------------------------------------------------------------
dxdt_SIL2R = k_sil2r * (th1 + treg * 0.2)  // predominantly shed by Th1
            * (1.0 - Elymph * 0.7)
            - k_sil2r_el * SIL2R;

//--------------------------------------------------------------------
// 3m. FVC % predicted (FVC_P)
//     Declines with fibrosis; improves slightly with inflammation reduction
//     In sarcoidosis: inflammatory component is reversible; fibrotic is not
//     FIRST trial: ~5% improvement with infliximab at 24 weeks (stage II-III)
//     ACE-25: ~3% improvement with prednisone vs. placebo at 6 months
//--------------------------------------------------------------------
// Inflammatory contribution to FVC reduction (reversible)
double inflam_fvc_effect = (gran / GRAN0 - 1.0) * 5.0;  // up to -5% from inflammation
if (inflam_fvc_effect > 0) inflam_fvc_effect = 0;

// Fibrosis contribution (quasi-irreversible)
double fibr_fvc_effect = (fibr - FIBR0) * 30.0;  // each 0.1 unit fibrosis = -3% FVC

// Target FVC: baseline minus fibrotic and inflammatory penalties
double fvc_target = FVC_P0 - fibr_fvc_effect + (gran < GRAN0 ? (GRAN0 - gran) * 0.05 : 0);
double fvc_current = FVC_P;

// First-order approach to target (rate limited)
dxdt_FVC_P = k_fvc * (fvc_target - fvc_current);

$TABLE
//====================================================================
// OUTPUT TABLE — capture PK concentrations + PD biomarkers
//====================================================================

// PK outputs (renamed to convention). C_PRED/C_PREDL/Cp_MTX_plasma/C_MTX/
// EFFECT_PREDL/EFFECT_MTX are the state-dependent quantities the guide’s
// qspserver-compatibility section asks to make discoverable -- they
// cannot themselves be $PARAM (they are computed every $ODE evaluation
// from compartment state, so a $PARAM of the same name would be a
// redeclaration), so per the precedent in eosinophilic-esophagitis/
// eoe_refactor_notes.md and thyroid-eye-disease/ted_refactor_notes.md
// they are captured here instead (with an "_OUT" suffix, since a bare
// "capture C_PRED = C_PRED;" self-reference is itself a redefinition
// against the $ODE double of the same name under mrgsolve 2.0.1),
// making them discoverable outputPaths via /model_manifest.
capture C_PRED_OUT          = C_PRED;          // mg/L (informational; PRED has no direct effect)
capture C_PREDL_OUT         = C_PREDL;         // ng/mL -- the exposed prednisolone concentration
capture Cp_MTX_plasma_OUT   = Cp_MTX_plasma;   // mg/L = ug/mL -- informational only, not exposed
capture C_MTX_OUT           = C_MTX;           // nmol/L -- the exposed MTX effect-driving concentration (== POLY_MTX)

// Drug effect indices (fraction inhibition) -- renamed from E_pred_fx/E_mtx_fx
capture EFFECT_PREDL_OUT = EFFECT_PREDL;
capture EFFECT_MTX_OUT   = EFFECT_MTX;

// PD state outputs
capture MACROPHAGE  = MAC_ACT;
capture TH1_CELLS   = TH1;
capture TREG_CELLS  = TREG;
capture TNF_pg_mL   = TNF;
capture IFNG_pg_mL  = IFNG;
capture IL12_pg_mL  = IL12;
capture GRANULOMA   = GRAN;
capture FIBROSIS    = FIBR;
capture ACE         = ACE_BM;
capture CALCITRIOL  = CALIT;
capture CALCIUM     = SERUM_CA;
capture SIL2R_UmL   = SIL2R;
capture FVC_pct     = FVC_P;

// Derived clinical outcome flags
capture HYPERCALCEMIA = (SERUM_CA > 10.5) ? 1.0 : 0.0;
capture ACE_ELEVATED  = (ACE_BM   > 52.0) ? 1.0 : 0.0;
capture FVC_IMPAIRED  = (FVC_P    < 70.0) ? 1.0 : 0.0;
'

##==============================================================================
## COMPILE MODEL
##==============================================================================

message("Compiling Sarcoidosis QSP mrgsolve model...")
mod <- mrgsolve::mcode("sarcoidosis_qsp_refactored", sarc_code)
message("Model compiled successfully. Compartments: ", length(mod@cmtn))

## Quick check of model structure
print(mod)

##==============================================================================
## HELPER FUNCTIONS
##==============================================================================

## Prednisone daily oral dosing (split into AM/PM equivalent using once-daily)
## Dose in mg; mrgsolve expects addl + ii for multiple dosing
dose_pred <- function(dose_mg, duration_weeks, start_week = 0) {
  ## Daily dosing: ii = 24 h, addl = (duration_weeks*7 - 1)
  mrgsolve::ev(
    time = start_week * 168,   # convert weeks to hours
    amt  = dose_mg,
    cmt  = "GUT_PRED",
    ii   = 24,
    addl = pmax(0, as.integer(duration_weeks * 7) - 1)
  )
}

## MTX weekly oral dosing
dose_mtx <- function(dose_mg, duration_weeks, start_week = 0) {
  mrgsolve::ev(
    time = start_week * 168,
    amt  = dose_mg,
    cmt  = "GUT_MTX",
    ii   = 168,   # weekly = 168 h
    addl = pmax(0, as.integer(duration_weeks) - 1)
  )
}

## Prednisone taper: 40 mg x 4wk -> 20 mg x 4wk -> 10 mg x 4wk -> 5 mg x 4wk
taper_pred <- function(start_week = 0) {
  ev1 <- dose_pred(40, 4, start_week)
  ev2 <- dose_pred(20, 4, start_week + 4)
  ev3 <- dose_pred(10, 4, start_week + 8)
  ev4 <- dose_pred(5,  4, start_week + 12)
  mrgsolve::ev_seq(ev1, ev2, ev3, ev4)
}

## Simulation wrapper: run 104 weeks, return tidy data frame
run_sim <- function(model, events, param_update = list(), sim_dur_wk = 104,
                    delta_h = 6) {
  ## Update parameters if provided
  if (length(param_update) > 0) {
    model <- mrgsolve::param(model, param_update)
  }
  out <- model |>
    mrgsolve::ev(events) |>
    mrgsolve::mrgsim(end = sim_dur_wk * 168, delta = delta_h, digits = 6) |>
    as.data.frame()
  out$time_weeks <- out$time / 168
  out
}

##==============================================================================
## TREATMENT SCENARIOS
##==============================================================================
## Simulation duration: 104 weeks (2 years)
## Clinical reference: ACE-25 trial ran 24 months; FIRST trial 24 weeks;
##   Vorselaars 2015 ran 24 months for MTX vs AZA comparison

SIM_WEEKS <- 104

## ─── Scenario 1: No Treatment (Natural History) ───────────────────────────
## Based on longitudinal cohort data:
##   Nardi et al. (2011): without treatment, stage II/III progresses in ~30%
##   Granuloma burden remains stable or slowly increases
##   FVC may decline 1-2% per year in untreated moderate disease

message("\n=== Scenario 1: No Treatment (Natural History) ===")
ev_none <- mrgsolve::ev(time = 0, amt = 0, cmt = "GUT_PRED")  # null event
sim1 <- run_sim(mod, ev_none,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 0,
                                    SPON_RES = 0))
sim1$Scenario <- "1: No Treatment"

## ─── Scenario 2: Prednisone 40 mg/day x 12 wks then taper ─────────────────
## Clinical basis:
##   ACE-25 trial (Gibson 1996): 40 mg/d prednisone x 3 months then taper
##   Result: FVC +3.3% vs placebo at 24 months; ACE decreased ~30%
##   Paramothayan Cochrane (2002): corticosteroids improve FVC short-term
## Regimen: 40 mg x 4wk -> 20 mg x 4wk -> 10 mg x 4wk -> 5 mg x 4wk -> stop

message("=== Scenario 2: Prednisone 40 mg/day (taper over 16 weeks) ===")
ev_pred40 <- taper_pred(start_week = 0)
sim2 <- run_sim(mod, ev_pred40,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 0,
                                    SPON_RES = 0))
sim2$Scenario <- "2: Prednisone 40mg Taper"

## ─── Scenario 3: Prednisone 20 mg/day + MTX 10 mg/week (Steroid-Sparing) ──
## Clinical basis:
##   Vorselaars et al. (2015) Eur Respir J: MTX vs AZA for pulmonary sarcoidosis
##   MTX arm: 10 mg/week; prednisone dose reduced to ~10-15 mg/day at 6 months
##   Result: FVC improvement non-inferior to AZA; better tolerability
##   Baughman et al. (2000): MTX 10 mg/wk as steroid-sparer in chronic sarc
## Regimen: Pred 20 mg/d x 16 wk then taper; MTX 10 mg/wk continuous x 104 wk

message("=== Scenario 3: Prednisone 20mg/d + MTX 10mg/wk (Steroid-Sparing) ===")
ev_pred20 <- mrgsolve::ev_seq(
  dose_pred(20, 16, 0),          # 20 mg/d x 16 wk
  dose_pred(10, 12, 16),         # taper to 10 mg x 12 wk
  dose_pred(5,  8,  28)          # further taper to 5 mg x 8 wk -> stop
)
ev_mtx10 <- dose_mtx(10, SIM_WEEKS, start_week = 0)  # MTX 10 mg/wk x 2 yrs
ev_pred_mtx <- mrgsolve::ev_seq(ev_pred20) + mrgsolve::ev_seq(ev_mtx10)

sim3 <- run_sim(mod, ev_pred_mtx,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 0,
                                    SPON_RES = 0))
sim3$Scenario <- "3: Pred 20mg + MTX 10mg/wk"

## ─── Scenario 4: Infliximab 3 mg/kg IV q8 weeks (Refractory Disease) ──────
## Clinical basis:
##   FIRST trial (Baughman 2006 Chest): infliximab 3 or 5 mg/kg q4-8wk
##   Result: FVC improved +2.5% (3 mg/kg) vs. placebo at 24 wks
##   Judson et al. (2008) Respir Med: IFX beneficial in refractory pulmonary sarc
##   Baughman 2012: long-term IFX maintenance in chronic pulmonary sarc
## PK: IFX 3 mg/kg IV q8wk -> trough ~2-4 mcg/mL (used as IFX_CSS)
## Implementation: IFX modeled as constant trough via IFX_CSS parameter

message("=== Scenario 4: Infliximab 3mg/kg IV q8 weeks (Refractory) ===")
## IFX trough ~2.5 mcg/mL at steady state (3 mg/kg q8wk)
## Combined with low-dose pred bridge (10 mg/d for first 4 wk)
ev_ifx_bridge_pred <- dose_pred(10, 4, 0)  # short pred bridge
sim4 <- run_sim(mod, ev_ifx_bridge_pred,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 2.5,
                                    SPON_RES = 0))
sim4$Scenario <- "4: Infliximab 3mg/kg q8wk"

## ─── Scenario 5: HCQ 400 mg/day (Cutaneous + Hypercalcemia; Mild Disease) ─
## Clinical basis:
##   Ogura et al. — HCQ effective for sarcoid-related hypercalcemia
##   HCQ blocks CYP27B1 in granuloma macrophages -> reduces calcitriol excess
##   Adams & Hewison (1992, 2012): landmark papers on HCQ mechanism in sarc
##   Siltzbach & Teirstein (1964): early HCQ use in cutaneous/systemic sarc
##   Lower efficacy for pulmonary disease; good for skin lesions + hypercalcemia
## PK: HCQ 400 mg/d -> Css ~400-700 ng/mL; effective conc ~ 450 ng/mL

message("=== Scenario 5: HCQ 400mg/day (Mild/Cutaneous Disease) ===")
sim5 <- run_sim(mod, ev_none,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 450, IFX_CSS = 0,
                                    SPON_RES = 0,
                                    GRAN0 = 30.0,    # mild disease: Stage I-II
                                    FVC_P0 = 92.0,
                                    ACE0 = 38.0,
                                    CA0 = 10.8,      # hypercalcemia at baseline
                                    CALIT0 = 55.0))  # elevated calcitriol
sim5$Scenario <- "5: HCQ 400mg/d (Mild+Hypercalcemia)"

## ─── Scenario 6: Spontaneous Resolution (Low Burden, Stage I) ──────────────
## Clinical basis:
##   Judson et al. (2000) ACCESS: ~50-70% of Stage I patients resolve spontaneously
##   Siltzbach (1961): natural history of sarcoidosis - Stage I often resolves
##   De Vries et al.: stage I bilateral hilar lymphadenopathy resolves in 60-80%
##   Within 2 years, granulomas often involute in Löfgren syndrome
## Modeled by: lower initial burden (GRAN0=20), SPON_RES=1 (antigen drive reduced)

message("=== Scenario 6: Spontaneous Resolution (Stage I, Low Burden) ===")
sim6 <- run_sim(mod, ev_none,
                param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 0,
                                    SPON_RES = 1.0,
                                    GRAN0 = 20.0,    # Stage I: bilateral hilar adenopathy
                                    FVC_P0 = 95.0,
                                    ACE0 = 35.0,
                                    SIL2R0 = 650.0,
                                    CA0 = 9.2))
sim6$Scenario <- "6: Spontaneous Resolution (Stage I)"

##==============================================================================
## COMBINE SIMULATION RESULTS
##==============================================================================

all_sims <- dplyr::bind_rows(sim1, sim2, sim3, sim4, sim5, sim6)
all_sims$Scenario <- factor(all_sims$Scenario, levels = unique(all_sims$Scenario))

## Color palette (colorblind-friendly)
scenario_colors <- c(
  "1: No Treatment"                   = "#E41A1C",
  "2: Prednisone 40mg Taper"          = "#377EB8",
  "3: Pred 20mg + MTX 10mg/wk"        = "#4DAF4A",
  "4: Infliximab 3mg/kg q8wk"         = "#FF7F00",
  "5: HCQ 400mg/d (Mild+Hypercalcemia)" = "#984EA3",
  "6: Spontaneous Resolution (Stage I)" = "#A65628"
)

##==============================================================================
## PLOT 1: Granuloma Burden Over Time
##==============================================================================
## Clinical expectation:
##   - No tx: stable or slowly increasing in moderate disease
##   - Pred taper: ~40-60% reduction at 6 mo, partial rebound after discontinuation
##   - Pred+MTX: sustained reduction maintained through 2 years
##   - Infliximab: ~40-50% reduction maintained with q8wk dosing
##   - HCQ: mild reduction (~20-30%) in Stage I
##   - Spontaneous resolution: resolution over 12-18 months

p1 <- ggplot(all_sims, aes(x = time_weeks, y = GRANULOMA, color = Scenario)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 100, linetype = "dotted", color = "gray50") +
  scale_color_manual(values = scenario_colors) +
  labs(
    title    = "Sarcoidosis QSP — Granuloma Burden Over Time",
    subtitle = paste0("Moderate pulmonary sarcoidosis (Stage II-III) baseline; ",
                      "Stage I for HCQ and Spontaneous Resolution scenarios"),
    x = "Time (weeks)",
    y = "Granuloma Burden (arbitrary units, 0-100)",
    color = "Treatment Scenario",
    caption = "Reference: ACE-25 trial (Gibson 1996), FIRST trial (Baughman 2006)"
  ) +
  scale_x_continuous(breaks = seq(0, 104, 13),
                     labels = c("0","13wk","26wk","39wk","52wk",
                                "65wk","78wk","91wk","104wk")) +
  theme_bw(base_size = 11) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        plot.title = element_text(face = "bold"))

##==============================================================================
## PLOT 2: Serum ACE and sIL-2R Biomarkers
##==============================================================================
## Clinical expectation (ACE-25 trial; Ziegenhagen 2003):
##   - Prednisone reduces ACE by ~30-40% at 6 months
##   - sIL-2R is more sensitive than ACE for disease activity
##   - MTX+pred: sustained ACE normalization over 2 years

## ACE plot
p2a <- ggplot(all_sims, aes(x = time_weeks, y = ACE, color = Scenario)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 52, linetype = "dashed", color = "red", alpha = 0.6) +
  annotate("text", x = 95, y = 53.5, label = "ULN = 52 U/L", color = "red",
           size = 3.5) +
  scale_color_manual(values = scenario_colors) +
  labs(
    title = "Serum ACE Biomarker",
    subtitle = "Normal <52 U/L; elevated in granulomatous disease",
    x = "Time (weeks)", y = "Serum ACE (U/L)",
    caption = "Ref: Studdy & Bird (1989); ACE-25 trial (Gibson 1996)"
  ) +
  theme_bw(base_size = 10) +
  theme(legend.position = "none")

## sIL-2R plot
p2b <- ggplot(all_sims, aes(x = time_weeks, y = SIL2R_UmL, color = Scenario)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 496, linetype = "dashed", color = "red", alpha = 0.6) +
  annotate("text", x = 90, y = 515, label = "ULN ~496 U/mL", color = "red",
           size = 3.5) +
  scale_color_manual(values = scenario_colors) +
  labs(
    title = "Serum sIL-2R (T-cell Activation Marker)",
    subtitle = "More sensitive than ACE for disease activity monitoring",
    x = "Time (weeks)", y = "sIL-2R (U/mL)",
    caption = "Ref: Ziegenhagen et al. (2003); Vorselaars et al. (2015)"
  ) +
  theme_bw(base_size = 10) +
  theme(legend.position = "none")

p2 <- gridExtra::grid.arrange(p2a, p2b, ncol = 2)

##==============================================================================
## PLOT 3: FVC % Predicted Over Time
##==============================================================================
## Clinical expectation:
##   - No tx: slow decline ~1-2% per year (Nardi 2011)
##   - Prednisone: +3.3% at 24 months (ACE-25 trial, Gibson 1996)
##   - Pred+MTX: +4-6% maintained at 24 months (Vorselaars 2015)
##   - Infliximab: +2.5% at 24 weeks (FIRST trial, Baughman 2006)
##   - HCQ: minimal change in pulmonary function (Stage I baseline near normal)
##   - Spontaneous resolution: recovery toward normal FVC

p3 <- ggplot(all_sims, aes(x = time_weeks, y = FVC_pct, color = Scenario)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 70, linetype = "dashed", color = "darkred", alpha = 0.7) +
  geom_hline(yintercept = 80, linetype = "dotted", color = "darkorange", alpha = 0.5) +
  annotate("text", x = 95, y = 68.5, label = "Severe <70%",
           color = "darkred", size = 3.5) +
  annotate("text", x = 95, y = 78.5, label = "Moderate <80%",
           color = "darkorange", size = 3.5) +
  scale_color_manual(values = scenario_colors) +
  scale_y_continuous(limits = c(60, 100)) +
  labs(
    title    = "Sarcoidosis QSP — FVC % Predicted Over Time",
    subtitle = "Primary pulmonary outcome; FIRST trial & ACE-25 calibration",
    x = "Time (weeks)",
    y = "FVC % Predicted",
    color = "Treatment Scenario",
    caption = paste0(
      "FIRST trial: IFX +2.5% FVC at 24wk (Baughman 2006 Chest)\n",
      "ACE-25 trial: Pred +3.3% FVC at 24mo (Gibson 1996 Eur Respir J)\n",
      "Vorselaars: Pred+MTX +4-6% FVC at 24mo (Eur Respir J 2015)"
    )
  ) +
  scale_x_continuous(breaks = seq(0, 104, 13)) +
  theme_bw(base_size = 11) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        plot.title = element_text(face = "bold"))

##==============================================================================
## PLOT 4: Serum Calcium Over Time (HCQ scenario emphasis)
##==============================================================================
## Clinical expectation (HCQ scenario):
##   - HCQ 400 mg/d reduces calcitriol production in granuloma macrophages
##   - Adams & Hewison (2012): HCQ reduces sarcoid hypercalcemia effectively
##   - Calcium normalizes within 4-8 weeks of HCQ initiation
##   - Prednisone also effective via direct suppression of CYP27B1

p4 <- ggplot(all_sims, aes(x = time_weeks, y = CALCIUM, color = Scenario)) +
  geom_line(linewidth = 0.9) +
  geom_hline(yintercept = 10.5, linetype = "dashed", color = "red", alpha = 0.6) +
  geom_hline(yintercept = 8.5,  linetype = "dashed", color = "blue", alpha = 0.4) +
  annotate("text", x = 92, y = 10.7, label = "Hypercalcemia >10.5",
           color = "red", size = 3.3) +
  annotate("text", x = 93, y = 8.3,  label = "Hypocalcemia <8.5",
           color = "blue", size = 3.3) +
  scale_color_manual(values = scenario_colors) +
  scale_y_continuous(limits = c(7.5, 12)) +
  labs(
    title    = "Serum Calcium Over Time",
    subtitle = "Sarcoid hypercalcemia driven by excess 1,25-dihydroxyvitamin D",
    x = "Time (weeks)",
    y = "Serum Calcium (mg/dL)",
    color = "Treatment Scenario",
    caption = paste0(
      "HCQ mechanism: inhibits CYP27B1 in granuloma macrophages\n",
      "Ref: Adams & Hewison (2012) J Clin Endocrinol Metab; Sharma (1996)"
    )
  ) +
  scale_x_continuous(breaks = seq(0, 104, 13)) +
  theme_bw(base_size = 11) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 8),
        plot.title = element_text(face = "bold"))

##==============================================================================
## PLOT 5: PK Profile — Prednisolone Concentration (Scenario 2)
##==============================================================================
## First 2 weeks of daily dosing — illustrates diurnal PK and accumulation
## Reference: Czock et al. (2005) — prednisolone PK at 40 mg/d

sim2_pk <- sim2[sim2$time <= 336, ]  # first 2 weeks (336 h)

p5 <- ggplot(sim2_pk, aes(x = time / 24, y = C_PREDL_OUT)) +
  geom_line(color = "#377EB8", linewidth = 0.8) +
  geom_hline(yintercept = 100, linetype = "dashed", color = "gray40") +
  annotate("text", x = 13, y = 110, label = "EC50 (immune suppression) = 100 ng/mL",
           color = "gray40", size = 3.3) +
  labs(
    title    = "Prednisolone PK — Scenario 2 (40 mg/d prednisone, first 2 weeks)",
    subtitle = "Czock et al. (2005) parameters: Vd=1.5 L/kg, CL=2.8 L/h",
    x = "Time (days)",
    y = "Prednisolone Concentration (ng/mL)",
    caption = "Ref: Czock et al. Clin Pharmacokinet 2005; Derendorf et al. Clin Pharmacol Ther 1985"
  ) +
  scale_x_continuous(breaks = 0:14) +
  theme_bw(base_size = 11)

##==============================================================================
## PLOT 6: MTX Polyglutamate Accumulation (Scenario 3)
##==============================================================================
## MTX-PG accumulate slowly over weeks; therapeutic range ~5-15 nmol/L
## Reference: Kager et al. (2014) Cancer Res

sim3_mtxpg <- sim3[sim3$time <= 52 * 168, ]  # first 52 weeks

p6 <- ggplot(sim3_mtxpg, aes(x = time_weeks, y = C_MTX_OUT)) +
  geom_line(color = "#4DAF4A", linewidth = 0.8) +
  geom_hline(yintercept = 5,  linetype = "dashed", color = "darkorange") +
  geom_hline(yintercept = 15, linetype = "dashed", color = "darkred") +
  annotate("text", x = 45, y = 5.8,  label = "EC50 = 5 nmol/L", color = "darkorange", size = 3.3) +
  annotate("text", x = 44, y = 15.8, label = "High therapeutic range", color = "darkred", size = 3.3) +
  labs(
    title    = "MTX Polyglutamate (MTX-PG) Accumulation — Scenario 3",
    subtitle = "Weekly MTX 10 mg/wk; intracellular PG accumulate over weeks",
    x = "Time (weeks)",
    y = "MTX Polyglutamates (nmol/L)",
    caption = "Ref: Kager et al. Cancer Res 2014; Bressolle et al. J Clin Pharmacol 1998"
  ) +
  scale_x_continuous(breaks = seq(0, 52, 4)) +
  theme_bw(base_size = 11)

##==============================================================================
## COMBINED 4-PANEL EFFICACY PLOT
##==============================================================================

p_combined <- gridExtra::grid.arrange(
  p1 + theme(legend.position = "none",
             plot.title = element_text(size = 10, face = "bold"),
             plot.subtitle = element_text(size = 8)),
  p3 + theme(legend.position = "none",
             plot.title = element_text(size = 10, face = "bold"),
             plot.subtitle = element_text(size = 8)),
  p2a + theme(plot.title = element_text(size = 10, face = "bold")),
  p4 + theme(legend.position = "none",
             plot.title = element_text(size = 10, face = "bold"),
             plot.subtitle = element_text(size = 8)),
  ncol = 2,
  top = grid::textGrob("Sarcoidosis QSP Model — 6 Treatment Scenarios",
                        gp = grid::gpar(fontsize = 13, fontface = "bold"))
)

##==============================================================================
## SUMMARY STATISTICS TABLE
##==============================================================================

summary_tbl <- all_sims |>
  dplyr::filter(time_weeks %in% c(0, 13, 26, 52, 78, 104)) |>
  dplyr::group_by(Scenario, time_weeks) |>
  dplyr::summarise(
    FVC      = round(mean(FVC_pct), 1),
    ACE_UL   = round(mean(ACE), 1),
    GRAN_AU  = round(mean(GRANULOMA), 1),
    Ca_mgdL  = round(mean(CALCIUM), 2),
    sIL2R    = round(mean(SIL2R_UmL), 0),
    .groups  = "drop"
  ) |>
  dplyr::rename(
    `Time (wk)` = time_weeks,
    `FVC %pred` = FVC,
    `ACE (U/L)` = ACE_UL,
    `Granuloma` = GRAN_AU,
    `Ca (mg/dL)` = Ca_mgdL,
    `sIL-2R (U/mL)` = sIL2R
  )

message("\n=== Summary: Key Outcomes at Selected Timepoints ===")
print(summary_tbl, n = Inf)

## Change from baseline for FVC (primary endpoint)
fvc_change <- all_sims |>
  dplyr::filter(time_weeks %in% c(0, 26, 52, 104)) |>
  dplyr::group_by(Scenario, time_weeks) |>
  dplyr::summarise(FVC_pct = mean(FVC_pct), .groups = "drop") |>
  dplyr::group_by(Scenario) |>
  dplyr::mutate(
    FVC_baseline = FVC_pct[time_weeks == 0],
    FVC_change   = round(FVC_pct - FVC_baseline, 2)
  )

message("\n=== FVC Change from Baseline (primary clinical endpoint) ===")
print(dplyr::select(fvc_change, Scenario, `Time (wk)` = time_weeks,
                    FVC_pct, FVC_change))

##==============================================================================
## SENSITIVITY ANALYSIS: Effect of EC50_pred on FVC response
##==============================================================================
## Demonstrates model sensitivity to PD parameter uncertainty
## EC50 range: 50-200 ng/mL (literature uncertainty)
## (param renamed EC50_pred -> EC50_PREDL, see refactor notes)

message("\n=== Sensitivity Analysis: Prednisolone EC50 on FVC (Scenario 2) ===")

ec50_values <- c(50, 100, 150, 200)
sens_list <- lapply(ec50_values, function(ec50) {
  sim_s <- run_sim(mod, ev_pred40,
                   param_update = list(AZA_CSS = 0, HCQ_CSS = 0, IFX_CSS = 0,
                                       SPON_RES = 0, EC50_PREDL = ec50))
  sim_s$EC50_PREDL <- ec50
  sim_s
})
sens_df <- dplyr::bind_rows(sens_list)
sens_df$EC50_label <- factor(paste0("EC50=", sens_df$EC50_PREDL, " ng/mL"))

p_sens <- ggplot(sens_df, aes(x = time_weeks, y = FVC_pct, color = EC50_label)) +
  geom_line(linewidth = 0.8) +
  scale_color_brewer(palette = "RdYlBu", direction = -1) +
  labs(
    title    = "Sensitivity Analysis: Prednisolone EC50 Effect on FVC",
    subtitle = "Scenario 2 (Prednisone 40mg taper); EC50 range 50-200 ng/mL",
    x = "Time (weeks)", y = "FVC % Predicted",
    color    = "EC50 (ng/mL)",
    caption  = "EC50 calibrated to ACE-25 trial data; uncertainty range shown"
  ) +
  theme_bw(base_size = 11)

message("\n=== All plots generated. Displaying... ===")

## Print all plots
print(p1)
print(p3)
print(p4)
print(p5)
print(p6)
print(p_sens)
print(p_combined)

##==============================================================================
## MODEL VALIDATION SUMMARY
##==============================================================================
## Calibration targets from clinical trials:
##
##  1. ACE-25 trial (Gibson 1996):
##     - Prednisone 40 mg/d x 3 months: ACE reduced ~30-40% at 6 months
##     - FVC improved +3.3% vs. placebo at 24 months
##     - Model outputs: check ACE at 26 wk and FVC at 104 wk for Scenario 2
##
##  2. FIRST trial (Baughman 2006 Chest):
##     - Infliximab 3 mg/kg: FVC improved +2.5% at 24 weeks vs. placebo
##     - Model outputs: compare FVC at 26 wk (Scenario 4 vs. 1)
##
##  3. Vorselaars 2015 (Eur Respir J):
##     - MTX 10 mg/wk + pred: FVC +4-6% at 24 months
##     - sIL-2R decreased significantly in MTX arm
##     - Model outputs: Scenario 3 FVC and sIL-2R at 104 wk
##
##  4. HCQ and hypercalcemia:
##     - Adams & Hewison (2012): HCQ 200-400 mg/d normalizes calcium in 4-8 wk
##     - Model outputs: CALCIUM in Scenario 5 at 8-12 wk
##
##  5. Spontaneous resolution (ACCESS cohort, Judson 2000):
##     - Stage I: 60-70% resolve within 2 years
##     - Model outputs: GRANULOMA in Scenario 6 should approach 0-10 by wk 104

validation_targets <- data.frame(
  Trial      = c("ACE-25 (Gibson 1996)", "ACE-25 (Gibson 1996)",
                 "FIRST (Baughman 2006)", "Vorselaars 2015",
                 "Adams & Hewison 2012", "ACCESS (Judson 2000)"),
  Endpoint   = c("FVC % change at 24mo", "ACE % change at 6mo",
                 "FVC % change at 24wk", "FVC % change at 24mo",
                 "Calcium normalization (wk)", "Spontaneous resolution (%)"),
  Observed   = c("+3.3%", "-30 to -40%", "+2.5%", "+4-6%", "4-8 wk", "60-70%"),
  Scenario   = c("2 (Pred 40mg taper)", "2 (Pred 40mg taper)",
                 "4 (Infliximab)", "3 (Pred+MTX)",
                 "5 (HCQ)", "6 (Spontaneous)"),
  stringsAsFactors = FALSE
)

message("\n=== Clinical Validation Targets ===")
print(validation_targets)

## Extract key model outputs for validation
val_check <- dplyr::bind_rows(
  sim2 |> dplyr::filter(abs(time_weeks - 24) < 1) |>
    dplyr::summarise(Trial = "ACE-25 FVC at 24wk",
                     Model_value = mean(FVC_pct) - FVC_P0,
                     Observed = "+3.3%"),
  sim2 |> dplyr::filter(abs(time_weeks - 26) < 1) |>
    dplyr::summarise(Trial = "ACE-25 ACE at 6mo",
                     Model_value = (mean(ACE) - ACE0) / ACE0 * 100,
                     Observed = "-30 to -40%"),
  sim4 |> dplyr::filter(abs(time_weeks - 24) < 1) |>
    dplyr::summarise(Trial = "FIRST FVC at 24wk (vs baseline)",
                     Model_value = mean(FVC_pct) - FVC_P0,
                     Observed = "+2.5%"),
  sim3 |> dplyr::filter(abs(time_weeks - 104) < 1) |>
    dplyr::summarise(Trial = "Vorselaars FVC at 24mo",
                     Model_value = mean(FVC_pct) - FVC_P0,
                     Observed = "+4-6%")
)
val_check$Model_value <- round(val_check$Model_value, 2)

message("\n=== Model Validation vs. Clinical Targets ===")
print(val_check)

message("\n=== Sarcoidosis QSP mrgsolve model simulation complete ===")
